### ISSUE TITLE
Crash on keybind reassign.

### ISSUE THREAD

**Issue by DaringShepard** [Sollace/Unicopia#1]
Title. Only running this mod, MineLP, and JumpingCastle. Though it also happens on more heavily modded setups, as well. 

Crash occurs when in-game and reassigning (not the main menu). It also will crash when attempting to load into a world with the changed keys.

Keys changed, for reference, can assume it happens with the others, as well:
key_unicopia.power.feed:-96
key_unicopia.power.disguise:-97

- Crashlog:
https://paste.dimdev.org/xonojokone.cs

- Full log:
https://paste.dimdev.org/zuzanecuka.md

**Comment by Sollace** [comment]
Try to stick to keyboard buttons for now. I'll fix mouse button support in a later build.
