### ISSUE TITLE
Unable to include Unicopia in Curseforge packs

### ISSUE THREAD

**Issue by MarcyMuffins** [Sollace/Unicopia#10]
The mod isnt on curse and isnt on the Third Party Mod approved list, which means the mod wont be included in any packs uploaded to curse, which leaves me with 2 options:
1. Remove the mod and upload to curse
2. Upload the pack to github, where noone will see it

I advise you to try and upload the mod to curse as soon as possible

**Comment by Sollace** [comment]
As the mod is still in early alpha, I won't be publishing it to curse.
