### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by ScootalooCMC** [Sollace/Unicopia#105]
Trying to use this mod on a server, but keep getting this issue where it says server is missing required mods and to remove them from the client list. However the mod isnt missing from the server, its there. One other thing is the server detected the mod was missing and requested us to update the client list before it started telling us to remove it. 

![imagewesdgfs](https://user-images.githubusercontent.com/94259160/227124332-1d382f48-a2dd-4535-a3f0-62b659651883.png)

**Comment by Sollace** [comment]
Try adding the latest version of Fabwork on both the client and server.

https://modrinth.com/mod/fabwork/version/1.1.9

Unicopia has a version bundled, but it is currently out of date.

**Comment by ScootalooCMC** [comment]
Cool, seems to be working now. Thanks.
