### ISSUE TITLE
Skill Wheel

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#112]
To reduce keybinds and allow more room for further skills, specifically more slots for unicorn spell casting, I believe it would be a good idea to replace the current skill/ability selection HUD with a quick select menu like the skill wheel below.

![image](https://user-images.githubusercontent.com/75338505/232115247-ec5b94ae-efc2-4001-bd2a-6f451a6a5a4a.png)

video of it being used in gameplay here:
https://www.youtube.com/watch?v=r6Vc9kUP84o&feature=youtu.be

**Comment by drowsiestprince** [comment]
Maybe spellbooks would disappear with use and the spell would naturally appear in one of these menus instead to prevent inventory clutter

**Comment by BlasterM5** [comment]
A skill wheel, this would solve a lot of button mashing problems, and let the 5 people that use the xbox controller mod do abilities easier.
