### ISSUE TITLE
Inability to buck/use crushing blow on mobs

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#115]
I feel that crushing blow should be usable on mobs and other players rather than only trees, as we've seen it used for offense in the show before.

**Comment by Sollace** [comment]
I believe the buck can already be used on entities. I specifically remember kicking around armour stands and creepers whilst testing it.

**Comment by Sollace** [comment]
Bucking entities is working. It' short range, so you have to be close, and it triggers with the quick action, so tap the key once to kick, not hold or double-tap.
