### ISSUE TITLE
Major bug in multiplayer causing crashes and corrupting files

### ISSUE THREAD

**Issue by Silversky13** [Sollace/Unicopia#118]
Currently happening on version 1.0.0-beta.30+lts on 1.19.2.

If you are playing on a multiplayer server and a player disconnects from the server while holding an entity using the carry ability it will crash the server completely citing a "java.lang.NullPointerException: Cannot read field "field_6002" because "entity" is null" error. 

Additionally, any other players connected to the server at the time of the crash will have all of their player data permanently corrupted, which will cause the server to crash immediately anytime they attempt to rejoin.

The original player that logged out will not have their data corrupted, only all other players on the server at the time of the crash. 

The only way to salvage and restore the server at that point requires you to delete the corrupted playerdata .dat file and edit the usercache.json file to reset that player completely causing them to lose all equipment and all progress in their race. You then have to have a non-corrupted player join the server before it will allow anyone that has been reset to rejoin.

I've included the crash report as an attachment with minor edits for privacy. Just thought you should know since it seems like a major issue.

[crash-2023-05-28_02.18.59-server record.txt](https://github.com/Sollace/Unicopia/files/11585966/crash-2023-05-28_02.18.59-server.record.txt)

Thanks for taking your time to make this mod

**Comment by Sollace** [comment]
Can you test with the 1.1.0 beta to see if the problem persists?

**Comment by Silversky13** [comment]
Unfortunately some of the other mods on the server aren't capable of being updated to 1.19.3 so I won't be able to do that without potentially breaking the server for now, sorry. Eventually, when I reset the server again, I'll be able to test it again in a later update. 

I just wanted you to know about the bug in the meantime. sorry I couldn't be more helpful
