### ISSUE TITLE
Cocoon item isn't very useful

### ISSUE THREAD

**Issue by fin600** [Sollace/Unicopia#12]
After the arduous process of getting gems and whole slime blocks to craft the cocoon item, it's only used to be cooked to get chitinous shells. I can't recommend it to be used to get hive blocks, because hive blocks very much feel like an upgrade to chitin. Either it needs to be an ingredient in more things, or have its own use. Perhaps some special changeling foods?

Edit: It takes 8 slime blocks to get 1 cocoon. 1 cocoon per chitinous shell. You need 9 chitinous shell for 1 chitin block. That's 72 slime balls per cocoon, and 648 slime balls total per chitin block. That's ridiculous even for changelings.

**Comment by Sollace** [comment]
Note also that you can farm slime balls without finding slimes. (those plants that hang from hive blocks)

**Comment by fin600** [comment]
That actually requires hive blocks to be craftable, though, [see the issue](https://github.com/Sollace/Unicopia/issues/11) on that. Hive blocks also don't always spawn the slime drips. Breaking the drips by hand doesn't make them drop anything either, they only give slime when they break naturally by being too near another block or when they reach max thickness. They give about 2-3 slime per break, which isn't much better than the thin slime left behind from the engulf attack. The thin slime gives 2 slime balls per thin slime, 4 if you use a fortune 3 shovel. It's still ridiculous to expect someone to gather almost 650 slime balls per chitin block. Singular chitin block.

Maybe that'd be a good use for the cocoon item, a way to farm a lot of slime?

Edit: With a fortune 3 shovel, you'd have to break 162 thin slime. With a normal shovel, that's 324 thin slime. Or waiting for 216 slime drips to break. That's a _lot_ for something meant to be a building material!
