### ISSUE TITLE
Flight and Alternate Worlds

### ISSUE THREAD

**Issue by BlasterM5** [Sollace/Unicopia#120]
Edit: Oops, pressed Enter instead of Tab

Prevent flying with a dimension check, for use with specific popular other dimension mods, such as Ad Astra, which is a reimagined Galacticraft, where you go to different planets. Have it where winged flight doesn't work on the moon, in space, or on mercury (other worlds, flight is possible because atmosphere, unless the suit model negates wings in mlp).

**Comment by Sollace** [comment]
Alrighty! In the 1.20 update you'll be able to disable pegasus flight on other planets using a datapack. Just add the planet's dimension type id to the c:has_no_atmosphere tag like you would block tags.

Eg. To disable flight in the end, you'd do this:

```
{
  "replace": false,
  "values": [
     "minecraft:the_end"
  ]
}
```
And it goes in `/data/c/tags/dimension_type/has_no_atmosphere.json` within your datapack.
