### ISSUE TITLE
Changelings Climb

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#122]
It'd be fun for changelings to have the ability to climb walls and ceilings like they did in the show! Also adds to their creep/sneak factor.

**Comment by xyzzy121** [comment]
Agreed. And imagine being sniped by a block of stone on a high ceiling.

**Comment by Sollace** [comment]
Do you have a reference where changelings are shown to be able to climb? I believe I remember that being something they could do but I don't remember which episode it was.

Right now the climbing ability is limited to the spider form when shapeshifting. Extending that to (untransformed) changelings is something I could do, just want to have the show as a reference so I know it's more or less in line with canon.

**Comment by PrinceDrowsy** [comment]
No prob dawg!

![image](https://github.com/Sollace/Unicopia/assets/75338505/1a81fe1a-8fa1-4cba-b9f7-c8ed8e4d2713)

![image](https://github.com/Sollace/Unicopia/assets/75338505/b7ef9d19-5845-4def-a904-052127444f4f)

**Comment by Sollace** [comment]
That last one I always just assumed they were flying 🤔

**Comment by PrinceDrowsy** [comment]
> That last one I always just assumed they were flying 🤔

their wings aren't moving while they crawl down the pillars

**Comment by xyzzy121** [comment]
Well, it’s kind of pointless to have an invert gravity function, if you can’t walk on the ceiling or the walls.
________________________________

**Comment by PrinceDrowsy** [comment]
> 

since when could they invert gravity? ?? ?

**Comment by xyzzy121** [comment]
They can't, but we already have the batpony hang-from-ceiling function. I was kind of annoyed that you couldn't walk on the ceiling. This seems like the perfect place for that.

**Comment by PrinceDrowsy** [comment]
> They can't, but we already have the batpony hang function. I was kind of annoyed that you couldn't walk on the ceiling. this seems like the perfect place for that.

ohhhhhhh okay. sorry, i got a little confused there.

**Comment by xyzzy121** [comment]
> > They can't, but we already have the batpony hang function. I was kind of annoyed that you couldn't walk on the ceiling. this seems like the perfect place for that.
> 
> ohhhhhhh okay. sorry, i got a little confused there.

You're fine! Imagine it though, You are a stone block sniping people from the vaulted ceiling of a cavern. Glorious.

**Comment by PrinceDrowsy** [comment]
> > > They can't, but we already have the batpony hang function. I was kind of annoyed that you couldn't walk on the ceiling. this seems like the perfect place for that.
> > 
> > 
> > ohhhhhhh okay. sorry, i got a little confused there.
> 
> You're fine! Imagine it though, You are a stone block sniping people from the vaulted ceiling of a cavern. Glorious.

 awesome. it'd be great if changelings could crawl around on ceilings and walls. it'd be cool to see batponies crawl on ceilings, but maybe be restricted by block types in a way that changelings wouldn't? since they're actively grabbing onto things to dangle like bats while changelings work like bugs and just kinda naturally stick to things with... what i believe is a special type of microscopic hair coating that bugs have if i'm remembering right? i also just really enjoy slight differences of how species use certain similar abilities.

**Comment by xyzzy121** [comment]
> awesome. it'd be great if changelings could crawl around on ceilings and walls. it'd be cool to see batponies crawl on ceilings, but maybe be restricted by block types in a way that changelings wouldn't? since they're actively grabbing onto things to dangle like bats while changelings work like bugs and just kinda naturally stick to things with... what i believe is a special type of microscopic hair coating that bugs have if i'm remembering right? i also just really enjoy slight differences of how species use certain similar abilities.

I picture Changelings just digging their claws in with stone, and perhaps a bit of magic. They feel like they should be the mlp equivalent of a xenomorph in creep factor, and I couldn't picture a xenomorph crawling around on the ceiling WITHOUT digging its claws into whatever surface it's on.

**Comment by PrinceDrowsy** [comment]
That _is_ pretty cool sounding....

**Comment by xyzzy121** [comment]
LETS GO!
