### ISSUE TITLE
Slightly Longer Range on Crushing Blow

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#124]
Maybe slightly longer range for offense purposes when using MineLP? Tad difficult to get a good shot.

**Comment by Sollace** [comment]
Maybe try using the stomp instead? 

Jump whilst hitting the key to slam into the ground, and deal knockback to surrounding entities.

Crushing blow is more intended for stationary targets, since as a pony you can only really hit things behind you.
