### ISSUE TITLE
Wrong command output

### ISSUE THREAD

**Issue by LingVarr** [Sollace/Unicopia#125]
After typing "/race get NICKNAME" I'm getting this: 
![2023-06-25_02 51 45](https://github.com/Sollace/Unicopia/assets/104311317/bd07c7ed-f86d-4631-b0ec-30aea535381e)
Instead of "%s" should be my nickname, right?

**Comment by Sollace** [comment]
I believe to get your own race you can do `/race get`

`/race get <name>` is for getting the race of a specific player. The output formatting is a bug though.
