### ISSUE TITLE
Problem with Element pages in the Spellbook when Sodium enabled

### ISSUE THREAD

**Issue by LingVarr** [Sollace/Unicopia#127]
The pages with all elements and items that contain this elements are not loading properly when Sodium enabled.
![2023-06-25_02 53 23](https://github.com/Sollace/Unicopia/assets/104311317/fc54a1c2-12eb-4807-b86a-e085b5db6fbc)
Only one page of random (I think) element shows. Without Sodium everything works normally. Interesting that after re-enabling Sodium game gets very laggy while the page is open (huge fps drop).

**Comment by Sollace** [comment]
This is another case of https://github.com/CaffeineMC/sodium-fabric/issues/1602

I actually forgot about the issue, so never worked my way around to finding a fix.
