### ISSUE TITLE
Game crash when Changeling change into Spawner

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#130]
![截屏2023-06-29 12 01 49](https://github.com/Sollace/Unicopia/assets/131762804/00b4cd4b-1eab-4e16-9a9d-99dca12901b0)
game version 1.20.1

**Comment by Sollace** [comment]
Sorry can you attach the crash report? Gonna need to the stacktrace to see what happened here.

**Comment by Cryghast** [comment]
[crash-2023-07-07_17.43.52-client.txt](https://github.com/Sollace/Unicopia/files/11980422/crash-2023-07-07_17.43.52-client.txt)


> Sorry can you attach the crash report? Gonna need to the stacktrace to see what happened here.

**Comment by Sollace** [comment]
> [crash-2023-07-07_17.43.52-client.txt](https://github.com/Sollace/Unicopia/files/11980422/crash-2023-07-07_17.43.52-client.txt)
> 
> > Sorry can you attach the crash report? Gonna need to the stacktrace to see what happened here.

Excellent. Thanks!
