### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by pxnksxda** [Sollace/Unicopia#133]
Hello! I'm trying to set up a server for my friends and I to play on, but I'm met with the message, "Server is missing required mod(s). Remove these from your client to join this server. [unicopia]".
I've ensured that Unicopia is present in both the server mods folder and the launcher instance mods folder, and even followed the advice from another thread detailing this same issue (I installed Fabwork for 1.20 intead of 1.19 as that's the version I'm playing) and that also did not help the issue.

**Comment by Sollace** [comment]
Fabwork is included as part of unicopia. You shouldn't have to install is separately.

Can you provide logs for both the client and server taken when this happens please?

**Comment by pxnksxda** [comment]
[Here is my log from my client](https://docs.google.com/document/d/1keB6WBgzJq_Z4ZTaAHTfRhTEAvu8BEbIFOT-EgouTNE/edit?usp=sharing)! It's everything from my session today to grab the logs, it's a bit lengthy. And here's the image of my server log from my attempt to join the server.
![Screenshot 2023-07-09 181648](https://github.com/Sollace/Unicopia/assets/138330591/58796a2d-9af8-4905-9940-183925c9e14a)

**Comment by MimzyFang** [comment]
> [Here is my log from my client](https://docs.google.com/document/d/1keB6WBgzJq_Z4ZTaAHTfRhTEAvu8BEbIFOT-EgouTNE/edit?usp=sharing)! It's everything from my session today to grab the logs, it's a bit lengthy. And here's the image of my server log from my attempt to join the server. ![Screenshot 2023-07-09 181648](https://user-images.githubusercontent.com/138330591/252175319-58796a2d-9af8-4905-9940-183925c9e14a.png)

The client log you provided doesn't seem to have the actual game log please go into your curseforge instances folder go into the .minecraft folder of it find the log folder and upload the latest.log to something like [mclogs](https://mclo.gs)

also look into getting a launcher that supports both curseforge and modrinth as it will make auto updating of Unicopia possible since Unicopia is on modrinth 
my personal recommendation would be prism launcher, but it's up to you

**Comment by Sollace** [comment]
Closing as stale

**Comment by tlitookilakin** [comment]
I'm having this issue still in 1.20.4 with Quilt, even in singleplayer. [Game Log](https://mclo.gs/aSvYDuk). Does *not* occur using an identical setup with fabric.

**Comment by MimzyFang** [comment]
> I'm having this issue still in 1.20.4 with Quilt, even in singleplayer. [Game Log](https://mclo.gs/aSvYDuk). Does _not_ occur using an identical setup with fabric.

this could be an issue between the 1.20.4 version of qfapi with Fabwork 

@Sollace any way I could confirm that without needing to add unicopia?

if I can confirm that assumption I'm going to report it to quilt as qfapi for 1.20.4 is pretty much in alpha rn and known to be a bit buggy especially with networking
