### ISSUE TITLE
Game crash when a mob died with alicorn_amulet

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#134]
![截屏2023-07-02 14 55 01](https://github.com/Sollace/Unicopia/assets/131762804/f2c62b6d-ca8a-4d03-8a49-17b512d8e3e5)
![截屏2023-07-02 14 49 38](https://github.com/Sollace/Unicopia/assets/131762804/865fa50d-d484-4cd6-a9d9-a7ae555cb154)

**Comment by Fangliding** [comment]
It is clear that the code of Alicorn Amulet does not have logic to handle entities other than players, causing the issue. Disabling the item from being picked up by entities might be help.
