### ISSUE TITLE
Here, an artwork for you all

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#140]
![3C04B2F4-A79D-47E9-A173-0519016A026F_1_102_o](https://github.com/Sollace/Unicopia/assets/131762804/cb447640-d78b-4098-adf4-8c253149275e)
https://trixiebooru.org/images/3158553

**Comment by Sollace** [comment]
I love it! Thank you ^-^

Unfortunately I'm going to have to close this, though, because the issue tracker is meant for actual issues. You are welcome to come and share it on the mine little pony discord though. 

https://discord.gg/zKSZ8Mg
