### ISSUE TITLE
In-game Guide to Mod

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#147]
It'd be cool if there were an in-game friendship journal themed guide you'd spawn with on how to use this mod! Things like basic controls, how to fly, what some of the abilities do, etc.

**Comment by Sollace** [comment]
Not something I really want to do, sorry.

It's not a feature I've ever really liked when large mods dump  abook on you at spawn, plus you already have the spellbook and the gui for picking your race lists the abilities you get.
