### ISSUE TITLE
Special Talent/Cutie Mark System for Ponies

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#148]
I think that after you pick your species, there should be a secondary system for the main three pony species + bat ponies where you can pick a "special talent" of sorts by choosing a buff from one of various systems, like a flight system buff where you can fly faster, or a different flight buff where you could fly steadier in storms, or a magic system buff where you can get an extra use outta a spell gem, or level up the spell book faster. There can also be more basic minecraft skill buffs unrelated to the unicopia systems.

All in all, I think this would be a good way to keep the ponies unique from other species! I find it vital that all the species have their own unique gameplay aspect/thing that makes them special.

I'd love to see people recommend other types of talent buffs!

**Comment by xyzzy121** [comment]
I'd definitely love an endurance buff that make hunger go down slower.

**Comment by PrinceDrowsy** [comment]
Perhaps an option to start as a blank flank and randomly gain a cutie mark as you do various tasks in minecraft that could correlate to certain cutie marks? like the game randomly picks one for you out of the selectable options, but the player doesn't know what it is, and you don't get it until you do something relating to it. like getting an animal cutie mark taming a wolf, or a farming cutie mark by bucking apples

**Comment by PrinceDrowsy** [comment]
Animal Handling Talent (some of these skills can potentially be unlocked by practicing your talent and leveling up in it?)

- Higher rate of taming animals with less effort
- Can command animals to follow you without holding any items, however there is a chance of this skill not working, with changing rates of success depending on the animal (goats being the most stubborn/least likely to listen, and passive mobs like sheep being the most likely.)
- Potentially a chance to get multiple babies out of animal breeding?
- Can convince some mobs to fight for you
- Alternatively, can convince certain hostile mobs to leave you alone for a temporary amount of time?

**Comment by PrinceDrowsy** [comment]
Farming (rock and plant variants)

Plant

- Quicker growing regardless of race
- Higher harvest yield
- Potential to harvest special crop variants with a higher saturation to hunger?
- More seeds from things like grass

Rock

- Quicker mining regardless of race
- Higher ore yield
- Perhaps a ore location skill that highlights one strip of ore in the area? High cooldown.

**Comment by Cryghast** [comment]
> Perhaps an option to start as a blank flank and randomly gain a cutie mark as you do various tasks in minecraft that could correlate to certain cutie marks? like the game randomly picks one for you out of the selectable options, but the player doesn't know what it is, and you don't get it until you do something relating to it. like getting an animal cutie mark taming a wolf, or a farming cutie mark by bucking apples

We would surly need meadowbrook‘s staff.
