### ISSUE TITLE
Minecraft Version?

### ISSUE THREAD

**Issue by DarkClippy** [Sollace/Unicopia#16]
Hello, Sollace. Sorry for asking a probably dumb question, but I couldn't find any information while looking through your hub that references what Minecraft version this is running on.

I'm in 1.5.2 now for the original Mine Little Brony mod and I need to know this. x3

**Comment by Sollace** [comment]
Unicopia is on 1.12.2 (last version).

A 1.14.4 port was started, but I'm waiting for some additions to fabric before I can continue it.

**Comment by DarkClippy** [comment]
Oooh, I'm excited to have pony powers in 1.14! x3 That's 2/3 at least, but I think TheWeatherPony is going to be awhile with Mine Little Brony 2.

And I'm assuming you would post that 1.14 version in this same hub, right? Just asking to make sure before I subscribe, because I'm pretty new to GitHub.

**Comment by Sollace** [comment]
Yeah. This is _the_ Unicopia project. If anything happens, it's going to come here.
