### ISSUE TITLE
Changeling Crawling Visuals + Descent Button

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#164]
It'd be interesting if when changelings crawl up walls, they look as though they're crouch walking on it sideways. Same with ceiling crawling, but upside down. Not only would it be visually interesting, it'd be accurate to how they crawl in canon. Also it'd be nice to suddenly and scarily drop off ceilings or slowly crawl down walls by holding shift.

**Comment by Sollace** [comment]
> Also it'd be nice to suddenly and scarily drop off ceilings or slowly crawl down walls by holding shift.

You can already do both of these.

Jump to drop from the ceiling, shift to hang onto walls without falling (same as ladders).
