### ISSUE TITLE
Replacement Pegasus Descent/Diving Method

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#165]
To make the new dives easier, and descent itself as well, perhaps the button should be changed from shift to simply looking straight down with the camera? Like you can still angle the camera down to look out below, but if you look straight down you begin to descend as a result of "angling your body down" to realistically see that far down. I know I was the one who suggested shift in my original post on the matter, but with new updates and the current flapping use for shift, this option might work better for future and current additions to the flight system. 

Alternatively, the tab button could be used instead.

**Comment by PrinceDrowsy** [comment]
Maybe you just barely begin to descend as you start looking down, and then the further down you look, the quicker you descend as you "angle your body" with your head in flight? Like how turning works. OH and maybe holding space negates this effect entirely so pegasi can look down without diving on accident!

**Comment by Sollace** [comment]
Flying already kind of follows the direction you look. i.e. flapping boosts you in the direction you look. I've been told doing too much based on where you look might become annoying, and I still intend for pegasi to be able to build whilst flying, so I don't think this is a good idea.

**Comment by PrinceDrowsy** [comment]
> Flying already kind of follows the direction you look. i.e. flapping boosts you in the direction you look. I've been told doing too much based on where you look might become annoying, and I still intend for pegasi to be able to build whilst flying, so I don't think this is a good idea.

Perhaps just switching the descent button to tab instead then so that flapping can be the only flight action on shift?
