### ISSUE TITLE
Cloud Blocks

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#167]
Perhaps the bust cloud option could be the grab cloud option when you're not holding a jar, and allow you to gain cloud blocks to build pegasus homes in the sky, or other structures! Non-pegasus ponies can't walk on clouds canonically, so you can use this to make your fortress a little less accessible, and unicorns and earth ponies have to either find spells or brew potions to temporarily gain the ability to walk on these objects.

Normal clouds could be obtainable by grabbing a cloud whenever you want during clear skies, but you could potentially also get storm cloud blocks that shoot lighting or rain out from underneath them when jumped on (as we've seen Rainbow do before.)

**Comment by Sollace** [comment]
This is an already planned feature. Thanks for making the issue though! I'll mark it as planned so that when it's added to the mod you'll be notified when this issue is closed.

**Comment by PrinceDrowsy** [comment]
Awesome!!!

**Comment by PrinceDrowsy** [comment]
> This is an already planned feature. Thanks for making the issue though! I'll mark it as planned so that when it's added to the mod you'll be notified when this issue is closed.

Oh, one more addition just in-case, but it'd be nice to place down jars of clouds as blocks to display by shift-right clicking, like Fluttershy's dad does in the show

**Comment by PrinceDrowsy** [comment]
> This is an already planned feature. Thanks for making the issue though! I'll mark it as planned so that when it's added to the mod you'll be notified when this issue is closed.

OH and I promise this is the last one, but it'd be cool if the cloud blocks negate kinetic damage, so you don't get hurt at all or at least as badly when crashing into them.

**Comment by xyzzy121** [comment]
I imagine cloud blocks being something like the ones from this:
https://github.com/AlexModGuy/CloudStorage
