### ISSUE TITLE
Dust Cloud Effect During Earth Pony Stomp

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#169]
It'd be really cool if a large ring of brown dust particles kicked up around an earth pony when they used their ground pound ability!!! It could also be effective as a way to blind enemies for a very short period of time if they're too close when it happens, and get a face full of dirt or sand.

Optionally, it'd be cool for bucking to also kick up dust like this (albeit a significantly smaller amount) when bucking without an actual target, or when missing an intended target.

**Comment by Sollace** [comment]
I already try to do something like this for other earth pony abilities. It's not really very well done though (not like the Effective mod) so if I were to add this I'd have to first redo the other effects and make dedicated particles for them.
