### ISSUE TITLE
how do I download/use this mod?

### ISSUE THREAD

**Issue by NXTerminator** [Sollace/Unicopia#17]
Total noob question, and my apologies for that, but I am familiar with the typical drag and drop jar files for most mods, however I am completely new to Github. Does this mod need to be compiled or something, because I have a huge feeling I am doing something wrong. I tried looking around before writing this, but I can't seem to find anything.

**Comment by Sollace** [comment]
Hi, NX. You can find the most recent version of the mod on the releases page. https://github.com/Sollace/Unicopia/releases

Take note that this mod is still in early development, and so might have some bugs or missing features.

**Comment by NXTerminator** [comment]
ok, and the latest release is 1.12.2 (MC version) right? also there are 4 files in each version. Let's take the latest release for example:
Unicopia-mc.1.12.2-inDev2.11.jar
Unicopia-redux-inDev2.11-sources.jar (I presume the 2 .jar files above are simple drag and drop like most .jar file mods, am I correct?)
Source code (zip) (I am familiar with compressed files, but idk if/how they can be used with Minecraft)
Source code (tar.gz) (Idk anything about this type of file)

Which ones do I use, and how do I use them to get all the assets? Every time I've tried I seem to be missing assets or something. I figure I am just overlooking something that might be obvious to people who frequently use Github.

Oh, and thank you for your help btw, I really appreciate it

Edit: I keep getting this error, once again I keep getting the itching feeling its user error on my end:
![2019-10-06_14 12 24](https://user-images.githubusercontent.com/56183249/66274365-80a10580-e843-11e9-97f9-84489702d750.png)

Here's the log:
[latest.log](https://github.com/Sollace/Unicopia/files/3694772/latest.log)

**Comment by Sollace** [comment]
@NXTerminator Only use the first one (`Unicopia-mc.1.12.2-inDev2.11.jar`) The others are for mode developers.

You can find JumpingCastle over here: https://www.curseforge.com/minecraft/mc-mods/solnet-jumping-castle

**Comment by NXTerminator** [comment]
Ah, thank you. Now I have another problem though. the game loads up, but as soon as I create/load a world, the game crashes (It gets to "Loading Terrain", then it crashes). I am using the latest 1.12.2 version of forge and the following mods (the 1.12.2 folder is empty):
![image](https://user-images.githubusercontent.com/56183249/66275600-d2e82380-e84f-11e9-8038-a76a6bf801d6.png)

If it makes any significant difference, I have set up the game to load from a custom directory location, using the vanilla launcher's installation feature, to test Unicopia since I was having issues with it.

Mine Little Pony and Liteloader work just fine when loaded without Unicopia, am I doing something wrong again?

Here's the crash report:
[crash-2019-10-06_15.48.45-client.txt](https://github.com/Sollace/Unicopia/files/3694845/crash-2019-10-06_15.48.45-client.txt)

**Comment by NXTerminator** [comment]
I feel like the above needs to be moved to a new issue, I appreciate all your help
