### ISSUE TITLE
Sapient Horses

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#174]
It'd be really funny and make a bit of sense for the MLP universe if horses could have a wandering trader-esque menu to interact with. We do know they exist as a separate species thanks to the mask Granny Smith wears in Scare Master.

**Comment by Sollace** [comment]
I don't think the kind of horses Granny's mask was modelled after were implied to be sapient, lol.

I don't think I'm going to do this one. Seems a little out of scope for what I want the mod to be.
