### ISSUE TITLE
The altar can't work with Quartz Brick，Smooth Quartz Slab or Quartz Slab

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#177]
mod version 1.1.1
game version 1.20.1

Is it meant to be or not?

**Comment by Sollace** [comment]
There is a [tag](https://github.com/Sollace/Unicopia/blob/1.20/src/main/resources/data/unicopia/tags/blocks/crystal_heart_base.json) for the blocks that work. Slabs are not really meant to be used with it, no. I don't know about quartz brick though if that was an oversight or it just didn't exist yet when I implemented this.
