### ISSUE TITLE
Altered Changeling Flight System

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#179]
To make changeling flight feel more bug-like, I believe the flapping mechanic should be completely disabled for changelings, as bugs are constantly flapping. Instead, the ascension while using space should be a little bit quicker, and either slow descent over time or disable it for changelings as well (as we have seen changelings hover in place in the show, as many bugs can do irl). However, at lower levels, taking off from the ground is a lot more awkward and perhaps takes more than one attempt (as we've seen bugs like beetles have little moments like this) and they could also perhaps have more trouble fighting the wind/are more affected by it than pegasi would at certain levels.

**Comment by PoneyClairDeLune** [comment]
Discovered this issue. Is removing the double-space to enter flight mode intentional with this change?
