### ISSUE TITLE
Mod Causes Crash Upon Loading a World

### ISSUE THREAD

**Issue by NXTerminator** [Sollace/Unicopia#18]
As the world loading screen gets to "Loading Terrain," it crashes and reports an error of "java.lang.NoClassDefFoundError: com/minelittlepony/pony/data/PonyRace" (full crash report at bottom).
The mods I have installed are (along with the latest 1.12.2 MC version of forge):
![image](https://user-images.githubusercontent.com/56183249/66857984-06ad0280-ef4e-11e9-8f52-57ce69472912.png)
For the record, the 1.12.2 folder is empty. If this makes any difference, am currently using a separate directory than the appdata/.minecraft/mods one to test this mod before attempting to pair it with others, since I have other mods in use in the main appdata/.minecraft/mods directory, using the vanilla launcher's "Installations" feature. I pre-tested Liteloader and Mine Little Pony mods before adding this in to make sure I set up the new directory location correctly, and those mods work as intended on their own. The world loads up fine, and I am indeed a pony when I load in. When I add in Unicopia and create a new world, that's when the problem occurs. The game seems to load up fine, as I mentioned, but then it crashes upon loading a new or existing world.
Here is the crash report:
[crash-2019-10-07_12.32.34-client.txt](https://github.com/Sollace/Unicopia/files/3730879/crash-2019-10-07_12.32.34-client.txt)

**Comment by Sollace** [comment]
It's probably not compatible with the version of Mine Little Pony you have there.

I fact I have no idea what version of mine little pony you're using there, we don't use that naming schema at all.

**Comment by Sollace** [comment]
@NXTerminator Please send your mine little pony litemod file so I can have a look at it.

**Comment by NXTerminator** [comment]
I think you were right, it seems to work, I thought I pulled it off the official website but I think I got a bad Mine Little Pony file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NXTerminator** [comment]
I can’t even seem to find where I got the bad file, but I must’ve been redirected to unsavory/bad internet places so that’s a bit unsettling. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NXTerminator** [comment]
I guess whatever I got wasn’t official and perhaps was some sort of malware look alike... thank you for pointing that out

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NXTerminator** [comment]
Probably wouldn’t hurt to check my computer now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NXTerminator** [comment]
Internet can be a scary place

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NXTerminator** [comment]
I’m pretty certain now I ended up with one of those look alike malware copies of MineLP because I didn’t navigate the page properly, clicked something suspicious, and didn’t realize it since I’m used to curseforge.

In any case thank you so much for pointing that out, and than you for all your help and patience. Unicopia world gen seems to be working ok at a glance, and the items are showing up in creative mode

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sollace** [comment]
Great to hear you got it sorted!

For future reference, the only sources for MineLP you can trust are https://minelittlepony-mod.com/ or the project here on github.
