### ISSUE TITLE
The crystal podium won't need the corner 8 blocks.

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#183]
![2023-09-07_00 06 26_副本](https://github.com/Sollace/Unicopia/assets/131762804/78cb522f-0f2c-41dc-9ffd-7a1a3a066024)
 
![image](https://github.com/Sollace/Unicopia/assets/131762804/9dd18ca6-a0cc-4d4d-b868-3cb24498a7d5)

The spell book didn't mention that you can use quartz blocks to replace diamond blocks and crystal podium can function without the corner blocks.

Is that meant to be?

**Comment by Sollace** [comment]
This is intended, yes.
