### ISSUE TITLE
（Sep 13 Updated）Hot air ballon design

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#186]
1.Strom king
![IMG_2632](https://github.com/Sollace/Unicopia/assets/131762804/0d411eaf-13bf-4361-8324-00f8d4ea879a)

2.Equality
![IMG_2633](https://github.com/Sollace/Unicopia/assets/131762804/ffa69610-40ff-42c2-b58b-d4c3db9f5d81)

3.Fimtale（changed on Sep 13）
![IMG_2639](https://github.com/Sollace/Unicopia/assets/131762804/94f02590-096b-4ea9-a53e-2b2690dc18d8)

4.Dawn
![IMG_2638](https://github.com/Sollace/Unicopia/assets/131762804/3817b008-d1e8-4572-8b82-79dd7c34b5de)

**Comment by PrinceDrowsy** [comment]
awesome designs dude!!!

**Comment by Sollace** [comment]
Oh wow, every time I come back this gets better. I promise I'll add these soon as I can

**Comment by Sollace** [comment]
Added, thank you! You're welcome to add any more you come up with as comments below this one up until I release 1.2.0
