### ISSUE TITLE
/race set alicorn won't work in adventure, survival and spectator mode

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#189]
With：“Selected Race is not permitted by your current server”

**Comment by xyzzy121** [comment]
Alicorn mode was meant to be a debug race, to facilitate testing of the mod. According to Sollace though, it is planned to be implemented naturally.

**Comment by Sollace** [comment]
Alicorn race is creative-only. Attempting to set yourself to it will fail.

In survival (1.2.0+) there is a way to getting the magic abilities of an alicorn by defeating sombra and repairing the alicorn amulet (to create the unicorn amulet) so both aspects mentioned above are complete.
