### ISSUE TITLE
[Air-ballon] Warden will attack air-ballon/Wrong texture

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#195]
![2023-09-19_16 11 27](https://github.com/Sollace/Unicopia/assets/131762804/92cba42e-0465-456c-8174-1ec9091ef44d)

Unicopia 1.2.0

And also:
![图像2023-9-19 16 04](https://github.com/Sollace/Unicopia/assets/131762804/fdc020a1-24e9-4fad-9bcd-b4437b9805fa)

It should be ''FT''.
<img width="50" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/c14e91a1-4661-47f2-8215-cd1823690cd4">

<img width="531" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/52157ac8-22a1-4e5f-9713-0989f855b70e">

<img width="85" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/099ec7d0-64da-4654-9160-6617acedaa10">

 I guess both of them are up side down, may need some manual adjustment.
<img width="249" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/529a9f80-52ea-4767-841d-b2502276d0e9">
Then it seems that the ropes for the burner were separated from the textures I sent. They are green.

**Comment by Sollace** [comment]
They are oriented the way it was given to me.

I did remove some of the ropes as I didn't feel they fit with the intended look of the balloon.

**Comment by Sollace** [comment]
Closing as the warden behaviour is intended. The balloon emits vibrations when you interact with it, so it will
