### ISSUE TITLE
Can send object to renamed mob using Dragon breath scroll

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#197]
![2023-09-20_23 04 31](https://github.com/Sollace/Unicopia/assets/131762804/be8628ef-b9cb-4755-83fb-9f970242a774)

**Comment by Cryghast** [comment]
Wait, if a player have a same name with a mob(in server), will the object goes to the player?

**Comment by Sollace** [comment]
> Wait, if a player have a same name with a mob(in server), will the object goes to the player?

Depends which ticks first, really. It could be either.

**Comment by Sollace** [comment]
The advancement for sending to Princess Celestia requires there to be no entities or players online with that name, by the way.
