### ISSUE TITLE
Alicorn Amulet Untextured (And how do I change races)

### ISSUE THREAD

**Issue by Orymizu** [Sollace/Unicopia#20]
When I put the amulet on, it was untextured and I'm not sure why. Everything else seems to work fine.

I was also wondering what button allows one to change their race, since my skin is King Sombra with a working horn, but on the side it shows a hoof and plants, which I'm pretty sure means I'm an earth pony.

**Comment by Sollace** [comment]
Use the `/race` command to switch in-game. Next version is going to include a way to select one before creating a world.

I'm aware of the broken texture with the alicorn amulet.

**Comment by Orymizu** [comment]
Alright, ty!

**Comment by Orymizu** [comment]
I'm still a bit lost when using the race command, as when I type unicorn and such it doesn't work. Am I doing something wrong?

Edit: After messing with the command a ton, I figured it out. Is there a guide or wiki to the mod where I could also view other info, since there isn't too much here.

**Comment by Sollace** [comment]
There isn't, no. The mod is still a work in progress, so a lot is due to change. Your best bet is to look a the release notes or ask in the MineLittlePony discord server.

**Comment by Orymizu** [comment]
Ah ok, that's what I was doing at first. Thank you so much and sorry for the trouble, excited for what's coming next.
