### ISSUE TITLE
Dash Ability for Earth Ponies

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#208]
It'd be really cool if Earth Ponies could activate an additional speed boost to their sprint at the cost of their hunger draining faster while using it! It'd give earth ponies a way to maybe keep up a bit more easily with their friends in the sky and those that can teleport, and we've witnessed earth ponies in the show being quite fast on foot as well.

**Comment by Sollace** [comment]
Earth Ponies already have this ability.
