### ISSUE TITLE
zap apple trees leaves not behaving correctly.(?)

### ISSUE THREAD

**Issue by probablyspaceitself** [Sollace/Unicopia#218]
while in creative and flying around i noticed that the naturally spawned zap apple trees had no leaves (see attached image) and when i went to grow one from a zapling(?), the foliage broke the minute the tree grew up. further more, when i tried to place the zap apple leaves manually, it makes the placement sound but the leaves aren't there. 

![2023-11-25_14 33 50](https://github.com/Sollace/Unicopia/assets/152031261/352ce88f-3105-4b34-81ac-8a548515e9e0)

-edit: fixed it somehow. sorry i bugged you.

**Comment by Sollace** [comment]
The leaves follow a seasonal cycle where they will appear and dissapear. I'll make a note that manually placed ones probably should not.
