### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by TackieGlue** [Sollace/Unicopia#220]
![Screenshot 2023-11-28 000315](https://github.com/Sollace/Unicopia/assets/152247463/49707ae5-5b37-4771-a07f-0f05a88f3d5f)

I added the mod to my server files but this still keeps happening when I try to join.

**Comment by MimzyFang** [comment]
What version do you use of Minecraft and of the mod

And a log from the server and the client would be nice ^^

**Comment by TackieGlue** [comment]
I am using 1.20.2 for both

**Comment by TackieGlue** [comment]
I don't know what I did but I fixed it. Sorry for the trouble
