### ISSUE TITLE
Magic = Redstone Signal

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#228]
We often see unicorns power machinery with idle magic, and [Lauren Faust herself has suggested](http://www.equestriadaily.com/2011/09/exclusive-season-1-retrospective.html) appliances and vehicles on the show are imbued with unicorn magic, so it'd be very interesting to see spells give off redstone signals when cast! Specifically spells that have an area of effect, or have been more directly cast on redstone machinery. I could also see a designated spell for activating redstone on top of the suggestions above. I think this could lead to some very fun new redstone usage!

![image](https://github.com/Sollace/Unicopia/assets/75338505/f087a9e5-51b8-47cb-b62d-d580bd73aa1b)

**Comment by Sollace** [comment]
I kind of did originally have some interactions between redstone and magic. The fire gems I think currently still can power redstone dust if you use it on them, but I had to drop the idea because powering redstone is tricky due to how the game works.
