### ISSUE TITLE
Can't start a server with mod.

### ISSUE THREAD

**Issue by kerplamp** [Sollace/Unicopia#23]
I have tried hosting a server on 1.16.4 and 1.16.2 and both have crashed with similar errors.

Singleplayer works just fine though.

Error: https://pastebin.com/Esw4MvKS

My friends and I think this mod is awesome and any sort of fix would be great.

**Comment by kerplamp** [comment]
After a lot of digging I found a [mod](https://www.curseforge.com/minecraft/mc-mods/mcpnp) that gets around the issue by not requiring you to use a server.

Can't use hamachi because my friend's hamachi is busted for some reason.

Closing issue.

**Comment by Sollace** [comment]
Reopening this so I remember to check for it.
