### ISSUE TITLE
Add Alicorn Metamorphosis potion effect as a debug effect

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#236]
We now do have Metamorphosis potion effects for races like earth pony, unicorn and so on, but we don't have Alicorn's effect. It should be added, whether it is for debug or for something else purpose.

**Comment by Sollace** [comment]
Sorry what is this requesting?

**Comment by MimzyFang** [comment]
I think they want a potion effect that is unobtainable in survival without cheats that will rebirth the affected player into an Alicorn

**Comment by Sollace** [comment]
Hm. Well I didn't intend to add a potion for that. I'll have to think about it. I might instead make a simple metamorphosis potion that lets you pick.
