### ISSUE TITLE
Pegasi can pick up multiple entities.

### ISSUE THREAD

**Issue by kerplamp** [Sollace/Unicopia#25]
My friend picked up our entire sheep farm, lol

**Comment by Sollace** [comment]
Bug? Or feature? 🤔

**Comment by kerplamp** [comment]
Pick up army of snow golems, auto turret.

**Comment by kerplamp** [comment]
woah, pick up like 20 iron golems and just be the unstoppable force. OH! keeping an ocelot on your head to be immune to creepers!
