### ISSUE TITLE
Mobs such as Zombies can't wear any amulets when Trinkets are installed

### ISSUE THREAD

**Issue by 256smash** [Sollace/Unicopia#258]
Hello, I would like to offer you a fix for the mod. When Trinkets was installed, I could no longer put modified items on them, such as the Alicorn Amulet or Sunglasses. And when I disabled the Trinkets mod, it would crash because Unicopia required the mod, even though it said it was optional. It wouldn't be a bad idea to experiment on any zombies, skeletons or pillagers - give them powers with an amulet or decorate them. I also tried putting amulets on them using the "In-Game NBTEdit Reborn" mod by entering codes inside the mobs, but it didn't work (it just drops the item from the mob).
Minor: I use in my mod-pack a lot of mods more than 160. 
**Game Version**: 1.20.1,
**Fabric version**: 0.15.3

This is my only request that can solve this problem! Thank you for your attention!

**Comment by Sollace** [comment]
I suggest updating the mod if you haven't already.

https://github.com/Sollace/Unicopia/releases/tag/1.2.2%2B1.20.1

**Comment by 256smash** [comment]
Problem solved! I just tried to run the mod without Trinkets again, maybe I fixed the error with configs. Although mod version 1.2.2 was present in my game. Thanks for helping out a little! :D
