### ISSUE TITLE
New abilities and stability of Grogar's bell

### ISSUE THREAD

**Issue by 256smash** [Sollace/Unicopia#259]
As we see that whoever uses the bell gets the power of chaos from it. We see Pinkie Pie and Cozy Glow being possessed by the powers from a bell, becoming huge and able to create anything they imagine. It would be great to give chaos powers for any mobs or yourself, and my idea is to get more power to turn for example a zombie (and not only) into a huge chaos entity or quickly teleport with a yellow magic portal to the right place as shown in the cartoon. To do this, you need to toggle the desired ability in which the individual interface of Grogar's bell will be shown with other keys. I have so many great ideas in mind to be honest, but it's worth it. I will always be kind enough to suggest the best idea imaginable. :)

![Shadows_of_the_all-powerful_Legion_S9E24](https://github.com/Sollace/Unicopia/assets/56295558/da272260-2029-4d40-be59-538d57112f41)
![1](https://github.com/Sollace/Unicopia/assets/56295558/6666cb71-4c74-42a1-9151-d4133a6f4e32)
![2](https://github.com/Sollace/Unicopia/assets/56295558/0311279c-3402-4d85-ac97-60bfbcfe07c0)

**Comment by Sollace** [comment]
This isn't intrinsic to the bell. This is because they used it to steal Discord's chaos magic. I might do something like this in the future, but for the time being I have no plans to make further changes to the bell beyond what it does at the moment.
