### ISSUE TITLE
Crash: Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by kerplamp** [Sollace/Unicopia#26]
[Crashlog](https://pastebin.com/fzff23cz)
_**Note: Crashing only seems to happen on worlds that aren't superflat or some variation of superflat. I didn't notice until now because I've mainly been testing on superflat.**_

 Game crashed because of [0bde55a](https://github.com/Sollace/Unicopia/commit/8e89edfb355e30bd8e9ca7b0433ef17d37dee206). Specifically line 64 (71 when I open it in notepad++) of [BlockDestructionManager.java](https://github.com/Sollace/Unicopia/blob/8e89edfb355e30bd8e9ca7b0433ef17d37dee206/src/main/java/com/minelittlepony/unicopia/BlockDestructionManager.java#L59) (Or at least that's what I think the issue is). 

Found a way to make my game not crash by making it so that if the size of the, uh, "Long2ObjectOpenHashMap" is above 1000 it clears it. The only affects on the block breaking rendering I've seen is a slight delay in rendering damage. Also after some more testing after posting this, I've noticed after loading a bunch of new chunks there are some tps issues. Pretty sure there's a better solution but this is what worked for me.

				if (sent.size() > 1000) 
				{sent.clear();}
                if (!sent.isEmpty()) {
                    Channel.SERVER_BLOCK_DESTRUCTION.send(world, new MsgBlockDestruction(sent));

Also the shield works great! I really like how you can keep 1 mob at bay with a small enough drain that you can almost regen it, but more than 1 starts to drain it faster than you can regen. 
It lets unicorns use their shield casually but are punished for sticking around an area with too many mobs for too long.

**Comment by Sollace** [comment]
Do you have some way I can recreate that error with the payload size? I
imagine you must have had a lot of blocks rendering destruction effects.

**Comment by kerplamp** [comment]
It happens whenever I try to create/play a default world in singleplayer. Superflat worlds don't seem to have the issue though. 

Just create a new default minecraft world, no options changed. That's what I'm doing to get the crash.

Note that the crash is somewhat delayed sometimes so you may have to wait a little bit.

**Comment by Sollace** [comment]
Do you restart the game before trying to load another world? I'm able to
play just fine and the map shouldn't have any significant amount of data in
it when just startibg out.

**Comment by kerplamp** [comment]
I'm not quite sure what you mean by restarting. I can't make a new world and then restart, the world immediately opens upon creation. And I can't restart minecraft after crash because it crashed. 
I'm attaching a video showing what happens from starting minecraft, to loading a new world.
_I turned my render distance down to 3 to see if it was a problem with render distance._

Video: https://www.youtube.com/watch?v=L6mA5FAe5Qc

I'm using the version from the newest release, not compiling code.

**Comment by kerplamp** [comment]
Newest update looks like it fixed it, I can load into normal worlds perfectly!
