### ISSUE TITLE
Friendship is (a) Mechanic - Pony Entities

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#262]
I would put this in my mobs list suggestion, but since this features a special kind of system of its own, I decided to make it a post of its own. I envision implementation of this being step-by-step, not an immediate implementation of everything I've listed, so I ask that you consider the concept with that in mind. I get that this is quite an overwhelming suggestion of things, haha.

### Ponies [Mob]

- Ponies are a replacement mob that spawn in place of the default villagers.
- Their appearances are generated using a randomized combination of base skin texture for their species, eye shape texture, hair texture, tail length, and a randomized hex code color for each of the above. Potentially some additional code to make the selection of complementary colors more likely, and have the hair and tail color be the same the majority of the time with a very small chance/rarity for them to generate with a separate color tail and mane.
- Config option to make them immune to fall damage? (or at least smart enough to avoid like... idk four block or higher drops? my villager death message mod tells me dumb falls like that cause 99% of villager deaths)
- They come with randomly generated names, which works by deciding whether they are a single word name (ex: rarity, octavia) or a two word name (ex: twilight sparkle, rainbow dash), and then the number of names decided on is picked from one or two text files of pony name prefixes and suffixes
- Ponies have the potential to spawn with canon names, which will assign them the appropriate matching texture.
- When interacting with them, you get a new menu with a trade button that opens the default villager trading tab, and a few new buttons that will be elaborated on further in the Friendship section below.
- They have the default villager professions, along with a few new ones like guard (replaces iron golems), mayor (tells you what ponies live in the village, and what professions they work. they can also tell you which ponies you're friends with. could also inform you of what events are going on and when, if said feature is implemented below), weather pony (can tell you what the weather will be for the next few days, trade cloud jars/other weather related items like snow and whatnot) party pony (can sell you party items like wrapping paper that can boost the affection of gifts and assist with event quests)
- Some of these default professions will also have new pony-related features, like librarians having the potential to trade you spell crafting items, and give tips/hints on how to craft certain spells
- They come in all playable pony types
- However, the types that spawn depend on the village. Most villages will spawn the main three tribes by default, but you can find kirin villages in jungle and mountain biomes, zebra villages in the savannah (or the dark forest/everfree biome as a reference to the journal of the two sisters), crystal ponies in a crystal village, earth pony villages in the sweet apple acres biome, or pegasus villages in the clouds.

### Friendship [Mechanic]

- You can become friends with ponies!
- Ponies will have an affection meter with you depending on your interactions with them.
- This affection count can slightly spread to other ponies in the village, both positive and negative counts.
- As mentioned above, ponies have a menu that features a Trade button, and a new one titled Interact.
- Clicking Interact will open the Interaction menu, allowing you to Idly Chatter, Ask a Rumor, Offer Help, Ask Help, or Give Gift(s)
- Idle Chatter just lifts your affection with a pony a little, and possibly displays a little flavor text in chat related to their profession and/or species.
- Offer Help allows you to help a pony with a Friendship Quest. Not all ponies will need help with something when you ask them though, so you can instead Ask a Rumor to find out who does need help. More on this explained in Friendship Quests.
- Ask a Rumor will let you know what ponies in the village might need help with something, related to the Offer Help button.
- Ask Help allows you to ask a favor of a pony depending on their job, species, and whether or not you are friends with them. Pegasi can carry you somewhere temporarily, or transmute the weather for you if they're a weather pony, earth ponies can grow a crop for you, or transmute one if they're a farmer, unicorns can cast spells for you, or teach you how to craft a few/level your casting if they're a librarian, a guard pony of any species can help you hunt some mobs, etc.
- If you ask for help from a pony that is not your friend, they probably won't help you. There is a cooldown on this feature, and you will lose affection with a pony if you ask them for favors too often, especially if you do so without chattering with them or helping them in return! They're your friend, not a pony for hire.
- However, you can hire ponies to do certain Ask Help tasks by paying them. This will not affect their affection meter.
- Give Gifts allows you to gift ponies items to increase their affection, and ponies will have randomized favorite items that you can learn through Idly Chatter(ing). Certain species and professions of ponies will have a higher chance of having favorite items related to those things. 
- There is a three per day cooldown on this to prevent gift spamming. A friendship based on monetary value is not a healthy one!

### Friendship Quests [Mechanic]

- You can Offer Help to a pony, and in response, some might give you Friendship Quests.
- Friendship Quests are randomized tasks that you can complete for a raise in affection and/or in return for a reward.
- These tasks can vary from getting an item for a pony, delivering an item from one pony to another, or slaying a mob in the area that's been bothering them. (Mayors potentially give bigger quests like boss fights? Might introduce a Princess profession for city-sized village structures that could give you truly monumental Friendship Quests.)
- Could give ponies assigned "best friends" from other ponies in the village, and you might get a more complicated quest where you help them get through an argument, host a party for one another, or save the other from a dungeon.
- Friendship Quests could also potentially give tasks to naturally introduce parts of Unicopia like spell crafting and boss fights? Kinda like the optional "tutorial shrines" in Legend of Zelda: Breath of the Wild that casually introduce mechanics without outright forcing you or holding your hand.
- Could have difficulty tiers, unemployed ponies giving easy tier, employed ponies giving medium tier, and ponies like guards, princesses, or mayors giving hard tier quests.

### Events [Mechanic]

- Pony Villages will periodically host events.
- Most villages default to all the events listed, but some will have specific events depending on type, or will exclude events for the same reason. A desert village probably isn't going to participate in Winter Wrap-Up, haha.
- Hearts and Hooves Day will decorate the village in pink and hearts, and boost affection for all interactions while it's in progress.
- Nightmare Night will decorate the village in jack-o-lanterns and the villages will adorn costumes, you can gift candy and treats for additional affection while this is in progress.
- Hearth's Warming will decorate the village in snow and lights, and remove the gift cooldown while it's in progress.
- Winter Wrap-Up will have the ponies cleaning up the snow from Hearth's Warming, and there will be additional Friendship Quests related to the event (clearing a certain amount of snow, planting seeds, gathering certain passive mobs) while it's in progress.
- Potentially assign ponies birthdays that they will receive additional affection from gifts during.

### Additional Structures

- Weather Factory for Weather Ponies to spawn in
- Orchard + Barn
- Town Hall for Mayors to spawn in
- Twilight-style Library for Librarians to spawn in
- Guard Barracks for Guards to spawn in
- Castle for Princesses to spawn in
- School House for a potential Teacher profession? Foals gather here during the majority of the day before heading home just early enough to avoid night fall

**Comment by PrinceDrowsy** [comment]
Princesses could replace/function as a variant of Mayors for larger villages/city type villages, with additional princess-specific mechanics of doling out bigger friendship quests like defeating bosses, making a certain amount of friends, gathering rarer items and artifacts

**Comment by PrinceDrowsy** [comment]
Option for a Wandering variant of the Party Pony profession (referencing Cheese Sandwich)

**Comment by PrinceDrowsy** [comment]
Potential for a Wonderbolt variant of the Guard profession (referencing their additional purpose in the series as an air force)

**Comment by PrinceDrowsy** [comment]
Foals potentially display a higher rate of needing help with Friendship Quests

**Comment by Sollace** [comment]
Interesting idea, but this sounds like it would be more suited to a standalone mod.

**Comment by PrinceDrowsy** [comment]
> Interesting idea, but this sounds like it would be more suited to a standalone mod.

Do you think at least a few of these ideas are worth utilizing though? Like the unique villages
