### ISSUE TITLE
Crafting recipes clashing relating to cloud items

### ISSUE THREAD

**Issue by Grendster** [Sollace/Unicopia#265]
- Cloud Door and Shaping Bench as of now have the same exact recipe, prioritizing Cloud Door over Shaping Bench.

- I believe Shaping Bench should be 2x2 and door 2x2x3 in the crafting grid for the sake of clarity.

- Pegasus, Earth Pony and Unicorn have attempted to craft it, should that be a necessary information.

Screenshot attached below with the issue.
![2024-02-18_20 51 41](https://github.com/Sollace/Unicopia/assets/160424641/b93a6006-4bc6-45ff-83b7-e9263e81847c)

**Comment by MimzyFang** [comment]
Okay this looks like a bug 

Will check it out today evening

Until it's fixed try using https://modrinth.com/mod/polymorph as a workaround

**Comment by Sollace** [comment]
Ah yeah this is a bug. The door is meant to be 2x3 not 2x2
