### ISSUE TITLE
First-person arm display when I transform into a mob with a spell

### ISSUE THREAD

**Issue by 256smash** [Sollace/Unicopia#266]
When I'm in mob guise (such as a zombie villager), I'm not very used to playing without an arm that is only displayed to the humanoid player. I would like to suggest a usual improvement to have the player turned into a mob (such as a zombie, skeleton or pillager) show the arm of any entity when every player who plays as a changeling or who uses a stone for a spell, like in the "Identity" mod. This would be great for both human and ponified mobs. :)

**Comment by Sollace** [comment]
This is already implemented in the latest release (perhaps I forgot to document it)

**Comment by 256smash** [comment]
Now I understand. I will research other issues very carefully. Thanks for the heads up on this!
