### ISSUE TITLE
Potion and Effect: Cloud Tangibility

### ISSUE THREAD

**Issue by 256smash** [Sollace/Unicopia#269]
I came up with one more idea that might be good for survival. Players who are playing as pony races except pegasus could use an uncommon potion to walk on clouds. Also, this effect could be applied to mobs such as villagers and others (although the effect can end in villagers that can still fall). Other option: To mobs can add a NBT tag. Roughly it could be: `{cloud_tangibility:BYTE}` (to use this tag, need to use a new rare item or new spell, I think so.) It would be creative and cool if one ponified villager could live as a real pegasus since some appear with wings depending on the base texture. (☆▽☆)

**Comment by Sollace** [comment]
You can already do this with feather walking boots

**Comment by 256smash** [comment]
I'll try to do as your said. Thanks again for the advice!
