### ISSUE TITLE
Question / Tweaks / Ideas

### ISSUE THREAD

**Issue by kerplamp** [Sollace/Unicopia#27]
**Question**
Usually when the code gets updated, I'll download it and change a few little things before compiling it and using it. But I can't seem to compile the code anymore because of the canvas addition. I think I need to compile the stuff in canvas-compat but I'm really inexperienced with compiling. I spent a whole day googling stuff about canvas and even tried just downloading canvas code from their github and compiling that in the canvas-compat folder. If its not too much trouble a link to some sorta like website that explains or anything would be awesome. If there isn't, I can just wait for the next release.

**Tweaks**
The small tweaks I usually make are reducing the earthpony stomp downward velocity from -6 to -2 because if you use the stomp ability on a slime block/bed you get sent to the moon. I also make it so that pegasus flight only happens when you press shift mid air instead of sprint jumping so that pegasus can sprint jump run (this is useful during storms). It also eases flight in cramped areas. 

**Ideas**
Note: These suggestions are under the idea that all races should all be capable in combat but in different ways, e.g. pegasi can choose their fights and are good at ranged attacks, unicorns are more adaptable and can change spells to fit their needs and earth ponies are straight dps and rush down enemies.

Ground pound rework: Most enemies can be instantly killed with a stone axe and ground pound. This alone isn't too bad but ground pound has an area of effect and a fairly large one at that (mobs that are ~3 blocks away or less instantly die with stone axe + ground pound). I think that having ground pound do less damage but instead inflict slowness and maybe pop enemies up into the air more than throw them away would make earth pony more "diverse?". That or some other change to damage scaling or more damage dropoff at range.

Pegasi damage scaling: This one I'm not to sure about because I have no idea how to code it so I haven't tested it but I had the idea to make pegasus damage scale based on their speed. 

Pegasus bow affinity: Arrows can be knocked faster and fly a little bit faster. (Also arrows are kind of messed up when you shoot while flying, they shoot at a slight downward angle.) My only concern with this would be that encounters between earth ponies and pegasi would probably just be 1 sided given the pegasus has enough arrows. Unicorn vs pegasus would probably end up with the unicorn putting up a shield and then using vortex to slap the pegasus into a wall or the ground but that's what the heavy enchant was for. That or the pegasus would use a rainboom to damage the unicorn.

Earth pony lasso: This should actually fix the pegasus vs earthpony scenario above. It's a short ranged projectile that once it hits an entity, it puts a lead on it. It could be the Shift + R ability for earthponies. It could be disconnected when the thrower takes damage so that you can't just hold onto an enemy forever. Or it could just break if the enemy pulls hard enough like normal leads.

I'm trying to come up with a bunch of ideas for unicorns because most of my suggestions have been for earthponies and pegasi but other than suggesting spells I can't really think of anything and I haven't had that many ideas for spells. I'll probably take some time to go through all the unicorn spells and see what they do so I can get a better idea of what the spell average power and utility is.

Lastly its really cool to see stuff I suggest make it into this mod! I hope that I'm helping and not just sorta dropping stuff on you. I'll usually spend hours on a message making sure that what I suggest seems possible and testing in game. I've made small mods for Garry's Mod so I have a little bit of experience in game modding, though I did use visual block based scripting. It's actually really cool and I recommend checking it out if you do play Gmod, it's an addon called Blueprints. Anyway, this is probably the best mod I've used in minecraft and I wish you good luck! It seems like every day you crank out some huge update to the mod! It's incredible!

**Comment by Sollace** [comment]
Response to your question:
It should just work if you've set it up correctly.

1. Clone the repo `git clone https://github.com/Sollace/Unicopia.git`
2. `cd Unicopia`
3. To edit/debug do `gradlew genSources eclipse` (or import the project into Idea)
4. To produce a jar do `gradlew build`

If you're having problems with canvas-compat not being present, just do `gradlew :canvas-compat:build` to produce the jars for that then you can rerun one of the above commands.

**Comment by kerplamp** [comment]
Sorry for posting after it got closed. Issue got closed while I was typing.

_I should probably mention that everytime I build unicopia I change the distribution url in gradle-wrapper.properties to version 6.3 because otherwise I get this error: `Could not initialize class org.codehaus.groovy.reflection.ReflectionCache`._

I used `git clone https://github.com/Sollace/Unicopia.git` and `cd Unicopia` but when I ran `gradlew :canvas-compat:build` it still gave me the error that it could not find the canvas-compat dev jar. However I was able to run `gradlew :canvas-compat:build` when I deleted the part in build.gradle that talks about canvas-compat. I think it was trying to use the canvas jars before it created them.

Once I got the canvas dev jar I replaced the part I deleted in build.gradle, kept the now built canvas jars in canvas-compat and ran `gradlew build`. 

Now I get the error

    >Task :compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
     >Could not resolve all dependencies for configuration ':compileClasspath'.
        >org.apache.logging.log4j:log4j-api:2.8.1 has more than one client module definitions.
    
This is probably because the janky way I got the canvas jars but I have no clue how to get them any other way.

Is there a specific program I should be using? I downloaded the GIT command line thing and used that for `git clone https://github.com/Sollace/Unicopia.git`

**Comment by Sollace** [comment]
> Tweaks

The moon jump was a bug. Should be fixed now, thanks! As for other changes... Eh, I don't know.

> Earth pony lasso

I'm not actually a fan of this as an ability. If implemented, it would probably require a special item, as it doesn't really make much sense for earth ponies to produce rope out of thin air.

> Pegasi damage scaling + Projectiles stuff

The idea is simple, but I don't think it will be particularly easy to implement, so the answer is "no" for now.

> I'm trying to come up with a bunch of ideas for unicorns

You don't have to worry about that! I have plans for what I want to do with unicorns.

**Comment by Sollace** [comment]
> This is probably because the janky way I got the canvas jars but I have no clue how to get them any other way.

Gradle is supposed to download dependencies automatically. Did you try `gradlew --refresh-dependencies`?

**Comment by Sollace** [comment]
Also please don't edit the gradle wrapper manually. You're likely to break other things that way.

**Comment by kerplamp** [comment]
I had already tried `gradlew build --refresh-dependencies` from when I was googling and just tried `gradlew --refresh-dependencies` and got what I think is the same error

    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring root project 'Unicopia'.
     > java.nio.file.NoSuchFileException: C:\Users\kerp\Desktop\unicopia changes\Unicopia\.gradle\loom-c 
    ache\remapped_mods\fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_4.1.16.4+build.6.jar

Also sorry for all the questions, I've never done anything with github and building before so a lot of this is new to me.

I tried this on the version I messed with, I'll try it on a clean clone right now. 

Still got an error. I'll just wait for releases, this gradle stuff is beyond me.

**Comment by Sollace** [comment]
@kerplamp 
Seems like something weird with gradle. This worked for me to re-generate the canvas-compat libaries after deleting them:

`gradlew :canvas-compat:build` should now work with the most recent commit. It will dump a big error, but it will still succeed and you'll have the canvas-compat-dev jar after that for building the main project with.

You shouldn't worry about canvas and all of that. Gradle will fetch them for you when it configures the project.
