### ISSUE TITLE
Using leaves as food

### ISSUE THREAD

**Issue by Grendster** [Sollace/Unicopia#270]
I don't mind eating them as my food source... if it was a bit more balanced per say on its nutritional value vs how easy it is to get.. at least perhaps in the early game?

I compared it to some other foods and... well, I think as of now they seem to be a **_bit_** too good.
Not just cherry leaves, other trees' leaves are affected too.. at least the vanilla trees.

![2024-02-19_18 58 43](https://github.com/Sollace/Unicopia/assets/160424641/18c7defc-8d4d-4030-971f-6d6a0d58b27c)
![2024-02-19_18 59 43](https://github.com/Sollace/Unicopia/assets/160424641/561b7312-4afe-46f8-9d7a-35d170236a9e)
![2024-02-19_19 00 10](https://github.com/Sollace/Unicopia/assets/160424641/aaac808a-6956-4d41-bdad-aa086b5bda06)
![2024-02-19_19 00 23](https://github.com/Sollace/Unicopia/assets/160424641/82394cda-851c-4ce0-900f-a2ea67d6cb50)

**Comment by Grendster** [comment]
I thought to add these here just as ''after-wisdom'' as I think they might be relatable.

Might have something to do with the recent change to hay bales and straw bales as placable edibles, but you can just eat them straight up without placing them.

![2024-02-19_19 10 20](https://github.com/Sollace/Unicopia/assets/160424641/65906413-098b-4bf8-a7ba-969d6fa26e63)
![2024-02-19_19 10 05](https://github.com/Sollace/Unicopia/assets/160424641/90253f11-1ea2-4886-a3c0-a0a3b9b05165)

**Comment by Sollace** [comment]
Leaves are not meant to feed you as much as hay bales - that was an oversight on my part. I had thought to change it during the betas but it slipped my mind.
