### ISSUE TITLE
Plunder Vine crashes world/server.

### ISSUE THREAD

**Issue by Grendster** [Sollace/Unicopia#271]
This is a critical bug/crash issue that needs hotfixing. It essentially crashes your single player world and prevents server from rebooting after it occurs.

What to do (to replicate it safely):
1. Go to Single Player
2. Choose Earth Pony
3. For sake of simplicity, make 5x5 sunflower area
4. Use the bonemeal ability on the middle sunflower
---
- Eventually a plunder vine will appear and that won't crash anything and you can remove it safely. However after second or third appearance, it will crash the game completely.
- That being said, before crashing, there was a split second moment before the crash when at least I was able to see (and some others in the testing of single player) the Plunder Vine's spot of growth wasn't only Plunder Vine. It also resembled the other new plants to be mixed on the very same spot (like the Poison cure).
- If I can help with any files or such, I will respond to the post after with the requested information(s).

**Comment by Grendster** [comment]
![bugcrop](https://github.com/Sollace/Unicopia/assets/160424641/0ea6c3dc-30ca-4c15-b3dc-348822576f7f)

This is how the mixed plant looked like.

**Comment by Fauli1221** [comment]
this might be a related crash
https://mclo.gs/oVHk7mC

**Comment by MimzyFang** [comment]
this might be related https://mclo.gs/M23wFuG

**Comment by MimzyFang** [comment]
@Grendster can you test if this mod fixes it https://modrinth.com/mod/neruina

though back up your world as it will delete entities that are broken

**Comment by Grendster** [comment]
![2024-02-20_22 25 52](https://github.com/Sollace/Unicopia/assets/160424641/55663ad0-160c-4998-a4cb-c2a9be1f23ee)
![2024-02-20_22 31 37](https://github.com/Sollace/Unicopia/assets/160424641/2483bd59-d221-4d00-b216-755b63705789)
![2024-02-20_22 29 25](https://github.com/Sollace/Unicopia/assets/160424641/57b0fb31-0433-490b-b3d6-dbdeec250898)



- I can confirm now with the mod that it fixes it. Sometimes the Plunder Vine appears correctly and sometimes it kills.. Ignominious Bulb from appearing. Also occasionally deletes a sunflower from the existence in testing.
- I would say it works adequately and is fixed with this mod at least on single player. I'd expect this to also work on multiplayer server but if any problems occur, I will be back to this.

**Comment by MimzyFang** [comment]
@Grendster the bug will be fixed in the next release

And I can tell you it also works on servers so if you ever encounter a crash that has something about ticking in it's crash log add that mod as a bandage fix
