### ISSUE TITLE
Bat Pony Cling Animation/Pose Suggestion

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#276]
It'd be nice when using the "Cling to Ceiling" skill to have the player model (with Mine Little Pony) to appear as though they're dangling by their hind legs, with their forelegs clutching each other at the hoof (think someone politely clasping their hands together in front of themselves) and their wings wrapped around their upper body in the front.

**Comment by Sollace** [comment]
This is kind of like the pose vampires hold when they're dangling. It's something I already thought of doing but couldn't ever think of a way to make it work with the current models, so, while a nice idea, it's bot really something I can do.
