### ISSUE TITLE
Rain or Snow in Any Biome - Pegasus Suggestion

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#277]
It would be nice if there was a separate weather/cloud jar for snow, and that pegasi could make it either rain or snow no matter the biome.

**Comment by MimzyFang** [comment]
This sounds nice on paper but with snow would be a mess to clean up

**Comment by PrinceDrowsy** [comment]
> This sounds nice on paper but with snow would be a mess to clean up

I imagine snow only falls in non-naturally-snowing biomes if you use one of the weather jars to prevent clean-up for those who don't want it. My own server hosts Winter Wrap-Up and whatnot, so we'd make great use of this, both the snowfall and cleaning it up later on.
