### ISSUE TITLE
Cancel the portal via panel will cause the game crash

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#278]
<img width="736" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/f6129431-6d94-48d0-9ea5-fb902ad708df">
If you try to reload the save it will say:
<img width="467" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/0c178719-b79b-48d2-8598-77a0bd804db4">

Minecraft 1.20.1 Unicopia 1.3.0
[crash-2024-02-25_16.38.45-server.txt](https://github.com/Sollace/Unicopia/files/14395753/crash-2024-02-25_16.38.45-server.txt)

**Comment by MimzyFang** [comment]
This sounds like a bug that was fixed in 1.3.1

**Comment by MimzyFang** [comment]
Please update

**Comment by MimzyFang** [comment]
Will close this for now if you can reproduce it in 1.3.2 comment and I will reopen it
