### ISSUE TITLE
Spell cancel panel weird, extra gemstone icon

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#279]
<img width="940" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/c8b88b7d-9d33-47be-9768-ce887eaf9a38">

Unicopia 1.3.2

**Comment by Cryghast** [comment]
I mean, if you drag the mouse to the right-down corner, a gemstone icon will show up and moving towards the opposite direction. Is that intended?

**Comment by Sollace** [comment]
Yes. It's further from the circle than it's meant to be, but the gemstone being there is intended.
