### ISSUE TITLE
Game crash when conventionally using mod.

### ISSUE THREAD

**Issue by kerplamp** [Sollace/Unicopia#28]
EDIT: Apparently a ton of updates came out and I didn't see them, you might have already fixed this.

First off, I got the mod to build :D! I'm using the IDEA thing you mentioned and was able to use the run minecraft client to use the mod. But when I build the jar and then move it to my mods folder, my game crashes before starting with error code 0. 

I saw that <clinit> and <init> in MixinLivingEntity and MixinMobEntity were causing errors and when I the @Injects that use them into comments, I was able to use the mod when it was in my mod folder. But this broke the Want It Need It curse which is sad because it's really funny to throw an enchanted item to a group of mobs and watch them go nuts.

But after a while of looking up stuff and messing with code I came out with what I'm sure is a really hacky solution.

For MixinMobEntity:

    @Inject(method = "tick()V", at = @At("TAIL"), remap = true) // <init>
    private void tick(CallbackInfo info) {
        if (test != 1) {
            ((Creature) get()).initAi(goalSelector, targetSelector);
            test = 1;
        }

    }

Btw if remap is set to false it still crashes. I don't know why. I just tried everything.

For MixinLiving Entity:

    @Override
    public Equine<?> create() {
        Creature c = new Creature((LivingEntity)(Object)this);
        Creature.boostrap();
        //Creature((LivingEntity)(Object)this);
        return c;
        //return new Creature((LivingEntity)(Object)this);
    }

    ---------------------------------------------------------------
    
    //@Inject(method = "<clinit>()V", at = @At("RETURN"), remap = false) //<clinit>()V
    //private static void clinit(CallbackInfo info) {
        //Creature.boostrap();
    //}

This might just be another problem with me building it but thought I'd post it anyway in case it helps with debugging.

**Comment by Sollace** [comment]
Can you post the actual crash log? Things you're commenting out there are likely to break other stuff. :eyes:

**Comment by kerplamp** [comment]
Sorry, forgot. 

https://pastebin.com/AAJPRpDf
