### ISSUE TITLE
Portals weird behavior

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#280]
![未命名作品](https://github.com/Sollace/Unicopia/assets/131762804/9b2112bd-cd64-4219-a6aa-bd7f92576c68)

1. create two portal that linked
2. cancel them
3. create a new pair of portal
4. the new portal will somehow link to the old one(even the old one was canceled)

**Comment by Sollace** [comment]
If you cancel one portal, any new one you make will still link to whatever available portal exists. That is how they're intended to function

**Comment by Cryghast** [comment]
> If you cancel one portal, any new one you make will still link to whatever available portal exists. That is how they're intended to function
Yes but it will connect to non-exists portal

**Comment by MimzyFang** [comment]
A friend of mine observed that behavior as well

**Comment by Sollace** [comment]
Can someone retest this in 1.3.7? I believe it should be fixed but can't confirm.

Spell linking with the ether in that version changed a lot.
