### ISSUE TITLE
support for Open Parties and Claims

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#283]
Open Parties and Claims is a mod to let you claim your area I would like Unicopia to integrate with it so that areas are protected from other people's spells or even block spells and have your own spells still work and maybe some other ideas that would need to be discussed 

https://modrinth.com/mod/open-parties-and-claims

**Comment by Sollace** [comment]
There is already something in unicopia to achieve this. Besides the usual restriction on being able to cast where you can't build, there is also a spell players can cast to prevent others from casting spells in the same area
