### ISSUE TITLE
Item Suggestion - Pony Armor stand

### ISSUE THREAD

**Issue by Grendster** [Sollace/Unicopia#285]
- This is merely but an idea, but as of lately when I've been laying my armor on the armor stands (vanilla), they are.. vanilla.
   for the sake of looking somewhat relevant as the player model is still 1 block, it'd be split in two, where you have helmet and chestplate on the ''front'' half of the armor stand, and leggings and boots on the second/ ''rear'' half of the armor stands.

- This would be all just for vanity and could be separate from vanilla recipe should one wish to still use those.
  For crafting recipe, it'd still use sticks and smooth stone slab, but perhaps in different shapes, aye?

**Comment by Sollace** [comment]
Mine Little Pony already provides this using a name tag. I don't want to duplicate functionality.
