### ISSUE TITLE
Vivecraft Compat

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#292]
I recently got a vr headset and am playing minecraft in vr now and because of that I got the idea if it might be possible to add a bit of compatebility betwen Vivecraft and Unicopia

since I have a vr headset I would defintily help with testing

what would be needed
1. a sort of simulated flight as the flight mechanic is effectively impossible in vr
2. a way to use the abilities and switch go up and down in the ability menu in vr

in case you need an api to intigrate these changes here is a api 
https://modrinth.com/mod/mc-vr-api
https://github.com/hammy275/mc-vr-api

**Comment by Sollace** [comment]
There's no possible way I can do this.
