### ISSUE TITLE
Pegasi & Unicorn Hunger Restoration from Fruits and Vegetables category

### ISSUE THREAD

**Issue by ShuffleBox82** [Sollace/Unicopia#293]
Giving my thoughts on this a bit more formally. I feel that pegasi and unicorns should gain 100% of the standard hunger restoration from food items in the fruits and vegetables category.

As is now, it feels like pegasi and unicorns got stuck between both being allowed and not allowed to eat fruits and vegetables at the same time, and it feels a bit weird/tedious for them to only gain 50%/70% of the standard hunger restoration from those foods. They are shown to be able to eat those kinds of foods perfectly fine in the MLP g4 show. I don't feel that them having foods they can exclusively eat (or at least, just pegasi it seems at the time of writing) warrants the hunger restoration decreases on such a large food category. I feel that simply just letting pegasi have the bonus/perk of being able to additionally being able to eat fish on top of the normal pony diet without making a balance around it worked fine.
In the context of a multiplayer server, this could also be a bit odd for any earth ponies (or any creatures i suppose :p) that enjoy farming and want to be able to do the work to feed others, since pegasi and unicorns no longer get full benefit from any crop except wheat.

It just feels a sort-of-but-not-quite restriction on the diets of pegasi and unicorns that doesn't feel right and discourages bothering with more than just wheat/hay, which is a shame since Unicopia introduces extra food items. If the player/server is running mods such as Farmer's Delight, it's even more disheartening to see hunger restoration penalties on those food items as well, since such mods are supposed to expand the player's options for food items. Only allowing earth ponies to gain full benefit from such a large food category just feels... wrong.

**Comment by Sollace** [comment]
I've made some adjustments and fixed some bugs that were causing other food types to show as fruits and vegetables when they weren't meant to. I hope this will make it feel a little more balanced.
