### ISSUE TITLE
Love enhancement - Suggestion

### ISSUE THREAD

**Issue by SkyArrow76** [Sollace/Unicopia#294]
While playing with this mod and the Create mod, I've been trying to automate everything. However, automating love is the tricky one. Since in order for the feature of love buckets/bottles/mugs to be filled a changeling race character has to throw it. 
I had an idea, since there is already the slime pustules that have some redstone functionality, perhaps if those power a dispenser (or other device where relevant) it is considered changeling activated.

Also, one other thing. A liquid form of love perhaps, for bulk liquid storage of it?

idk, this might just be a very niche thing, so not a high priority idea.

**Comment by Sollace** [comment]
What do you need to collect love for exactly? It's typically there as a food item for changelings so they have alternatives to sucking on cows and sheep.
