### ISSUE TITLE
Slime Pustule Redstone Not Updating Vertical Redstone

### ISSUE THREAD

**Issue by SkyArrow76** [Sollace/Unicopia#295]
Perhaps this is intended behavior and/or I don't use redstone enough, but it appears than when the slime pustule gets a redstone signal, it doesn't power the redstone above unless there's a block update. Same goes for when its powered off, leaving the redstone magically still powered.
![2024-03-03_14 29 10](https://github.com/Sollace/Unicopia/assets/33587750/be3e28ac-2707-4bc8-b3fe-a05052b12fda)
![2024-03-03_14 28 53](https://github.com/Sollace/Unicopia/assets/33587750/80fbf49d-76f1-4485-a978-14d7c4091613)

**Comment by MimzyFang** [comment]
Honestly I wonder if technical players would want that behavior as a feature

**Comment by Sollace** [comment]
When I was testing it I had the pustule hanging from a lamp and it updated that just fine.

Try instead having the pustule hang off the thing you want to power directly (or pit torches on the sides of the block).

**Comment by SkyArrow76** [comment]
> When I was testing it I had the pustule hanging from a lamp and it updated that just fine.
> 
> Try instead having the pustule hang off the thing you want to power directly (or pit torches on the sides of the block).

Ah, that worked
