### ISSUE TITLE
Don't change player to Seapony skin when the player did not activate the ability 

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#296]
Right now if you have the Seapony necklace and turn into a Seapony your skin doesn't change back when you leave the water how I would expect it 

But the other way around if I have a Seapony skin it and am not the Seapony species it still changes my skin when I touch water which just seems weird as I'm not a Seapony from unicopias perspective

**Comment by Sollace** [comment]
This is a 1.20.2+ feature

**Comment by MimzyFang** [comment]
> This is a 1.20.2+ feature

Ah I didn't know
