### ISSUE TITLE
AlicornAmulet causing crash 

### ISSUE THREAD

**Issue by LuckyDusk** [Sollace/Unicopia#3]
So every time I start the game up I get this from the mc launcher 

"The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/minelittlepony/unicopia/extern/BaubleAlicornAmulet"

[crash-2019-02-21_00.21.29-client.txt](https://github.com/Sollace/Unicopia/files/2887933/crash-2019-02-21_00.21.29-client.txt)

**Comment by Sollace** [comment]
It's the baubles support causing the game to crash. It should be fixed in the next build.
