### ISSUE TITLE
Changeling Crash with New Update

### ISSUE THREAD

**Issue by GnomeEater** [Sollace/Unicopia#30]
https://pastebin.com/0ASThKgS
I received this crash whenever I attempted to disguise as a Changeling after installing the newest update. Note that I tried this in two separate worlds, one made before the update and another after, and both still crashed immediately after using the disguise power. Figured you might want to look into the cause whenever you're able to.

**Comment by Sollace** [comment]
https://github.com/Sollace/Unicopia/releases/tag/beta-8b
