### ISSUE TITLE
Bees don't pollinate oats

### ISSUE THREAD

**Issue by Samurott1999** [Sollace/Unicopia#301]
The oat plants don't have the block tag that allows bees to pollinate them (bee_growables), which results in slower growth compared to other plants. Other plants that I've seen, such as the pineapple, do have it. It seems to be just the oats.
I'm using 1.3.3 on Minecraft 1.20.1, for reference.

**Comment by Sollace** [comment]
I'm not aware of any vanilla mechanic that lets bees pollenate crops.

**Comment by MimzyFang** [comment]
> I'm not aware of any vanilla mechanic that lets bees pollenate crops.

It's been a thing ever since bees were added https://minecraft.wiki/w/Bee#Pollinating

**Comment by Sollace** [comment]
> > I'm not aware of any vanilla mechanic that lets bees pollenate crops.
> 
> It's been a thing ever since bees were added https://minecraft.wiki/w/Bee#Pollinating

I see. I thought that meant only flowers
