### ISSUE TITLE
New Item: Flour

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#309]
Made by grinding wheat using a grindstone (no point in making a whole separate grinder just for wheat) you can then use this item to craft various baked goods such as muffins, cakes, cupcakes, etc.

**Comment by Sollace** [comment]
This is actually something I already did for a different unreleased mod (Baker's Delight). Thus I'm kind of hesitant to add this, as otherwise it's a slipper slope towards Unicopia absorbing that other project.
