### ISSUE TITLE
Pony models tilt 90 degrees forward when flying.

### ISSUE THREAD

**Issue by kerplamp** [Sollace/Unicopia#31]
Whenever I fly using just Pegasus or the Wings of Icarus the pony model will tilt forward enough to face directly downward. I think it has to do with humans flying and how when they fly they tilt forward to make themselves parallel to the ground. It might just be applying to all flying players and not just human flying players.

**Comment by Sollace** [comment]
You need the latest version of Mine Little Pony (at least 4.2.2) as that has the required APIs to correct the tilting.
