### ISSUE TITLE
New Blocks: Liquid Color and Rainbow Color

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#311]
Liquid Color is a new kind of bucketable liquid that can be crafted by combining a water bucket with a dye of your chosen color. Using red will give you Liquid Red, blue will give you Liquid Blue, cyan gives you Liquid Cyan, so on and so forth. These can be placed like water can, or you can use them to craft Rainbow Color by combining them with a cloud block. You can also obtain Liquid Color by killing mobs of the corresponding color with a bucket, as a reference to the Rainbow Factory. Getting one of every color this way will grant you the advancement/achievement "In The Rainbow Factory"

Rainbow Color is a new kind of decorative cloud block. Depending on the Liquid Color you craft them with, they'll be the corresponding color. Liquid Red gives you Rainbow Red, Liquid Pink gives you Rainbow Pink, and so on and so forth. These will occasionally spawn as a rare structure for clouds in the form of, well, a rainbow. These blocks can be sheared to get their corresponding color in the form of dye, and the blocks will simply disappear, or alternatively turn back into cloud blocks.

Both block types have supporting evidence in the show for why they should exist in these two separate forms, that being scenes where we see the rainbow as a solid object the CMCs use a vacuum to drain color from (hence the ability to shear rainbow blocks) and of course Liquid Color from the weather factory episode. We see rainbows in a solid and liquid form throughout the series as separate things, so it only makes sense to me to have both a liquid and solid form for this. It's also useful to have both for different kinds of decorating.

**Comment by PrinceDrowsy** [comment]
Additional Note: Liquid Color can be drank with varying effects depending on the color, much like in the weather factory episode.

**Comment by PrinceDrowsy** [comment]
@Fauli1221 How come, if you don't mind me asking?

**Comment by MimzyFang** [comment]
> @Fauli1221 How come, if you don't mind me asking?

Doesn't fit the project

**Comment by PrinceDrowsy** [comment]
> > @Fauli1221 How come, if you don't mind me asking?
> 
> Doesn't fit the project

I was thinking back on this concept again, and perhaps if I simplified it a bit and related it to the core systems of the mod as an ingredient for perhaps a new potion or spell (in reference to the cutie mark crusaders using it to make a love potion in the show) would it better suit the project do you think?

Maybe just as rainbow blocks by themselves (instead of the liquid _and_ blocks) spawning decoratively in cloud structures that can be sheared to obtain dyes and used in said potion mentioned above? They could also be used to craft light-related spells, perhaps?

**Comment by EternaDash** [comment]
I Smell Rainbow Factory
