### ISSUE TITLE
Debuff to Siphon Love 

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#312]
I have noticed that while in combat with a changeling, the Siphon Love ability makes them far too powerful in PVP, being able to leech a significant portion of HP in a moment. Since changelings do not use their ability to feed as a viable method of combat, the only time we see it being Chrysalis siphoning Thorax as a show of power rather than an actual combat maneuver, I believe it'd be best to make the ability work a bit differently for lore accuracy, as well as balancing out PVP. 

My suggestion would be to have the power leech a heart of health every few seconds (recovering a point of hunger for every heart) as the ability is held to activate and so long as the target stays in a close enough proximity to the changeling. This would make it less of an overwhelming K.O. in PVP, as well as be more accurate to the show in function and ability.

**Comment by Sollace** [comment]
I agree. That sounds like a lot better way to do it. This would basically put it in line with how grogar's bell works
