### ISSUE TITLE
Tornado/Dust Devil Ability

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#313]
We see Rainbow Dash make a small, self-contained tornado in the episode Swarm of the Century. I think this would be an incredibly fun and cool ability for pegasi to have. It could slowly pull mobs toward it (this can be fought to some avail) and damage them once they come into contact with the main body of the tornado, going heart/hit point by hit point like a cactus. This ability requires speed build-up in the same way the sonic rainboom does, however this is to a lesser degree, and requires a different method than diving, that being spinning in a circular motion with rapid wing movement/flapping. Simply gliding in a circle won't produce the wind speeds required to activate this skill.

I imagined the visual would be utilizing an animated 3D model with some minor particle effects. The 3D model, as a potential suggestion, could be in four slightly transparent segments, each segment wiggling/rotating a bit as they shift from side to side opposite of the segment below it. The base piece at the bottom would not move.

These are just suggestions though, so feel no pressure to utilize them if there's a superior method.
![image](https://github.com/Sollace/Unicopia/assets/75338505/2e6948f9-8dbe-425d-89a9-a6db8ddd6b95)

![image](https://github.com/Sollace/Unicopia/assets/75338505/9003c6cf-adfa-4884-9680-54bf2966c361)

**Comment by MimzyFang** [comment]
thanks for the suggestion but this is probably a bit to complicated to implement and would make Pegasi way to overpowered and unbalanced
