### ISSUE TITLE
remove camera tilt from avian flight

### ISSUE THREAD

**Issue by minty-cups** [Sollace/Unicopia#314]
there should be an option to toggle off the camera tilting, its really motion sickness inducing

**Comment by minty-cups** [comment]
also, this is my first time submitting an issue thing on github. i apologize if this is messy

**Comment by PrinceDrowsy** [comment]
Agreed! I often get quite sick from this feature, having motion sickness myself, which is a shame because flying is so fun. The ability to disable it would be perfect.

**Comment by MimzyFang** [comment]
I'd say this should be added to the Accessibility settings
