### ISSUE TITLE
Crystal Shards Replacing Diamonds From Diamond Ores Is Annoying

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#315]
When You Find Diamond Ore, You Expect Diamonds, Obviously. The Fact I Can Be Given A Crystal Shard, Which Is A Third Of A Diamond, And I Can't Even Convert Them Back To Diamonds With Three Of Them, Gets Annoying Real Fast When I Need That Diamond From A Vein But It Gets Replaced By A Crystal Shard, And Now I Have To Go Find Another Diamond Vein. This Is Especially Annoying As A Pegasus, Who Doesn't Even Get Usage Out Of Gemstones.

Honestly, This Could Probably Be Fixed By Having The Crystal Shard Drop Alongside A Diamond, Having A Separate Ore For It, Or Just Removing The Chance For A Shard To Drop Altogether.

**Comment by Sollace** [comment]
This is already fixed in dev.
