### ISSUE TITLE
Super jittery flight camera, beta 8

### ISSUE THREAD

**Issue by BlasterM5** [Sollace/Unicopia#32]
Trying this mod out with a special modpack, and I noticed when flying around, when you near the bottom of the stamina bar, the camera shakes like the Enterprise is under attack.

Except when you land, it keeps going.

And going.

For many seconds.

I can understand the camera shake being a feature, but it could use a bit of a tone-down.

Will test further...

Edit: With only Mine Little Pony, Fabric API, and this mod, the shakination exists.

**Comment by Sollace** [comment]
The shaking means you're over-exerting yourself. It will fade after a few seconds. The intention is that you should land and rest to recover before the shaking becomes too much.
