### ISSUE TITLE
Optifabric crash post 1.3.0

### ISSUE THREAD

**Issue by Lopun-Night** [Sollace/Unicopia#320]
Updates 1.3.0 and beyond crash on startup when paired with Optifabric.
[crash-2024-03-25_14.04.31-client.txt](https://github.com/Sollace/Unicopia/files/14749185/crash-2024-03-25_14.04.31-client.txt)

**Comment by MimzyFang** [comment]
Optifine is not supported please use an alternative
https://lambdaurora.dev/optifine_alternatives/

**Comment by Lopun-Night** [comment]
I see. Thank you for your response and the link.

**Comment by MimzyFang** [comment]
@Lopun-Night if you want something that has almost all optifine features and more I would recommend this modpack
https://modrinth.com/modpack/fabulously-optimized and if you have issues with it we have a much easier time debugging the issue and will be able to support you

**Comment by Lopun-Night** [comment]
Much appreciated, I will look into it.
