### ISSUE TITLE
Random Lightspeed Wind

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#321]
In A Storm, I Do See How It Makes Sense For Flight As A Pegasus To Not Go Particularly Well. What I Don't See Is It Launching Me At Ungodly Speeds Into A Wall With Zero Time To React, Instantly Vaporizing My Health With Kinetic Energy. I Can Only Imagine How Someone Would Feel If They Lost A Decently Old Hardcore World To That. I _Assume_ Storms Randomly Hitting The Player With Comically Fast Winds Isn't Intended?

**Comment by MimzyFang** [comment]
This is an intended feature please avoid flying in bad weather

**Comment by MimzyFang** [comment]
Or alternatively fly so high up that there is no wall to get launched into

**Comment by Sollace** [comment]
Probably fixed with today's changes.
