### ISSUE TITLE
i cant figure out how to eat as a changeling

### ISSUE THREAD

**Issue by vriedi** [Sollace/Unicopia#323]
im playing on 1.20.1 and i cant figure out how to siphon love

**Comment by Cryghast** [comment]
As a changeling，you can use your ability to suck love from mobs，or you can drop glass bottle， mug or bucket near the activated crystal heart to fill it with love.
作为幻形灵，你可以用技能从怪物那里吸取爱，或者将玻璃瓶，马克杯或桶扔在激活的水晶之心附近，以将其填满爱。

**Comment by vriedi** [comment]
what key i cant figure it out

**Comment by Cryghast** [comment]
> what key i cant figure it out

There are multiple pages，try press PageUp or PageDown botton （on the right side of your keyboard） to switch between different ability pages

The default key to switch pages are PageUP and PageDown，you can change that in settings

**Comment by Sollace** [comment]
Changelings can also eat raw meat and rotten flesh (unless I'm forgetting what has been released yet)
