### ISSUE TITLE
Changeling-related suggestions, such as Metamorphosis.

### ISSUE THREAD

**Issue by GodkingLuckyBunny** [Sollace/Unicopia#324]
I saw that normal Changelings are in the game and getting some updates sometimes, so I figured I'd put all my Changeling ideas in here for the mod.

My first one is the Metamorphosed Changeling as a race. I know it may have some balancing issues, since it removes their need to feed on love (or anything at all rather kinda) and instead feed by giving love, which is way easier, but mayhaps that can be solved by making it where you have to earn the metamorphosis like in the show, or at least can't choose that race and have to become it. (The metamorphosis could go nice with a possibly race-based autoskin change, but that's a story for another time.)
![image_2024-04-04_231319790](https://github.com/Sollace/Unicopia/assets/74641640/62bdbceb-bad3-4971-b886-27dc312866c2)
This is what Metamorphosed Changelings look like. ^^^ They're also known as Reformed Changelings or Changedlings.

Another suggestion of mine is a way for Changelings to use cocoons. It's likely that the actually full-on cocooning should be restricted to a type of Changeling royalty if it's in an ability form, though trapping mobs via use of Changeling goo could work for the more typical Changelings as a way to hinder mobs or to be able to feed on their love via the balancing thing mentioned by [drowsiestprince](https://github.com/drowsiestprince) in https://github.com/Sollace/Unicopia/issues/312. It could also just be blocks that slow down your movements and such, much like Slime Blocks or Honey Blocks, which can just be in the Changeling Hive, maybe as cages containing mobs.
![image_2024-04-04_232434480](https://github.com/Sollace/Unicopia/assets/74641640/6df82fa3-a055-4c4a-b35c-ba01b10cc8a7)
![image_2024-04-04_232713372](https://github.com/Sollace/Unicopia/assets/74641640/80bb1ec8-558f-4293-84ac-dcbe7081e9d7)

The final suggestion I have related to Changelings, which is related to the Changeling Hive structures that are in the mod as mentioned before, is Changelings as a mob. I would like to see the other races as mobs too, that way, even if you're singleplayer or just playing with a few friends, some ponies will be just doing stuff around your world (non-destructive, of course,) letting the world feel more lived in and like others exist than just you. The Changelings in particular would likely be mobs that wouldn't be all too kind to mobs or players that aren't Changelings or tamed by/friendship bracelet with a Changeling, at least until they metamorphose. These Changelings would just kinda exist otherwise, though a Changeling queen or king could be a type of boss that you could fight to overthrow, maybe being how you would unlock the ability to metamorphose if you do it without violence or something. Once you have overthrown a Changeling King or Queen, maybe you could then command the Changelings like Queen Chrysalis (and King Throax too to an extent,) in order to get them to do tasks and such for you, like guarding a location. I guess this could also come with it's own things in order to get more Changelings and such, but that's up to you, the devs, to decide.
![image_2024-04-04_232516392](https://github.com/Sollace/Unicopia/assets/74641640/2ce3dab2-944d-4aa8-8ba4-b2d44aefad4f)

It's up to you guys making the mod whether you add these changes or not, it's your mod after all, and that's how the cookie crumbles, but as long as I'm heard, I'm good.

**Comment by GodkingLuckyBunny** [comment]
Also, I seemingly couldn't figure out how to label these with the labels and such, so....sorry if that's annoying at all.

**Comment by Sollace** [comment]
Alright so I finally got around to looking at this and it seems like most of this is for things that are already planned or asked for.

No plans to add changedlings at this time. Sorry.

https://github.com/Sollace/Unicopia/issues/175
https://github.com/Sollace/Unicopia/issues/116
