### ISSUE TITLE
Unicorn Teleportation Randomly Dealing Absurd Damage

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#328]
I Spawn Into A World And Walk Around For A Bit Before Trying To Use Teleport. But When I Used It, For Some Reason I Took 8 Hearts Of Damage, Nearly Killing Me On The Spot. There Was Tall Grass Nearby I Was Trying To Avoid When Teleporting, And I Had Full Mana Since I Only Just Spawned. The Place I Was Trying To Teleport To Was Only About 10 Blocks Away.

**Comment by Sollace** [comment]
This should be fixed with the next update. The damage you're taking is wall damage, since sometimes the teleport can clip you into nearby blocks if you teleport from a spot straddling two positions.
