### ISSUE TITLE
Game Crashed While Flying, Banished To Space (suddenly at Y=638084)

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#329]
![image_2024-04-09_060805063](https://github.com/Sollace/Unicopia/assets/153742870/6bfe3acd-bbc5-4585-91af-ccd34e975e67)

Something Similar Happened A Bit Ago With Dimensional Doors, But Instead In The Negatives. I Just Figured It Was A Problem With That Mod Instead, But This Is Making Me Think Otherwise

**Comment by coppercore** [comment]
+1 I've had this crazy Y teleportation happen as well with Dimensional Doors if i die in a pocket and get sent into Limbo.

**Comment by EternaDash** [comment]
The Dimensional Doors One Actually Caused Me To Lose God Armour I Spent Ages On Since I Was Well Into The Void, Which... It Stung, To Say The Least.

**Comment by Sollace** [comment]
Please wait for the next update and tell me if the problem still happens after then. I have no idea what would cause this to happen since I've never seen it personally, but also part of the changes in 1.3.4 is supposed to cap the maximum speed to prevent pegasi from flying too quickly.
