### ISSUE TITLE
Silence Suggestion (Kirin)

### ISSUE THREAD

**Issue by GodkingLuckyBunny** [Sollace/Unicopia#330]
It's a probably really dumb suggestion and wouldn't be all that neat for some people, but I figured I'd suggest it anyways just to see what the devs here think about this.
![image](https://github.com/Sollace/Unicopia/assets/74641640/03ad46fc-93f3-48a0-9b70-6ec2d728d6b3)
In the show, the Kirin step through the Stream of Silence in order to suppress their voices and emotions and all that, which I'm guessing is the reason for the abilities of them being silent until their rage form, which counteracts their silence. If not, I'm at least reasonable here. Either way, I thought of the dumb suggestion of making a thing where Kirins are prevented from chatting in chat (with a few exceptions so things like commands can work properly and such,) with all their chat messages either being silent, like "....", just completely blank, or just not able to be sent at all. This could also possibly be integrated with mods that allow chat methods if desired, like making it stop you from talking in Simple Voice Chat too. This could be undone by some Foal's-Breath flowers, which undo the effects of the Stream of Silence, thus allowing the player to speak again, though I recommend making it able to be turned off in the config, for those who don't want their voice to be silenced (and since it's a pretty minor thing gameplay wise, it's probably fine). I also imagine going into rage form turns off this silence too, but idk if that's how it works.

**Comment by GodkingLuckyBunny** [comment]
Random dumb thought:If this was added into the mod and people were playing it, they'd probably have to get very creative when talking to people as a Kirin. (Yes, I'm also aware that they unsilence their voices eventually, but this is entirely hypothetical.)

**Comment by Sollace** [comment]
I don't really want to interfere with the in-game chat. Besides that being kind of tricky since the chat is very complicated, I just don't really like the idea.

Psychedelicraft has drunk speak only because it existed in the mod prior to me updating it.

**Comment by MimzyFang** [comment]
Just unbind the key and if you play with in-game VC be muted at all time's
