### ISSUE TITLE
bug: all doors have a lighting bug

### ISSUE THREAD

**Issue by JossDarkwood** [Sollace/Unicopia#346]
Every door (except for the palm door, for some reason) has a bug where, when opened, the front face of the door is extremely dark. It only seems to happen when there's a solid block on the side opposite the hinges (ex: if the door opens to the right, then if there's a block to the left, the bug happens.)
I know Minecraft's lighting system is a little broken, and I think I've seen this exact thing with vanilla doors in the past, but I figured I should post about it in case it's something you can fix.

![2024-05-08_20 12 19](https://github.com/Sollace/Unicopia/assets/88699189/f3ecc73c-6dcf-4ad1-94d2-eedb9307538c)

Also, none of the palm wood blocks have a crafting recipe (except for the basket and the hanging sign). This is probably intentional, they probably just haven't been added yet, but I thought it was something worth mentioning.

**Comment by Sollace** [comment]
The palm blocks should all have recipes. I will check. It maybe they fell through the cracks during the datagen move.

I don't experience the lighting issue. Are you using anything that changes render (i.e. sodium, optifine, rubiddium, etc)?

**Comment by JossDarkwood** [comment]
I do, actually! I can't believe I didn't think of mentioning that, I'm so sorry.
I have Sodium, Lithium, Indium, Starlight, and FerriteCore. (I really want Minecraft to run well, okay? lol) I also have LambDynamicLights (self-explanatory), Chunks Fade In (also self-explanatory), and Continuity (connected textures). So it's probably a mod conflict. I'll go ahead and experiment, try disabling some of them to see if that fixes it. It might not be anything on your end, so I'm sorry.
I'll add another comment if I figure out what's causing it.

**Comment by JossDarkwood** [comment]
Well, I removed every mod except for Unicopia (and the fabric API, obviously) and that still didn't fix it. So I'm thinking it has to be some kind of graphics error on my end, if you're not getting the same problem. Sorry!

**Comment by MimzyFang** [comment]
> I do, actually! I can't believe I didn't think of mentioning that, I'm so sorry.
> I have Sodium, Lithium, Indium, Starlight, and FerriteCore. (I really want Minecraft to run well, okay? lol) I also have LambDynamicLights (self-explanatory), Chunks Fade In (also self-explanatory), and Continuity (connected textures). So it's probably a mod conflict. I'll go ahead and experiment, try disabling some of them to see if that fixes it. It might not be anything on your end, so I'm sorry.
> I'll add another comment if I figure out what's causing it.

Try removing starlight it's no longer needed since 1.20 and known for causing some issues

**Comment by Sollace** [comment]
> Also, none of the palm wood blocks have a crafting recipe (except for the basket and the hanging sign). This is probably intentional, they probably just haven't been added yet, but I thought it was something worth mentioning.

All of the palm blocks have recipes

**Comment by JossDarkwood** [comment]
Weird. Well, something must've somehow gone catastrophically wrong on my end! (Unless you mean that you just added them again, but I don't think you do.) I'll try redownloading the mod and see if that fixes anything. Sorry for wasting your time!
