### ISSUE TITLE
Apples Inside Leaves

### ISSUE THREAD

**Issue by OakPlatinum** [Sollace/Unicopia#352]
Is this supposed to happen?
Btw, when using Jade, some blocks and entities only display their localization keys. (Sorry I forgot to take a screenshot for this.)
Thank you!

![IMG_20240511_025145.png](https://github.com/Sollace/Unicopia/assets/169054099/71b64793-057f-496d-8267-40c93408dee7)

**Comment by Sollace** [comment]
What items are only showing their localization keys?

**Comment by OakPlatinum** [comment]
Various apple **blocks**, butterflies in early versions, crystal heart **entity**, etc.
(I'll send a detailed list later. It's 5:30 a.m. here.)q

**Comment by OakPlatinum** [comment]
Various apple **blocks**, butterflies in early versions, crystal heart **entity**, etc.
(I'll send a detailed list later. It's 1:30 a.m. here.)

**Comment by EternaDash** [comment]
This Made Me Think Of An Idea: Maybe Leaves From Those Specific Apple Trees Could Drop Their Respective Apples Occasionally, Like How Oak Leaves Drop Vanilla Apples

**Comment by OakPlatinum** [comment]
Blocks are too many, so I didn't check them. :(
Basically those not in the Creative Inventory.

| Entity            | Has Localization String |
|-------------------|-------------------------|
| air_balloon       | Yes                     |
| butterfly         | Yes                     |
| cast_spell        | Yes                     | 
| crystal_shards    | Yes                     |
| **floating_artefact** | No                      |
| **friendly_creeper**  | No                      |
| ignominious_bulb  | Yes                     |
| ignominious_vine  | Yes                     |
| **loot_bug**          | No                      |
| **magic_beam**        | No                      |
| mimic             | Yes                      |
| **muffin**            | No                      |
| sombra            | Yes                     |
| specter           | Yes                     |
| spellbook         | Yes                     |
| storm_cloud       | Yes                     |
| **thrown_item**       | No                      |
| twittermite       | Yes                     |

Examples:
![图片](https://github.com/Sollace/Unicopia/assets/169054099/a93142a9-ba4d-43a8-baef-0ab1e380bbea)
![图片](https://github.com/Sollace/Unicopia/assets/169054099/39c91516-d1b7-4e66-b417-be3543deecb2)

And, this is a problem too. (Should I open a new issue?)
![图片](https://github.com/Sollace/Unicopia/assets/169054099/596b704a-13c3-48b9-beda-e65894a7ef68)
![图片](https://github.com/Sollace/Unicopia/assets/169054099/ee8d6be2-d8ba-4f87-bd4f-f908c9cf5410)

Btw, may I ask you a personal question on Discord, @Sollace ?

**Comment by Sollace** [comment]
> Blocks are too many, so I didn't check them. :( Basically those not in the Creative Inventory.
> Entity 	Has Localization String
> air_balloon 	Yes
> butterfly 	Yes
> cast_spell 	Yes
> crystal_shards 	Yes
> **floating_artefact** 	No
> **friendly_creeper** 	No
> ignominious_bulb 	Yes
> ignominious_vine 	Yes
> **loot_bug** 	No
> **magic_beam** 	No
> mimic 	Yes
> **muffin** 	No
> sombra 	Yes
> specter 	Yes
> spellbook 	Yes
> storm_cloud 	Yes
> **thrown_item** 	No
> twittermite 	Yes
> 
> Examples: ![图片](https://private-user-images.githubusercontent.com/169054099/329816239-a93142a9-ba4d-43a8-baef-0ab1e380bbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTMwMzgsIm5iZiI6MTcxNTY5MjczOCwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE2MjM5LWE5MzE0MmE5LWJhNGQtNDNhOC1iYWVmLTBhYjFlMzgwYmJlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMzE4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDUzZDBlYmExZTc2NjI1MTllZWE5MzgwNzVkOTljOWJjMzI4NzNjNmRmNGRjYjU0OTA3MGE3YmRhMTNhYjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gR-qAgMzRSCPcEDzQDhYgFPixdzhaVosxD-oEcj9wk8) ![图片](https://private-user-images.githubusercontent.com/169054099/329816226-39c91516-d1b7-4e66-b417-be3543deecb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTMwMzgsIm5iZiI6MTcxNTY5MjczOCwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE2MjI2LTM5YzkxNTE2LWQxYjctNGU2Ni1iNDE3LWJlMzU0M2RlZWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMzE4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWE5YWQwZjQ1MmFmODFhNTBlMzRiMmRiMzkxYTNiOGVlZWZlNmIxNGJlODRjZmM3ODk2NWJhYTM2ZWZmYWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hKsNDX9A47lekEXwbaWVqEZnnW-xhszGg8d876L50vc)
> 
> And, this is a problem too. (Should I open a new issue?) ![图片](https://private-user-images.githubusercontent.com/169054099/329817044-596b704a-13c3-48b9-beda-e65894a7ef68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTMwMzgsIm5iZiI6MTcxNTY5MjczOCwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE3MDQ0LTU5NmI3MDRhLTEzYzMtNDhiOS1iZWRhLWU2NTg5NGE3ZWY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMzE4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDYzNWJkOTg2ZWQyNjA4NjY2NTkzOTM3M2U4NzBlOTE1MzBlOTQ3ZWYyNWNkNTEzMGFkODlmZjc1ZDliOWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0cteUWLWNPEqNkMHrQzsGQ0Ytw0c-L4rXXfxlb_4fxk) ![图片](https://private-user-images.githubusercontent.com/169054099/329817008-ee8d6be2-d8ba-4f87-bd4f-f908c9cf5410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTMwMzgsIm5iZiI6MTcxNTY5MjczOCwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE3MDA4LWVlOGQ2YmUyLWQ4YmEtNGY4Ny1iZDRmLWY5MDhjOWNmNTQxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMzE4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmJkMzBjODUzNDBiNWUzYjZhNmZhNzY4MWY1OWFlOTI5ZWRiNDExYzcwOWZjYzc0YzBhMGQ3MTg2YTE2MjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvd6CoJI2mZWttl9NFtdGSyBQZDmYR1zvZdanm0rquo)
> 
> Btw, may I ask you a personal question on Discord, @Sollace ?

These are technical entities that you don't normally see their names for during regular gameplay so they didn't get translated.

Second one is a translation issue. It needs to be fixed it on [crowdin](https://crowdin.com/project/unicopia).

**Comment by Sollace** [comment]
> This Made Me Think Of An Idea: Maybe Leaves From Those Specific Apple Trees Could Drop Their Respective Apples Occasionally, Like How Oak Leaves Drop Vanilla Apples

They're not really meant to with fruit trees since the fruit grows under the leaves. You're supposed to farm it that way rather than destroying the tree.

**Comment by OakPlatinum** [comment]
Could you please approve my correction on crowdin?
Also, I'm glad to help with translation if you don't mind.

**Comment by Sollace** [comment]
> Blocks are too many, so I didn't check them. :( Basically those not in the Creative Inventory.
> Entity 	Has Localization String
> air_balloon 	Yes
> butterfly 	Yes
> cast_spell 	Yes
> crystal_shards 	Yes
> **floating_artefact** 	No
> **friendly_creeper** 	No
> ignominious_bulb 	Yes
> ignominious_vine 	Yes
> **loot_bug** 	No
> **magic_beam** 	No
> mimic 	Yes
> **muffin** 	No
> sombra 	Yes
> specter 	Yes
> spellbook 	Yes
> storm_cloud 	Yes
> **thrown_item** 	No
> twittermite 	Yes
> 
> Examples: ![图片](https://private-user-images.githubusercontent.com/169054099/329816239-a93142a9-ba4d-43a8-baef-0ab1e380bbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTQ4MzUsIm5iZiI6MTcxNTg5NDUzNSwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE2MjM5LWE5MzE0MmE5LWJhNGQtNDNhOC1iYWVmLTBhYjFlMzgwYmJlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMTIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmI5NTA5MjQ1ZTUxYjBmZGRiZmJiYjY4Mjc4NDE4NGM1MDI0MjNiZjkxMDY5YzQwNjg0NzMwMzI0MGRhM2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vkSimxFIIZuWSn8omP6WCqC5FoAMsYVJx60s2Y1YYbg) ![图片](https://private-user-images.githubusercontent.com/169054099/329816226-39c91516-d1b7-4e66-b417-be3543deecb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTQ4MzUsIm5iZiI6MTcxNTg5NDUzNSwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE2MjI2LTM5YzkxNTE2LWQxYjctNGU2Ni1iNDE3LWJlMzU0M2RlZWNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMTIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmQ5ZWNiYTI5N2IyZmUzYjBlYzgyNTBjMGQ2NDA4M2UwZjRjMmUxNTkxYzhkOWU4NTU4ODYyNjJjMzAxZDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bQAoPRnquMr1XZThrAZskDLCVp65taOE8mCiP28Om9c)
> 
> And, this is a problem too. (Should I open a new issue?) ![图片](https://private-user-images.githubusercontent.com/169054099/329817044-596b704a-13c3-48b9-beda-e65894a7ef68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTQ4MzUsIm5iZiI6MTcxNTg5NDUzNSwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE3MDQ0LTU5NmI3MDRhLTEzYzMtNDhiOS1iZWRhLWU2NTg5NGE3ZWY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMTIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWJjOWQ5MDhmMjIxMTA2NzRmYzIwOTVjNGY0N2IwNDhmM2NmMjQ5MDdlOTdmZmE2YzNkMmFiYzc3YzgzMDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zPHJg4R6tR6sOcDfHWtLH79N_5OLWzDLZ5nNzEKNs3o) ![图片](https://private-user-images.githubusercontent.com/169054099/329817008-ee8d6be2-d8ba-4f87-bd4f-f908c9cf5410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTQ4MzUsIm5iZiI6MTcxNTg5NDUzNSwicGF0aCI6Ii8xNjkwNTQwOTkvMzI5ODE3MDA4LWVlOGQ2YmUyLWQ4YmEtNGY4Ny1iZDRmLWY5MDhjOWNmNTQxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMTIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWFlOWVlN2JhMTQwZDZhZGRlNTE5M2RkYzhmZTRkMDRmOGVmZDRhZDY5YzQ2OWM4ZTIwZTI5YWJjZGUxZmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FFOMXi0Klb0bcLNC8jqhfemUlbRCEXHa0wsHB-o9G4o)
> 
> Btw, may I ask you a personal question on Discord, @Sollace ?

Please report a bug to your other mod. They should be using `entity.getName()` or `entity.getDefaultName()` to get the names of entities.
