### ISSUE TITLE
Prot Stacking

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#353]
As Any Race, Cast Protection From Hand. Afterwards, Get Another Protection Spell, And Cast That From Hand As Well. The Two Protection Spells Will Stack On Top Of Eachother, Which Also Stacks The Repelling Effect It Has, So With 10 Of Them You Launch Any Unsuspecting Foe Into The Aether.

I Presume This Would Also Work With Other Normally-Unstackable Spells, But I Found It Via The Protection Spell.

Also Mini-Issue: You Can't Remove Your Own Protection Spell If You Cast It By Hand Without Dying, Which Could Pose Some Issues If You Have Friends, Pets, Or Farm Animals You Would Prefer Not Be Put Into A Space Program.

**Comment by Sollace** [comment]
Just for this one, I'm making a new tag.

**Comment by Sollace** [comment]
> Also Mini-Issue: You Can't Remove Your Own Protection Spell If You Cast It By Hand Without Dying

Tap V.

![image](https://github.com/Sollace/Unicopia/assets/6429283/ee5b481b-4db0-465d-95db-5f1d1e16785d)

**Comment by Sollace** [comment]
![image](https://github.com/Sollace/Unicopia/assets/6429283/adbfe1ec-b54e-4dc7-88d5-d56dc6cacdf0)

**Comment by Sollace** [comment]
> As Any Race, Cast Protection From Hand. Afterwards, Get Another Protection Spell, And Cast That From Hand As Well. The Two Protection Spells Will Stack On Top Of Eachother

Fixed in [#1d156305668b41c24777ad81caf792b54e176d3d](https://github.com/Sollace/Unicopia/commit/1d156305668b41c24777ad81caf792b54e176d3d)
