### ISSUE TITLE
Wrong MineLP Version

### ISSUE THREAD

**Issue by OakPlatinum** [Sollace/Unicopia#354]
???
Shouldn't it be 4.11.7+1.20.4?
![Screenshot_2024-05-13-19-16-47-778_com.github.android-edit.jpg](https://github.com/Sollace/Unicopia/assets/169054099/34e95c65-5d5d-4cd6-90e7-d28f67ee9afb)

**Comment by Sollace** [comment]
It doesn't have to be. That number is a minimum, and 4.11.6 did work on 1.20.4 so long as the updated kirin is provided (which it is)

**Comment by OakPlatinum** [comment]
Actually I thought so before.
I tested it myself on IDEA, and it (MineLP) required modmenu 8.0.0 so the game crashed. When I changed the version to 1.20.4, it worked. Idk why, tbh. Probably my mistake.

**Comment by OakPlatinum** [comment]
And it seems MineLittlePony's modmenu overrides Unicopia's.

**Comment by Sollace** [comment]
Dunno. I normally run it in eclipse and it uses the version of modmenu unicopia asks for.

I will note you might need a fabric_loader_dependencies.json in your config folder to run it inside the ide

```
{
  "version": 1,
  "overrides": {
    "unicopia": { "depends": { } },
    "kirin": { "depends": { } },
    "fabwork": { "depends": { } }
  }
}
```

This is because when running in the ide the versions in fabric.mod.json doesn't get updated.

**Comment by OakPlatinum** [comment]
I'll try it. Thank you so much! <3
