### ISSUE TITLE
Polearms Should Be Spears

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#355]
The Polearm Item Feels Useless. It Attacks Agonizingly Slow, It Does Pitiful Damage For It's Attack Speed, And I Find It Pretty Easy To Punch Out Zap Logs Damageless Without It. So I Feel Like Repurposing It Into A Spear Would Fix That. It Could Attack As Slow As An Axe And Still Do One Less Damage Than A Sword, But Would Keep The Reach It Currently Has, Making It A Good Choice If You Want To Attack From A Safe Distance Without Using Arrows, And Are Okay With Sacrificing Speed.
![image_2024-05-13_142700030](https://github.com/Sollace/Unicopia/assets/153742870/6f7429d2-0aba-4eb0-915c-ff565e3ac963)
_⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀i also just wanna be roman, but that's a personal thing_

**Comment by Sollace** [comment]
I thought about doing this already but decided not to because polearms seemed powerful already.

**Comment by PrinceDrowsy** [comment]
Polearms are honestly quite useful for fighting phantoms, and once more flying mobs are introduced I think it'll be quite the vital weapon in a pegasus pony's arsenal.

**Comment by EternaDash** [comment]
> Polearms are honestly quite useful for fighting phantoms, and once more flying mobs are introduced I think it'll be quite the vital weapon in a pegasus pony's arsenal.

Having Polearms Strictly Be Useful Against Flying Mobs Feels Wrong, I Mean It Already Looks Like A Spear So Why Can't It Actually Function Against Regular Mobs?

**Comment by PrinceDrowsy** [comment]
> Having Polearms Strictly Be Useful Against Flying Mobs Feels Wrong, I Mean It Already Looks Like A Spear So Why Can't It Actually Function Against Regular Mobs?

I wouldn't say they're _strictly_ useful against flying mobs. They can be used the same as any other weapon, just with their own individual unique trait. Tridents can be thrown, axes do more damage, swords are swift, and polearms have great reach. I feel like that suits the general trend of weapons. Addressing your point directly though, they're also good for hitting endermen from a safer distance, allowing unicorns a better reach while utilizing their shield spell, and perfect for mob farms.

**Comment by PrinceDrowsy** [comment]
OH! Actually, one suggestion could be that they do more damage against armored mobs/players specifically! Since they'd pierce through the gaps and whatnot. Not too OP while still giving them an additional unique use. Perhaps they don't do additional damage _every_ time to account for "error" in "missing the gaps" if needed to be nerfed a tad during testing?

**Comment by EternaDash** [comment]
> OH! Actually, one suggestion could be that they do more damage against armored mobs/players specifically! Since they'd pierce through the gaps and whatnot. Not too OP while still giving them an additional unique use. Perhaps they don't do additional damage _every_ time to account for "error" in "missing the gaps" if needed to be nerfed a tad during testing?

Adding Armour Piercing Is A Hella Good Idea, I Love That. Though I Still Would Like It To Be Faster, As 0.4 Attack Speed Is Just Not Fun Tbh

**Comment by EternaDash** [comment]
Orbital Striking This Issue Because I'm Making A Remastered Version Of It.
