### ISSUE TITLE
Cant use in server

### ISSUE THREAD

**Issue by ScootalooCMC** [Sollace/Unicopia#36]
Trying to use this in a fabric server Minecraft version 1.17.1 fabric version 0.12.0, but the fabric server saying that the are dependencies or other mods required for this one to work. I tried searching for those and cant find them anywhere.

**Comment by Sollace** [comment]
Please post what it's asking for. I can't help if I don't know which dependency you're missing.

**Comment by ScootalooCMC** [comment]
Mod 'Unicopia' (unicopia) requires "version 0.1.0 or later" of fabric-keybindings-v0, which is missing!

Mod 'Unicopia' (unicopia) requires "version 0.1.0 or later" of fabric-rendering-v1, which is missing!

Mod 'Kirin UI' (kirin) requires "version 0.1.0 or later" of fabric-key-binding-api-v1, which is missing!

**Comment by Sollace** [comment]
You're missing fabric-api. All of those are included in it. https://www.curseforge.com/minecraft/mc-mods/fabric-api/files

**Comment by Sollace** [comment]
That "fabric 0.12.0" is just the fabricloader version.

i.e. To take an analogy to something you might find more familiar:

forge mod loader (fml) -> fabric loader
minecraft forge -> fabric api

They are just not bundled as one thing like forge and fml are so they can be updated separately, and without having to re-run the installer every time (since fabric-api is just a regular mod).

**Comment by ScootalooCMC** [comment]
I have fabric-api-0.42.1+1.17.jar

**Comment by Sollace** [comment]
Uuuuuuhhhhh... One moment.

**Comment by Sollace** [comment]
I have added a beta13-server jar to the release page here: https://github.com/Sollace/Unicopia/releases/tag/1.0.0-beta.13

Try that one, and see if it will resolve your issue. I'll work on a proper fix when I release the next beta.

**Comment by ScootalooCMC** [comment]
Okay this version let the server launch so I think its good. Cool and thnx!

**Comment by ScootalooCMC** [comment]
also side note just the opinion of me and another friendthat the flight mechanics could use an overhaul it seems abit dificult to get into the air and even stay flying forward its like it wants to but cant.

**Comment by Sollace** [comment]
Flight mechanics are as they're intended to be. You need to use shift to flap your wings to gain altitude and hold space to glide. To move forward you hold forward (of course).
