### ISSUE TITLE
Bone Meal Is Useless For Some Reason

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#362]
I Try And Bone Meal Some Crops, Specifically Wheat Seeds. 12 Bone Meal Used, Literally No Progress. That Isn't How Minecraft Works, Something In The Code Is Probably Having A Stroke.

**Comment by Sollace** [comment]
Working fine for me. Try removing your other mods.

![image](https://github.com/Sollace/Unicopia/assets/6429283/c23e09d6-bc3f-46eb-a32b-504e5b39f037)
