### ISSUE TITLE
Seeds Are As Good As Wheat

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#363]
![image_2024-05-20_171844966](https://github.com/Sollace/Unicopia/assets/153742870/aad77d82-a1af-4b98-a349-431e48f194df)
![image_2024-05-20_171952296](https://github.com/Sollace/Unicopia/assets/153742870/e05815e7-6aa3-459c-9ee8-cd2b7244c824)
I Think The Images Show The Issue. We Aren't Birds, Are We?

**Comment by Sollace** [comment]
Are you playing as a hippogrif?

**Comment by EternaDash** [comment]
> Are you playing as a hippogrif?

I'm A Unicorn In This Case. Not To Be Rude, But It's A Tad Obvious

**Comment by Sollace** [comment]
Well your hud was covered, so it wasn't easy to tell what unicopia is considering you as. if you are actually set as a unicorn according to unicopia then this might be unintended. The seeds are meant to be equivalent of wheat for hippogrifs.
