### ISSUE TITLE
Randomly Diving Faster Than Physically Possible Without Even Clicking Crouch Or Looking Down At All

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#365]
Gonna Keep This Short And Sweet, Without Looking Down Or Even Touching Crouch (and not accidentally dashing), I Suddenly Flew At Unfathomably Fast Speeds Towards A Stone Wall. Not Even A Storm, No Rain, The Gods Just Decided I Will Now Become A Fallout Lore Skeleton. It Felt Like I Went Faster Than I Even Should've Been Able To At All. RIP To Anyone Who Lost A Hardcore World To That.

**Comment by Sollace** [comment]
There's a known [bug](https://github.com/Sollace/Unicopia/issues/361) with the flight state desyncing which was already fix in the dev branch.

This doesn't sound like that though. This sounds like the intended mechanic where you gain speed and start gathering points for your super ability when you're flying less than a certain amount of blocks off the ground for more than a certain amount of time.

It has a maximum speed you can travel (regardless of level), and it goes away quickly if you fly up. It typically works fine when you know it's coming and keep it to large open areas, so the only limiting factor is your ability to react, and read changelogs.

![image](https://github.com/Sollace/Unicopia/assets/6429283/8d4eb306-fb24-4582-aaaf-e93c5741d14c)

**Comment by EternaDash** [comment]
> This doesn't sound like that though. This sounds like the intended mechanic where you gain speed and start gathering points for your super ability when you're flying less than a certain amount of blocks off the ground for more than a certain amount of time.

Wasn't Really Gaining Speed As It Was Shooting Me Like A Bullet Out Of Nowhere. Even If It Works Just As Intended, Should You Really Be Able To Be Launched At Supersonic Speeds From Barely Moving At All In Quarter Of A Second?
Maybe I'm Being Stupid, Idk, I Just Don't Want Someone To Lose Their Hardcore World To Something That Feels Totally Unfair, Like Randomly Being Shot Into A Wall Out Of Nowhere For No Discernible Reason.

**Comment by Sollace** [comment]
I don't really get that at all from my playtests, so I don't know what you're experiencing.
