### ISSUE TITLE
Stuck Cooldown

### ISSUE THREAD

**Issue by OakPlatinum** [Sollace/Unicopia#366]
(English isn't my mother tongue, so sorry if you are confused by this.)
I drank a Potion of Metamorphosis, used the necklace before transformation, and used it again after respawning, then it thought I was still a seapony and then tranformed me into my previous race. Next, my cooldown got stuck like this:
![Image_1716651293342.png](https://github.com/Sollace/Unicopia/assets/169054099/f0fb0913-9df3-422d-ad84-3c891e4453bb)

(p.s. I don't like to complain, but could anyone update the out-dated README.md?)

**Comment by Sollace** [comment]
This is a known bug, I just don't really know what causes it yet as it's hard to replicate.

> could anyone update the out-dated README.md

I'll make a note that the readme needs updating. The wiki is meant to be a more substantial source of info, but since things keep changing it's all bound to be outdated to some extent.
