### ISSUE TITLE
Pausing And Unpausing Over Water Whilst Flying Puts You Into A Space Program

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#370]
From My Testing, Pausing And Unpausing When Close Over Water Mid-Flight Sends You Far Higher Than It Should, And Especially If You Do The Procedure Multiple Times Quickly. With About 4 Repeats Of This In Quick Succession, I Get Launched A Whole 40 Blocks Higher From My Own Tests, As Usually It Took Me To Around y=110, And With The Pause Unpause Method It Took Me To Around y=150.

**Comment by Sollace** [comment]
This is normal. Water has an updraft proportional to how high the sun is in the sky.

It happens even when you don't pause.
