### ISSUE TITLE
Infinite Food From Literally One Village

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#371]
Ponies Eat Hay, That's Not Surprising Anypony. And Villages Spawn With Hay Bales, Which Contain 9 Wheat Which Each Are Just As Good As Golden Carrots (they're actually better, but only by 1 point of hunger). This Means, Potentially Off-Spawn, You Can Take All The Hay Bales And Have Effectively Infinite Food, Sidestepping The Earth Pony's Entire Reason For Living (besides doing more damage i guess). You Somehow Exhaust Your Wheat Supply Of Multiple Stacks? You'll Probably Have Found Another Village By Now, And Especially If You're A Pegasus Which Can Just Fly And Nuh Uh The Issue Of Terrain Slowing You Down Entirely.
This Was Also A Tad Bit Of An Issue In Vanilla Or For Humans, Which Get 3 Bread Per Hay Bale, But Bread Doesn't Give Much Saturation And Is A Third Of The 9 Effectively Gold Carrots You Get From 1 Hay Bale As A Pony. When You Can Make The Existence Of An Entire Pony Race Obsolete With A Relatively Common Structure, I Feel There's A Problem.

My Idea On How To Fix This Is In Two Parts: The First Is To Nerf Both The Amount Of Hunger And Saturation Given Per-Wheat And Hay Bale Eaten, For Wheat Maybe Back To 1.3.3 Numbers And For Hay I Suppose To 10 Points Of Hunger And Saturation So 9 Individual Wheat Still Gives More But A Hay Bale Is More Immediate, If Wasteful To Eat.

The Second Is To Do One Of Two Things:
1. Remove The Recipe Converting Hay Back Into Wheat (not ideal, hay bales alone are still edible).
2. Simply Lower Or Remove Hay Bale Spawns From Villages, Inadvertently Fixing The Same (but lesser) Issue With Humans.

⠀

Also Bonus Issue: Trees Also Act As Infinite Food With Shearing Them. Even After The Nerf, The Saturation Stacks As You Keep Eating, So Once More Making Earth Ponies About As Useful As Underthemayo's """Criticism""" Of Ultrakill. Unless You're In- Like, A Desert Or Something. And In That Case, When Are You Getting Seeds? For This, Just Making Leaves Give 0 Saturation Should Do The Trick.

**Comment by PrinceDrowsy** [comment]
Giving leaves zero saturation sounds like a great plan to me. For hay bales, perhaps making them a weaker form of how cakes work would be a good plan? And "raw" hay pieces, so to speak, essentially giving a far lesser amount of saturation and food points than, say, hay fries and the like. Kinda like raw meat vs. cooked.
