### ISSUE TITLE
Oh Hey, A Question For Sollace Themselves

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#374]
Gonna Keep This Simple Because I Don't Wanna Sound Annoying: Why Haven't These Gotten A Response Yet, Despite Being At Least 2 Days Old, And At Most 5 Days Old? I'm Unsure If You've Even Read Them, Which Is Making Me Paranoid Because My Brain Hates Me.
![image_2024-05-29_215024717](https://github.com/Sollace/Unicopia/assets/153742870/18e39185-b295-413e-904f-aa0e62acca73)
_really concerned i'll also sound self-centred since two of the three issues are mine, which isn't what i want, so sorry if i come off as that, i would've asked this even if none of these issues were mine._
i'm just gonna submit this issue, won't get anything done if i do nothing from fear of sounding wrong.

Also Side Note: I'm Sending My PC In For Maintenance So I Probably Won't Be Able To Respond For A Few Days Myself If That's Important In Some Way.

**Comment by Sollace** [comment]
I've seen them, I just don't have anything to say on them yet. Big walls of text are kind of hard to handle so I would appreciate a little patience.
