### ISSUE TITLE
Spellbook broken?

### ISSUE THREAD

**Issue by gutt3rsn1pe** [Sollace/Unicopia#376]
tried multiple times to create spells and made sure I had the levels and correct ingredients, but I ended up with a botched gem even though my book said "new discovered"

**Comment by MimzyFang** [comment]
What Minecraft version/mod loader + mod loader version/mod version are you on

**Comment by Sollace** [comment]
This is a known issue in 1.20.1

**Comment by gutt3rsn1pe** [comment]
im running on 1.20.4

**Comment by gutt3rsn1pe** [comment]
is there a version where the spellbook works or is it just broken

**Comment by MimzyFang** [comment]
Expect a release soon
