### ISSUE TITLE
Quit and load the save will let hostile zombie(generated by necromancy) protect you

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#379]
https://cdn.discordapp.com/attachments/182490536119107584/1248296013060378747/2024-06-06_23.19.47.mov?ex=666325c1&is=6661d441&hm=711a055e9136e4a305d77f547f30e01bdef84e13fdec727330cb33fcf9c86ea9&

https://github.com/Sollace/Unicopia/issues/136

A reversed bug

Unicopia 1.3.6

**Comment by Sollace** [comment]
Stale
