### ISSUE TITLE
Can't perform sonic rainboom?

### ISSUE THREAD

**Issue by Mrufka69** [Sollace/Unicopia#381]
I'm playing on Minecraft version 1.20.4

Despite having 450 mana and starting from the maximum height, the charging circle does not fully charge. 
It's always almost at the end/near the ground where i die from fall damage. Even if I manage to load it all the way, pressing 'use' takes too long/pressing doesn't work. Bug or am I stupid and don't know how to do it?

**Comment by Cryghast** [comment]
Yes，I have the same experience as you sad，but it‘s still actually possible to perform rainboom，but it will be too hard and not practical，in another word，rainboom skill is not useful anymore

**Comment by Mrufka69** [comment]
>rainboom skill is not useful anymore
yes.
