### ISSUE TITLE
Pegasus feather drop bug

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#383]
Sometime when I flying in the sky，I heard the feather drop sound，also there were subtitles for it，but the feather didn‘t drop，sometime it will drop，sometime it won’t drop

**Comment by EternaDash** [comment]
I've Been Dealing With That Too, I've Just Stopped Reacting To The Sound Altogether And Look Out For The Texture Of The Feather Briefly Popping Up Infront Of Me, Or The Painfully Loud Challenge Complete Sound (why are those advancements even *marked* as challenges?)

**Comment by ColdStoneSys** [comment]
i would also like to note that feathers sometimes drop without even making the sound
