### ISSUE TITLE
Suggestion：Rainboom visual effect and sound effect in multi player server

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#384]
In G4 episodes，the rainboom shockwave affect far and wide through the sky and other ponies on the ground can see it

Can we add a feature that：when a player perform rainboom，all the players in the same dimension would see a visual shockwave through the air and hear its sound？

**Comment by Sollace** [comment]
1. We already have an effect and sound
2. This would be very annoying if you have pegasi all over the server doing rainbooms.

**Comment by EternaDash** [comment]
> all the players in the same dimension would see a visual shockwave through the air and hear its sound？

I Don't Think It'd Be Particularly Enjoyable To Hear Sonic Rainbooms From Thousands Of Blocks Away Repeatedly, Ponies Farming The Wither Already Gets Annoying We Don't Need Something Like That But More Common.

**Comment by OakPlatinum** [comment]
How about making it configurable?
If you like that awesome global sound event, you can turn it on. If not, just turn it off.

**Comment by MimzyFang** [comment]
I have to agree with Sollace and EternaDash this would be mainly an annoyance
