### ISSUE TITLE
FirstAid Compatibility

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#385]
*Sending This Here Since MineLP Isn't Meant To Have Anything Besides The Ponified Models So Compat Should Probably Be Tied To Unicopia*

[FirstAid](https://modrinth.com/mod/firstaid) Is That Mod That Can Cripple Limbs And Crap, You Might Recognize It From RLCraft.
![image](https://github.com/Sollace/Unicopia/assets/153742870/7f481a20-4726-4cc2-8772-effb5236e309)
*(image taken from modrinth)*

I Feel Like Adding Compatibility For FirstAid Would Make For A More Immersive Experience And- Dropping Corporate Speak: Would Just Be Cool In General. Maybe If Without MineLP, It'd Only Make Changes If You Were A Pegasus, And Would Thus Allow For Your Wings To Be Crippled, Or As A Unicorn With Their Horn Maybe? And With MineLP Installed, It'd Work About As You'd Expect For A Pony.

Personally: I'd Just Like For A More Immersive Experience, Though Seeing How Long 1.3.7 Is Taking, Maybe Push This To 1.3.8 So This Doesn't Become Unicopia's 2.2 Update.

**Comment by Sollace** [comment]
Does First Aid add things visually to the player?
