### ISSUE TITLE
Support Serene Seasons

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#386]
[Serene Seasons](https://modrinth.com/mod/serene-seasons) is the seasons mod from the biomes o plenty team since 1.20.4 it's on Fabric and has since then a history of updating to new versions really quickly plus having more features then fabric seasons 
I would love to see some compatibility with unicopia crobs 

for infos on the features see here 
https://github.com/Glitchfiend/SereneSeasons/wiki
and the sourcecode is here https://github.com/Glitchfiend/SereneSeasons though it unfortunately is ARR

**Comment by Sollace** [comment]
Making a note:

https://github.com/Glitchfiend/SereneSeasons/tree/1.21/common/src/main/resources/data/sereneseasons/tags/block

Relevant tags are:
`sereneseasons:autumn_crops` (block+item)
`sereneseasons:winter_crops` (block+item)
`sereneseasons:spring_crops` (block+item)
`sereneseasons:summer_crops` (block+item)
`sereneseasons:unbreakable_infertile_crops` (block only)

**Comment by Sollace** [comment]
Since serene seasons doesn't do any block models/texture changing, the blocks will not change appearance. Also I have no way to control growth rates directly.

Doesn't seem like I need any code changes for this.

**Comment by MimzyFang** [comment]
so only setting tags

**Comment by Sollace** [comment]
> so only setting tags

Yeah. You can technically do it with a datapack, but it is convenient for me to add a few lines to datagen

**Comment by denisonchik35l** [comment]
здравствуйте, у нас на сервере установлен ваш мод только что у меня был конец весны ,а теперь снова начало что это может значить?
