### ISSUE TITLE
Pegasus hot air rise bug

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#393]
<img width="500" alt="image" src="https://github.com/Sollace/Unicopia/assets/131762804/8906e1ae-5231-4610-a5cc-83347a549df5">
If you fill underground with lava, cover with some blocks, then place water on the surface.(Like a sandwich )

When a pegasus fly above this sandwich structure, it will receive a very strong height boost, and hard to dive down.

But if you remove the water from it, then no height boost.

(I knew fly above lava can let you gain height, but this sandwich structure can do even way to more, I'm wondering if this is a feature or a bug?)

**Comment by Sollace** [comment]
Water gives you a boost depending on the time of day. It's already been changed for the next update to account for the depth, so I'm closing this as completed.
