### ISSUE TITLE
Bug：pegasus in flying situation can not shoot arrow correctly in server

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#394]
![未命名作品](https://github.com/Sollace/Unicopia/assets/131762804/4916171c-d8bc-4288-b545-aa0fdc241076)
Unicopia 1.3.6

**Comment by Sollace** [comment]
Test with minelp's fillycam option turned off. Unicopia on its own doesn't change anything other than your player's hitbox when you're flying.

**Comment by Cryghast** [comment]
> Test with minelp's fillycam option turned off. Unicopia on its own doesn't change anything other than your player's hitbox when you're flying.

 I tried，but the issue is still
