### ISSUE TITLE
Fortification Effect Doesn't Work As Expected When Applied With Commands

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#396]
If I Am Correct, Fortification Nullifies Knockback, And It Only Normally Is Applied When An Earth Pony Crouches.

What I Am Talking About Is When Commands Are Used To Apply The Effect Outside Of That Circumstance, Which Could Be Really Useful For Certain Things In Mapmaking Like Maybe For A Tank Class Which Should Be Immune To Knockback Or A Boss Mob That You Don't Want Being Cheesed. But As Of Now, You Must Be Crouched For Fortification To Function, Even If Commands Are Used To Give You The Effect.
So Since Knockback Res Isn't A Potion Effect, I Ask For Fortification To Work Even While Uncrouched If The Player *Did* Get The Effect Via Commands.

**Comment by Sollace** [comment]
As noted on the other story, I never intended fortification to be applied to other races.

The effect itself doesn't actually do anything, it is just an indicator for earth ponies to be able to see when they are fortified (activated by sneaking). Fortifying isn't a new feature in itself, just the status effect to show when it's present is.

Fortifying also has other effects than just nullifying knockback. It also reduces fall damage and makes you less easily pushed by shields if I remember correctly.

To allow it to work on other races as an effect given with a command I would probably have to make a separate status effect entirely, so may I suggest working this idea into something along those lines instead?
