### ISSUE TITLE
Changeling hive expose in air

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#398]
![2024-07-01_01 55 03](https://github.com/Sollace/Unicopia/assets/131762804/2b894fae-7538-4943-92d2-aa5a3cc3b5eb)

It shouldn't be  able to generated on mountains，otherwise it will easy expose on air

**Comment by Sollace** [comment]
Yeah I'm not super sure how to fix that. It's a problem that it has to generate with the mouth level to the ground and I could never figure out how to make it generate a neck based on elevation.
