### ISSUE TITLE
Batpony screen particle effect place is not right

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#399]
![2024-07-02_22 45 50](https://github.com/Sollace/Unicopia/assets/131762804/56f8ff45-3eb8-4772-bf93-ed34db7eaf5a)

It comes from above head

sorry the screenshot didn't catch that

**Comment by Cryghast** [comment]
If you play as human，the location is right

If you play as pony race，the location is wrong

**Comment by MimzyFang** [comment]
@Cryghast do you play with or without bigpony?

**Comment by Cryghast** [comment]
> @Cryghast do you play with or without bigpony?

Yes，but I haven’t change any settings of the bigpony
