### ISSUE TITLE
Ledger Compatibility

### ISSUE THREAD

**Issue by OakPlatinum** [Sollace/Unicopia#403]
[Legder](https://modrinth.com/mod/ledger/) is a serverside logging mod. But some actions in Unicopia like magic spells and earth ponies' kicks can't be recorded. It would be great if you considered adding the compatibility.

**Comment by Sollace** [comment]
I don't think this is really feasible for me to do.

**Comment by Sollace** [comment]
After looking into it, the way Ledger implements its events are not in a very compatible way at all. I'd be surprised if Unicopia is the only mod that they have problem with.

I suggest taking the issue to them as any logging should be done in `WorldChunk#setBlockState` or in `Block#onStateReplaced`, not... in the hundreds of other places they're injecting into instead.
