### ISSUE TITLE
Cling to Ceiling seemingly broken

### ISSUE THREAD

**Issue by Reznc** [Sollace/Unicopia#404]
I'm not sure if I'm doing something wrong when it comes to trying to cling to the ceiling but anytime I do it I'll turn upside down for a quick second before getting flipped around and I'm basically right back where I started.

**Comment by Cryghast** [comment]
Yes，I found that too

This ability are now not stable anymore

1.3.8

**Comment by Cryghast** [comment]
I have the same issue in server，this ability are now not stable
