### ISSUE TITLE
Polearms: A More Detailed Issue On The Weapon

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#408]
#355 Said Polearms Should Be Spears, Which Is More Just Asking For A Buff. Here's A Far More Detailed Issue On My Ideas For The Polearm.

1: Damage & Attack Speed
=

I've Been Using A Mod Called [CIA](https://modrinth.com/mod/cia), Or Custom Item Attributes If You're No Fun. With It, I've Been Playing With A Manually Buffed Polearm Which Attacks As Fast As An Axe To Make It Viable And Enjoyable To Fight With, And It Works Pretty Well As a Combat Option.
Either You Go Sword For Decent Spread Of Speed And Damage, An Axe For High Burst Damage, Or A Polearm For Attacking More Safely.
*really all we're missing is a rapid-fire weapon that isn't just your hoof.*
However, In My Playing, I Find It's Become *Too* Powerful To Just Leave At Being As Fast As An Axe, So Here's My Ideas To Make It Actually Fair.

1. Damage: Make The Polearm Do One Less Damage For Each Rarity, Meaning Wooden And Gold Does 2 Damage, Iron Does 4 Damage, And Netherite Does 6 Damage. It's As Shrimple As That.

2. Attack Speed: I Think Nerfing It To Be Just A Little Bit Slower Than The Axe Would Do Nicely. If I Diamond Axe Has An AS (attack speed) Of 1, Then a Diamond Polearm Should Have An AS Of 0.7, Fast Enough To Be Enjoyable To Use But Being Slow Enough To Pose A Genuine Downside. This Also Means The Iron Polearm Would Have An AS Of 0.6, And Wood/Stone At An Agonizing 0.5. To Fix This, Just.. Don't Change The Attack Speed Depending On Material, Just Stick To 0.7, Like How Swords Are At 1.6 Regardless Of Material.

2: Armour Penetration & Why Is There Sweeping?
=

Armour Penetration. The Polearm Ignores Up To 7 Points Of Armour, Or Full Leather Armour. Idea Taken From @drowsiestprince
![image](https://github.com/user-attachments/assets/17d0acdb-56d3-4b1e-985c-d47ce4d97f71)
Unlike Their Suggestion However, I Don't Believe There Should Be Any RNG Tied To It, That Feels Overly Complicated For A Long Stick With A Pointy End.

Next Is Why Is There Sweeping? It's Not A Sword. What I Think Is Happening Is That You Set It To Be A Sword And Left It At That, So It Can Get Sword Enchants But It Also Gets Sweeping, Which Is Kinda Weird. For Extra Balance, That Should Be Removed Since You Jab With The Polearm Rather Than Sweep With It Like A Sword.

3: Precision Enchantment & Pogo Enchantment
=

First Is The Precision Enchantment. The Enchantment Comes In Three Levels.
Precision I Gives An Extra 3 Armour Points Of Penetration
Precision II Gives An Extra 5 Armour Points Of Penetration
Precision III Gives An Extra 7 Armour Points Of Penetration
This Enchantment Would Be Exclusive To The Polearm.

Next Is The Pogo Enchantment, Which Comes In Two Levels.
Pogo I Launches The Player Back 2 Extra Blocks When Making A Hit In Close-Quarters
Pogo II Launches The Player Back 4 Extra Blocks When Making A Hit In Close-Quarters
This Enchantment Would Also Be Exclusive To The Polearm, And Is Incompatible With Knockback.
Note: Very Useful For Getting Away From A Surprise Creeper.

4: Enchantment Restrictions
=

Some Enchants I Believe Wouldn't Be Suited For The Polearm, Here They Are With My Reasoning.
1. Sharpness: Making A Weapon With Great Range Do More Damage Is Kinda Bonkers, And You Can Already Pierce Armour.
2. Fire Aspect: Imagine Being Lit Ablaze From Across A Canyon With No Way Of Retaliating, And With A Melee Of All Things!
3. Sweeping Edge: Since We'd Be Removing It's Sweeping Capabilities Anyways.
4. Bane Of Arthropods & Smite: Same As Sharpness, But Less Since Who Uses These Enchantments Outside Of Smite For Wither?

5: Appearance & Recipe
=

Some Ponies May Find The 3d Model Out-Of-Place Compared To The Other Vanilla Weapons Which Are All 2d, So Adding A Resource Pack That Disables The 2d Look Client-Side Would Be Nice.

Also, If I Recall Correctly, The Netherite Polearm Is Made Like Every Other Polearm Rather Than Needing A Netherite Smithing Template And Diamond Polearm At A Smithing Table. This Is Odd, So I Suggest Fixing That To Be In-Line With The Usual Crafting Recipe For Netherite Tier Items. (also applies to the horseshoe, which eats your netherite for no good reason)

6: End
=

:)

**Comment by Sollace** [comment]
Horseshoe recipes the way they are is intentional as they are made exclusively out of metals. There is no stone or diamond horseshoe, so no way to make it by smithing.

**Comment by Sollace** [comment]
You are correct about me setting it as a sword. In reality it's because the Polearm item extends the sword class, so it inherits a lot of the same behaviour. Not all of that I can change though.

**Comment by Sollace** [comment]
I don't think `Pogo` is the right name for that enchantment. Sounds like it's kind of doing the same thing as knockback does anyway?

**Comment by Sollace** [comment]
Same for `Precision` really. I'd probably just make it so the polearm can use Piercing and leave it at that.
