### ISSUE TITLE
Clam Shell Placed Wrongly

### ISSUE THREAD

**Issue by OakPlatinum** [Sollace/Unicopia#411]
You can't find a clam shell on a furnace, can you?
![Screenshot](https://github.com/user-attachments/assets/dfa4fb17-4bab-454a-b779-47341fa9a775)

**Comment by Sollace** [comment]
Why not? Shells can settle anywhere under water

**Comment by OakPlatinum** [comment]
Er, okay.

**Comment by MimzyFang** [comment]
> Er, okay.

As someone who is a hobby scuba diver I agree with Sollace if you are under water it's flora and fauna can end up everywhere even a sunken oven

**Comment by Sollace** [comment]
> As someone who is a hobby scuba diver

The lore deepens...
