### ISSUE TITLE
issues377 does not fixed properly

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#413]
It is more logical that you can prese V and set off from boat，rather than stuck in it

Also，if a flying pegasus rright click the boat，it will still have the weird look

Simply ban the take off ability when a player on boat can‘t solve this bug
![image](https://github.com/user-attachments/assets/015b712a-2a81-4cfd-910a-658a3c5a8c3c)

**Comment by MimzyFang** [comment]
Duplicate of #377

**Comment by MimzyFang** [comment]
@Cryghast I reopened the old issue the discussion can be continued there ^^

**Comment by Sollace** [comment]
Ah hm. I thought I had fixed this. :thinking:
