### ISSUE TITLE
Overhaul To Holding Things (yes im serious)

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#416]
Was Thinking How The Equestrian Military Would Function When I Remembered That: Hang On, How Would A Pony Even Hold A Weapon? So Now We're Here.

I Suggest A Rework Of Holding Items, With Seven New Slots: Two Hooves, Two Wings, Two Telekinesis, Mouth.
*note: this would also brutally murder the vanilla offhand slot. rip*

Hoof Slots Would Slow The Pony Down By 33% When Used, Unless Swimming Or Flying.

Wing Slots Would Disallow Flight When Used.

Telekinesis Slots Would Be Free Of Any Downsides.
*note: left for any would act as offhand, right for any would act as manehand*

The Mouth Slot Would Act Like The Offhand. It Would Also Not Have Any Downsides.

A Key Should Be Bound To Swap Between Which You Are Using (assuming you have them). I Propose Left And Right Arrows.
There Should Also Be A Key To Add An Item Selected Within The Hotbar To One Of These Slots, Or To Retrieve One From Them Without Using The Inventory. No Idea What To Use For This One.

**Comment by Sollace** [comment]
I... don't really want to mess with item holding.

It's just too complicated and I think players might be confused by it. Plus I can image how it will cause compatibility issues with other mods.
