### ISSUE TITLE
Crashing when Starting New World

### ISSUE THREAD

**Issue by PossibleHorse** [Sollace/Unicopia#42]
Hello! First I'd like to say that this mod looks absolutely amazing and I can't wait to get a chance to use it :)
The problem I'm having is that upon starting a new world my minecraft crashes. I can get all the way to selecting the settings for the world and starting to load it, but as soon as it reaches 100% it kicks me back to the launcher.
Below I've added my crash report and a list of the exact versions of mods that I am using.
Thanks! -Mo

[crash-2022-01-02_14.59.29-server.txt](https://github.com/Sollace/Unicopia/files/7799705/crash-2022-01-02_14.59.29-server.txt)

Mods in mod folder:
fabric-api-0.45.0+1.18
hdskins-6.5.0
minelittlepony-4.4.0
Unicopia-1.00-beta.13

**Comment by Sollace** [comment]
The mod is not updated to 1.18. For now you'll have to stick on 1.17 until I can get the next beta out (which should be fairly soon, it's a big update)

**Comment by PossibleHorse** [comment]
oooh shoot that makes sense. 
Thank you sm!
Very excited to see what you have planned :)
