### ISSUE TITLE
Keybind To Disable Bat Pony Night Vision

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#422]
Specifically For The Night Vision, You Still Get Blinded By The Sun Regardless Because Obviously.

I Ask For This Because It's Damn Impossible To Actually Tell What You Need To Light Up To Spawn-Proof Somewhere, And Thanks To The Night Vision F3 Won't Tell You.

**Comment by Sollace** [comment]
Disabling it defeats the purpose.
