### ISSUE TITLE
Grogar’s bell can‘t  suck a mob repeatedly

### ISSUE THREAD

**Issue by Cryghast** [Sollace/Unicopia#424]
Once a mob leave the grogar’s bell suck range，we couldn’t suck it any more

In other words，we can only suck a mob one time

But we can suck a player many times

This feature has been here for a while（Versions），Is that meant to be？

**Comment by Sollace** [comment]
Mobs have a finite amount of mana. Collecting it from them takes away some of their abilities and once it's done you can't take any more.

Players in contrast regenerate their mana, so you can continue collecting from them.

**Comment by Cryghast** [comment]
> Mobs have a finite amount of mana. Collecting it from them takes away some of their abilities and once it's done you can't take any more.
> 
> Players in contrast regenerate their mana, so you can continue collecting from them.

Is it right that zombie，skeleton and other mobs stop attacking the player once it out of the sucking range？

**Comment by Sollace** [comment]
> > Mobs have a finite amount of mana. Collecting it from them takes away some of their abilities and once it's done you can't take any more.
> > Players in contrast regenerate their mana, so you can continue collecting from them.
> 
> Is it right that zombie，skeleton and other mobs stop attacking the player once it out of the sucking range？

Yes. Once you've started sucking magic from them they lose their ability to attack and become passive.

**Comment by Cryghast** [comment]
> > > Mobs have a finite amount of mana. Collecting it from them takes away some of their abilities and once it's done you can't take any more.
> > > Players in contrast regenerate their mana, so you can continue collecting from them.
> > 
> > 
> > Is it right that zombie，skeleton and other mobs stop attacking the player once it out of the sucking range？
> 
> Yes. Once you've started sucking magic from them they lose their ability to attack and become passive.

I found drowned（mob）behave weird，bouncing on the surface of the water
