### ISSUE TITLE
Bat Ponies Are Bucking Invisible To Mobs In The Nether

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#425]
![image](https://github.com/user-attachments/assets/5510af89-0781-46be-8f51-f4bed596cdb8)
I Am Not Crouching, This Wither Skele Just Cannot See Me, I Have To Be On The Exact Same Block As It For It To Notice Me.
And If You're Crouching, They May As Well Be Neutral Mobs.

**Comment by Sollace** [comment]
This is intended but maybe could use some adjustment. Bat ponies are in general more sneaky and the amount of sneak depends on light level (maybe the nether is lacking sky light which could be the problem)
