### ISSUE TITLE
Villagers Attack Changelings [Suggestion]

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#427]
I think it'd be interesting if villagers and golems attacked undisguised changelings on sight, requiring the player to transform into a passive mob of some kind to trade with them or generally exist amongst their kind. I made a few suggestions about types of villagers in Mob Suggestions that might have unique interactions regarding this.

**Comment by EternaDash** [comment]
Maybe Not Villagers, They Should Run Instead Since They Never Really Attack Anything. But Golems, Yeah That Would Make Perfect Sense.
