### ISSUE TITLE
Metamorphosis Potions Softlock The Game

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#428]
![image](https://github.com/user-attachments/assets/76d611fb-ecb1-476c-aae2-452e4556e1f8)
Believe It Or Not, I Have Clicked Respawn And It Isn't Respawning. Not Ideal.

**Comment by Sollace** [comment]
What version are you using? This does not happen for me in 1.20.4

**Comment by Sollace** [comment]
I cannot reproduce this even in a dedicated server.
