### ISSUE TITLE
"You Can't Take It With You" Advancement Is Bugged

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#429]
With A Diamond Pickaxe And Enchanted Book With Consumption, When Combined At An Anvil I Did Not Get The Advancement As I Should Have For Enchanting It With Said Consumption Book.

**Comment by EternaDash** [comment]
Note: It Also Doesn't Work With Hearts Stronger Than Horses, I Enchanted My Pick With Heart Bound IV At An Anvil And Once More Nothing

**Comment by Sollace** [comment]
You only get the advancements when enchanting using the enchanting table.

**Comment by EternaDash** [comment]
> You only get the advancements when enchanting using the enchanting table.

Just A Note, But That's Kinda Jank To Keep It Like That

**Comment by Sollace** [comment]
> > You only get the advancements when enchanting using the enchanting table.
> 
> Just A Note, But That's Kinda Jank To Keep It Like That

Not something I can easily change as that is how Mojang has it set up and I'm focused on fixing bugs not adding new features. The "enchant item" predicate only triggers for the enchanting table and there is no equivalent one for the anvil.

You're better off filing it as a bug with Mojang as I agree the predicate really should trigger for enchanting using a book in the anvil.

**Comment by EternaDash** [comment]
> You're better off filing it as a bug with Mojang as I agree the predicate really should trigger for enchanting using a book in the anvil.

Oh It's A Mojang Issue
Didn't Know That
