### ISSUE TITLE
End Exploration Post-Dragon As A Flying Race Sucks

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#432]
I Can See Why You Lose So Much Mana When Going Over The Void, It's To Stop A Pony From Escaping The Centre Island Too Early. But I've Defeated The Ender Dragon And Got To The Outer Islands Normally, I Shouldn't Be Losing All My Mana In An Instant In That Case, It's Just Annoying.
Simple Fix: Disable The Insane Mana Drain When The Ender Dragon Is Defeated, It's Not Like A Pony Can't Get To The Outer Islands Afterwards Anyways.

**Comment by MimzyFang** [comment]
your half right this is indeed intended as a nerf though I don't think anything will change about that 
it also is not end related to my knowledge (@Sollace correct me if I am wrong) but instead based on if you are above void or not so it also affects skyblock

**Comment by Sollace** [comment]
It's not instant, it's just slightly faster. And yes it's based on whether you are above void so flying above islands is fine.

Short to medium flight is doable is you level up your stamina

**Comment by EternaDash** [comment]
> It's not instant, it's just slightly faster. And yes it's based on whether you are above void so flying above islands is fine.

Full Mana At Like 17 Last I Remember Gets Drained In 5-7 Seconds
