### ISSUE TITLE
Two Gamerules Relating To Picking Tribes

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#433]
1. Force Tribe On Join
`/gamerule ForceTribeOnJoin [<true/false>] [<tribe>]`
This Would Skip The Menu For Selecting A Tribe And Simply Force You Into The One Chosen. False By Default. Good For Map Makers.
Example: Let's Say We Have A Flight Course Map That We Want The Player To Be A Pegasus For.
`/gamerule ForceTribeOnJoin true pegasus`

2. Block Tribe Join
`/gamerule BlockTribeJoin [<true/false>] [<tribe>]`
This Would Grey Out The Blocked Tribes When Joining And Disallow Selecting Them. False By Default. Good For Map Makers Also.
Example: Let's Say You Don't Want An Earth Pony Because This Is Communism And We Can't Have That Going Well Can We?
`/gamerule BlockTribeJoin true earth`
In The Case Of Wanting To Also Block Changelings For Not Needing To Rely On The Broken System We're Making:
`/gamerule BlockTribeJoin true earth changeling`
*more practically for blocking tribes that can break the map like flying races skipping the everything*

More Map Making Tools, Yippee.

**Comment by MimzyFang** [comment]
all of this is already possible with the unicopia sub command for example
```
unicopia worldtribe set unicopia:pegasus
```
enforces everyone to use pegasus
and you can disable tribes with for example
```
unicopia racelist disallow unicopia:changeling
```
though these apply to the config so you need to provide that config with the world


@Sollace could you make it so that those commands affect the world and not the config as that would make more sense

**Comment by Sollace** [comment]
> all of this is already possible with the unicopia sub command for example
> 
> ```
> unicopia worldtribe set unicopia:pegasus
> ```
> 
> enforces everyone to use pegasus and you can disable tribes with for example
> 
> ```
> unicopia racelist disallow unicopia:changeling
> ```
> 
> though these apply to the config so you need to provide that config with the world
> 
> @Sollace could you make it so that those commands affect the world and not the config as that would make more sense

The racelist is meant to work like the regular server whitelist, so it's not part of the world.

**Comment by Sollace** [comment]
Closing to reduce the clutter as both of these are already possible with existing commands.
