### ISSUE TITLE
Change Tribe Commands Not Requiring Cheats To Use

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#438]
![image](https://github.com/user-attachments/assets/bf7911b6-7260-4e3c-b145-6c9c1d0e8af8)
I'm Gonna Be Honest, Part Of Me Didn't Want To Report This Because I Really Want A Way To See Light Properly As Bat Pony For Builds, But Ultimately It Is Clearly A Bug Seeing Metamorphosis Potions Are The Intended Way Of Doing This.

**Comment by Sollace** [comment]
The command requires op when in a multiplayer world. In singleplayer it does not and this is intentional.

If you have a singleplayer world with commands enabled you can still use the tribe command to change races.

**Comment by EternaDash** [comment]
> If you have a singleplayer world with commands enabled you can still use the tribe command to change races.

You Know What? Thank You. I Actually Have A Way To See Light Properly When Building, So That's Cool
