### ISSUE TITLE
Spanish Translation for the HOW_TO_PLAY.md file

### ISSUE THREAD

**Issue by Julielinas-github** [Sollace/Unicopia#439]
I saw the HOW_TO_PLAY file was missing a spanish translation, so I decided to make my own! I followed the formatting of the english file, please let me know if anything needs to be changed.

raw text file:

[HOW_TO_PLAY_ES.txt](https://github.com/user-attachments/files/16632552/HOW_TO_PLAY_ES.txt)

.md file pfp link:

https://github.com/Julielinas-github/HOW_TO_PLAY_ES/blob/34c8e30fd0c99f85898f0ce674660724a0faa869/HOW_TO_PLAY_ES.md

**Comment by Julielinas-github** [comment]
I also created a spanish translation for the README:

.md file pfp link:

https://github.com/Julielinas-github/README.md/blob/0d2c73b6386a1dfc3f93b333b946f43f744322a4/README_ES.md

**Comment by Sollace** [comment]
I recommend making a pull request with the files. Then I can just merge it to add them
