### ISSUE TITLE
Tree Downer - Earth Pony Ability [Suggestion]

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#442]
An ability that works similarly to Tree Harvester mods, earth ponies can use their buck ability multiple times in quick succession to down an entire tree at once instead of simply harvesting fruit from it. When the player does have a Tree Harvester mod installed, it quickens the amount of time taken to down the tree instead.

Perhaps the time taken to down the tree can decrease with increased leveling? Can receive the advancement "Debbie Tree Downer" from downing your first or instead perhaps a significant portion of trees with this ability. Could be in a larger advancement tree (haha) pertaining to orchard care upon the implementation of the system I suggested in #339

**Comment by Sollace** [comment]
Earth Ponies can already do this by kicking trees multiple times.
