### ISSUE TITLE
Increased Jump Height for Earth Ponies [Suggestion]

### ISSUE THREAD

**Issue by PrinceDrowsy** [Sollace/Unicopia#444]
I believe it'd be fun for earth ponies to have an increased jump height that functions similarly to how jumping works for riding a horse, in that you can hold down the spacebar to get extra airtime. The height could increase similarly statistically to horses as well, but you obtain the higher jump by leveling up rather than through selective breeding.

Could have an advancement for maxing out your jump height? Could be in a greater advancement tree themed after the show's rodeo adventures, such as utilization of the lasso from #275, horse shoe tosses, and perhaps other trick jumps along the lines of over fences and barrels. "Over a Barrel" could be a particularly funny one to reference the show.

**Comment by EternaDash** [comment]
I've Played With RPG Stat Mods, Having Higher Jump Height At All Times Would Be Agony, And Having To Hold To Jump Just Adds Input Delay To The Most Basic Game Feature Which Isn't Ideal
If This Was Attached To An Ability However, I'd Have No Complaints To Make
