### ISSUE TITLE
Lighting problems when using shaders.

### ISSUE THREAD

**Issue by ghost** [Sollace/Unicopia#445]
Having some issues with lighting when using shaders.
These first two images show the game without Unicopia in the game.
![2024-08-20_04 53 30](https://github.com/user-attachments/assets/65d781be-4ac3-41db-9c10-4ab7a9f6af11)
![2024-08-20_04 51 52](https://github.com/user-attachments/assets/065178a1-2031-4853-8cf5-44e2c8eca65f)

These two images are how the game looks with the mod in the game.
![2024-08-20_04 50 25](https://github.com/user-attachments/assets/7c4f9013-2a37-40ce-8a01-b24c5d811c6b)
![2024-08-20_04 50 45](https://github.com/user-attachments/assets/2b2bb102-f466-46dc-8933-01ef4a3bfc48)

The game both without and with Unicopia + no shaders.
![2024-08-20_05 04 40](https://github.com/user-attachments/assets/01bd7446-7f3b-4a54-a2ca-10c84ec37645)
![2024-08-20_05 06 23](https://github.com/user-attachments/assets/b93c86d3-fcd4-48ba-8021-c7ce175054fe)

I'm using Iris shaders along with sodium and indium.
The shader I am using in the screenshots is Astralex.

**Comment by Sollace** [comment]
Can you provide a link to the shaders?

I've tried the AstraLex shaders from [here](https://modrinth.com/shader/astralex/versions) both for 1.20.4 and neither of them load.

```
[20:47:51][m [32m[Render thread/INFO][m [36m(Minecraft)[m [0m[System] [CHAT] The shaderpack failed to load! Please report the error to the shader developer. Copy Info
[m[34m[20:47:51][m [31m[Render thread/ERROR][m [36m(Iris)[m [31mFailed to create shader rendering pipeline, disabling shaders!
[m net.irisshaders.iris.gl.shader.ShaderCompileException: moving_block.fsh: moving_block.fsh: 0:1076(6): error: syntax error, unexpected SAMPLE, expecting ',' or ';'
```

**Comment by MimzyFang** [comment]
Try [BSL](https://modrinth.com/shader/bsl-shaders) that's the one Olenian is using as far as I know

**Comment by Sollace** [comment]
> Try [BSL](https://modrinth.com/shader/bsl-shaders) that's the one Olenian is using as far as I know

BSL in the daytime
![image](https://github.com/user-attachments/assets/5fd0dcd5-4b54-4e0e-bc51-c3603585f850)

BSL in the nighttime
![image](https://github.com/user-attachments/assets/2f666398-a4f1-4ba5-92c7-cac5b5d3da21)

**Comment by Sollace** [comment]
Sorry, I had night vision on, lol

Again without night vision

Day:
![image](https://github.com/user-attachments/assets/661ec51d-f9da-4f61-b774-99fc53565c3a)

Night:
![image](https://github.com/user-attachments/assets/1fc81ed8-c82a-41c5-9549-00e1145f716c)

**Comment by Sollace** [comment]
BSL is working fine and there's nothing specifically I do that would mess with shader lighting in particular unless the shaders are really badly designed, so I'm going to close this.

You can open it again if you encounter other shaders that have this problem after the next update.
