### ISSUE TITLE
Use 3b biomes for clouds instead of structures

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#446]
Use 3d biomes with skyland generation instead of structures for clouds and instead have structures generate on those clouds

**Comment by EternaDash** [comment]
The Idea Of A Sky Village Automatically Makes Me Love This Idea

**Comment by Sollace** [comment]
I can't really figure out how I'd do this. You need to set the noise settings for the biome but there's not way to do that?

And I don't know how to make a noise setting that would generate convincing clouds. If anyone can, here's a tool for doing it:

https://misode.github.io/worldgen/noise-settings/

**Comment by Sollace** [comment]
Not really using a biome, but I've set up a carver to generate clouds so this can be closed.
