### ISSUE TITLE
Make Pillagers Drop Carapaces

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#447]
Carapaces And Chitin Are Agonizingly Luck-Based To Find. Either You Spawn Near A Hive, Or Have To Travel 10,000 Blocks To Find One On The Surface, Not Fun. Easy Fix: Make Pillagers Drop Carapaces.
Reasoning Is Simple: In MineLP, They're Changelings. Of Course They're Gonna Drop That Stuff. Also Makes Farming The Stuff Less Mind-Numbing.

If You Don't Like That Idea, You Could Theoretically Just Make Any Changeling Player Drop Carapaces When They Die, But Then We Run Into A Rainbow Factory Situation Where The Optimal Farm Is Making A Spawn Trap So I Can Understand Not Doing That.

**Comment by Sollace** [comment]
Pillagers being changelings is a mine little pony aesthetic thing so I'm not going to do this.

When changelings are added they will drop carapaces and chitin however.
