### ISSUE TITLE
Containers broken by Earth Pony Crushing Blow does not drop its contents

### ISSUE THREAD

**Issue by ColdStoneSys** [Sollace/Unicopia#448]
The crushing blow skill can break containers like barrels and chests and the block will break but the block, but its contents will be lost.

This seems to happen when a mob/player is killed by the attack 

(Found this out the unfortunate way)

**Comment by EternaDash** [comment]
That Can Break Stuff?

**Comment by Sollace** [comment]
> That Can Break Stuff?

Yeah. Everything that increases block digging percentage can break the blocks if used multiple times.

**Comment by Sollace** [comment]
Are you sure you're using crushing blow? Because from my testing that only breaks trees (wood and leaves)

**Comment by Sollace** [comment]
Nevermind. It's the dash ability, not the kick ability.
