### ISSUE TITLE
Limit AOE spell size

### ISSUE THREAD

**Issue by ColdStoneSys** [Sollace/Unicopia#450]
I was playing around with spells and I managed to create a Frost gem that spanned over 100 blocks wide. I think doing this on a server could have negative effects on performance especially if someone is intentionally spamming such spells.

Maybe its unrealistic for it to happen through normal game-play, but it does exist and I think it is a potential issue.

![image](https://github.com/user-attachments/assets/c383065d-bf8a-416a-b48a-dd67e92c95cb)

**Comment by OakPlatinum** [comment]
Same. I once cast a spell like this, and it caused much lagging, even crashing the server. Should have a configurable range limit.

**Comment by EternaDash** [comment]
I Think A Server-Sided Config Limit Is The Best Solution, Since If You *Really* Wanna Have Comically Large Spells, You Can In Singleplayer Or Your Server. Maybe Just Add A Comment In The Config That Mentions How Insanely Large Spells Could Tank Preformance.
