### ISSUE TITLE
Multiple spellbooks can be placed in 1 block.

### ISSUE THREAD

**Issue by NyxDerg** [Sollace/Unicopia#451]
If you place a wall behind a block, and click that wall over and over in Creative mode, you will add infinitely many spellbooks in that same block. This has an unintended side-effect of adding each block's slight pushing force into an insanely powerful pushing force.

![2024-09-04_08 27 51](https://github.com/user-attachments/assets/5e054764-7d5f-4d46-bb57-554baf67c19d)

**Comment by Sollace** [comment]
Minecart physics

**Comment by EternaDash** [comment]
Spellbook Powered Entity Railgun (Sper)
Twilight Would Be Proud
