### ISSUE TITLE
Server Crashes Due to Tribe Change

### ISSUE THREAD

**Issue by ColdStoneSys** [Sollace/Unicopia#453]
Drank a potion of pegasus metamorphosis as a kirin and when i died the server crashed and when i rejoined the server locked up and crashed again. 

Report is attached.
[crash-2024-09-14_21.56.45-server.txt](https://github.com/user-attachments/files/17004344/crash-2024-09-14_21.56.45-server.txt)

**Comment by Sollace** [comment]
The error in this case looks like the server tick took too long. Do you have the logs for the first crash?

**Comment by Sollace** [comment]
Cannot reproduce

**Comment by ColdStoneSys** [comment]
> The error in this case looks like the server tick took too long. Do you have the logs for the first crash?

Apologies for my delay in response.

This is the first crash. the second crash report was identical. No idea what caused this other than the above.

**Comment by Sollace** [comment]
> > The error in this case looks like the server tick took too long. Do you have the logs for the first crash?
> 
> Apologies for my delay in response.
> 
> This is the first crash. the second crash report was identical. No idea what caused this other than the above.

Sorry, I don't know what the cause is then. It could be a mod conflict as I see a mixin method I don't recognise in `redirect$zdc000$apoli$preventArmorDamaging`.

Were you wearing any modded armour when this happened?

**Comment by ColdStoneSys** [comment]
I was wearing normal netherite armor and my chestplate had padded III if that matters at all. I'd have to check my mod list for anything that might stand out.

**Comment by ColdStoneSys** [comment]
the mixin appears to be part of the origins mod (dont ask me why i have origins and unicopia, it wasnt my decision).
