### ISSUE TITLE
Instruments (add them they're cool)

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#459]
Hm It Appears I Have Absolutely Nothing Better To Do, So I Could Either Finally Get Around To Watching More Of Friendship Is Magic, Or Write An Issue That Can Wait Anyways.
Hmmmmmmm..

Welcome To Episode Three Of Ripping Apart The Corpse Of #397 Because Unlike Valve I *Can* Count To Three.
*that is going to age so poorly if the next half-life game is half-life 3*
This Issue I'm Bringing The Idea Of Instruments, A Wonderful Roleplay Tool That You Can Use To Absolutely Annoy The Crap Out Of Your Friends Or Deal With Parasprites If And When They Are Added.

Instruments I Actually Remember Exists
-

Cello: Listen, My Favourite Pony Is A Cellist (octavia) So This Was Obviously The First Instrument I Was Going To Mention.

Piano: All I'm Saying is That Classical Is Still Really Good, And Piano Is Possibly My Favourite Classical Instrument. Also Would Really Like If It Had Gravity And Could Crush Ponies Underneath It So I Can Recreate That One ASDF Skit.

Saxophone: Jazz Is Underrated, I Rest My Case.

Whatever The Hell Vinyl Uses: I'm Not Sure What To Call That.. Thing She Uses, Feel Free To Call Me Stupid, But If I'm Mentioning The Cello Because Of Octavia It's Only Fair I Also Bring Her Roommate Here Too.

Guitar, Violin, And Trumpet: I Don't Have Anything To Say About These So Here They Are Clumped Together.

Just.. Assume Every Other Instrument That Matters Is Here Too Because I Sure As Hell Don't Remember Them.

End
-

This Was A Decently Short One.
No I Will Not Make That Joke.

**Comment by OakPlatinum** [comment]
Actually, [a lot of mods](https://modrinth.com/mods?q=instrument) have already did it, and I prefer [More Colorful](https://modrinth.com/mod/morecolorful).
I think these features should be in a seperated mod, or at least an addon.

> ... Deal With Parasprites If And When They Are Added...

Great idea.

<br/>
<hr/>

_btw, @EternaDash that's called a [DJ controller](https://en.m.wikipedia.org/wiki/DJ_controller), with two [turntables](https://en.m.wikipedia.org/wiki/Phonograph), some [DJ mixers](https://en.m.wikipedia.org/wiki/DJ_mixer) and whatever else on it. Visit [this](https://en.m.wikipedia.org/wiki/Disc_jockey) for details._

**Comment by EternaDash** [comment]
> that's called a DJ controller, with two turntables, some DJ mixers and whatever else on it.

Thank You Very Cool

**Comment by Sollace** [comment]
I don't intend on adding musical instruments. I agree with @OakPlatinum that it's something that works better as a separate mod and I don't want to take away from the vanilla mechanic of using note blocks and redstone constructions to make machines to play music. To me that's more interesting than just adding a piano.
