### ISSUE TITLE
Let Earth Ponies Eat Gemstones

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#460]
Episode Four Of Ripping Apart #397's Corpse, Real Small One:
![image](https://github.com/user-attachments/assets/340e6f7b-45cb-4e3e-a314-cd7188fd700d)
I Want To Be Able To Waste My Diamonds Like A True Aristocrat: Consuming Them.
![pony-town-Aristocratic Applejack-stand-blinking-padded-1x](https://github.com/user-attachments/assets/4deb74d7-020b-4436-8125-0ffc2c1060e8)

**Comment by Sollace** [comment]
Okay fair, since the spellbook technically says earth ponies can, I'll make it so
