### ISSUE TITLE
Let Ponies Interact With Clouds Blocks In Creative Mode

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#461]
Named The Pickaxe I Used In #458 This As A Joke, But Honestly Should Be It's Own Issue.
![image](https://github.com/user-attachments/assets/2e5d2f1d-3296-44c1-8186-16e606ca06e8)
Seriously, Why Can't I Place And Break Cloud Blocks In Creative As A Non-Pegasus? I'm In Creative, Does It Really Matter?
All It Does Is Makes Me Have To Switch To Pegasus While Building Which- I Literally *Am* A Pegasus But I Don't *Play* As One Always. And I Don't Want Other Ponies To Have To Switch Back And Forth Either, It's Annoying.

**Comment by Sollace** [comment]
Sure. This was a feature before that got forgotten in the reimplementation
