### ISSUE TITLE
Changeling Hivemind Chat (I Guess?)

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#463]
Episode Six Of Ripping Apart #397's Corpse, Starting To Regret Making That What I Call This But Oh Well Can't Stop Won't Stop.

Changelings Are A Hivemind. I've Said This Literally Last Issue. Thus It Makes Sense They'd Have A Hivemind Chat...

...Yeah I'm Gonna Be Honest, This Is The Weakest Of The Ideas I'm Taking From #397, Since You Can Just Make A Server Plugin.
Eh, Might As Well Take It Off The List Of Ideas I *Can* Suggest.

**Comment by Sollace** [comment]
Not easily possible with how the minecraft chat works
