### ISSUE TITLE
Changelings Being Weak To Fire

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#464]
just gonna clear off the last changeling-related thing on the list i care about
Welcome To Episode Seven Of Ripping Apart #397's Corpse.

I've Mentioned This In Past Issues, But I Don't Actually Know If Sollace Likes The Idea So Here's An Issue For It For You.
*if you already told me what you think, feel free to call me an idiot for forgetting.*

Changelings Are, From What I Know, Insects. Insects Tend To React Poorly To Fire, At Least That's What The Pokémon Logic In Me Is Saying. So To Me At Least It Just Feels Right They'd Be Weak To Fire?
I'd Say A 2x Damage Multiplier When Taking Fire Damage Since There Really Isn't Many Ways To Take Fire Damage As It Is, And The Only Enemy Able To Do It Consistently, Blazes, Are Hard-Countered By Snowballs And Fire Resistance Potions, And Are Overall Pushovers With A Shield And Axe.

**Comment by Sollace** [comment]
Pokemon logic doesn't apply to pony changelings. I don't really think we should be making fire more deadly than it already is. Players as changelings already have a hard time as it is.

**Comment by EternaDash** [comment]
> Pokemon logic doesn't apply to pony changelings. I don't really think we should be making fire more deadly than it already is. Players as changelings already have a hard time as it is.

Fair
