### ISSUE TITLE
Gamerule For Pegasi Dropping Their Feathers On Death

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#465]
yeah the recent issues of 397 are me giving the weaker of the ideas, they might be good idk.
Welcome To Episode Eight Of Ripping Apart #397's Corpse, I Have Completely Ran Out Of Jokes For That.

The Idea Is Shrimple: Pegasi Drop Their Feathers When They Bite The Dust.
When A Pegasus Is Ripped Asunder, Hacked Apart, Or Hears Their Past Voice, They Drop 0-1 Pegasi Feathers On Death.
Should Be Gamerule Off By Default To Avoid The Imminent Re-Enactment Of The Rainbow Factory On Your Local Survival Server.
*could also add a delay between deaths and allowing for the pegasus feather to drop to further prevent that outcome.*

Justification?
-
I Only Have One Really, But It's Not Half-Bad: PVP-Enabled Servers.
With The #367 Changes To Pegasi Feathers I've Suggested, Maybe A Dedicated PVP Server Could Have The Gamerule On, And Allow For Crafting The Unique Gear With It. And For Anarchy Or Faction Servers, The Same Applies, Just On A Bigger Map.
*i mean, 60000000x60000000 is at least slightly bigger than a pvp map of, like, 100x100.*

**Comment by Sollace** [comment]
I'm not a fan of players dropping loot that isn't from their inventory. Pegasus feathers are only supposed to drop from pegasi during flight as a natural consequence of shedding. For everything else, anything that takes a pegasus feather should also accept a griffon feather which naturally generates in chests.
