### ISSUE TITLE
Make Humans A Selectable Tribe Without Cheats

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#466]
Episode Nine Of Ripping Apart #397's Corpse, Definitely My Last Issue For Tonight Since I Want 10 To Be Real Good.

Humans Are.. Definitely A Thing. *idk can somepony fact check that?* They're Definitely One Of The Races Of All Times, No Ups Or Downs, Literally Just Vanilla Minecraft. But That Kinda Makes Them Obsolete. Earth Ponies Are The Bread Basket Of A Group And Great Warriors, Pegasi Are Excellent Explorers And Miners For Some Reason, Unicorns Are... Changelings Are Incredibly Self-Reliant With Sapping Love, Bat Ponies Work In The Night And Dark While Others Stay In The Light, And I Don't Play Hippogriffons Or Kirin So I Can't Comment On Them. But Humans? What Can They Do? They're A Full 2 Blocks Tall Which Is More Of A Hinderance, They Can't Eat Seeds Or Leaves Or Hay For Infinite Food, They Can't Fly Or Teleport Or Grow Food Rapidly Without Bonemeal. They're Mid.
However, It's Inevitable Somepony Is Going To Want To Play As A Human. In The Mod All About Not Doing That. For.. Some Reason. *maybe roleplay?* But They Exist As A Tribe, And One Inaccessible For An Equally Inexplainable Reason. So, For The Sake Of *Having* The Option, There Should Be A Button To Play As A Human. Maybe Rename It As A Minecrafter So They Have ***Something*** Going For Them: An Interesting Name.

This Would Be The Weakest Suggestion I've Given But #463 Exists So Second Weakest.

**Comment by PrinceDrowsy** [comment]
Human as an option to select would be fun for my non-pony friends <3 It's also a funny little gen 1 reference! As well as just being a viable vanilla option. On a larger server there are definitely going to be some people who just want to play vanilla Minecraft.

**Comment by EternaDash** [comment]
> Human as an option to select would be fun for my non-pony friends <3 

*Oh* I Completely Forgot About Ponies Playing With Non-Pony Friends Lol
