### ISSUE TITLE
[BUG] Alicorn Amulet - Enemy multiplication effect

### ISSUE THREAD

**Issue by RomaTomatoPlant** [Sollace/Unicopia#467]
When the Alicorn Amulet is worn for extended periods it causes enemies overtime to split when you punch them, if its 3 witches for example cleaved all 3. and they all split into 2 each, the next swing. 6 > 12 >24 ect you get it -- This being able to happen so fast makes servers become insanely laggy when within a minute you can spawn in almost 50 entities 

It happens worse with flaming entities, every flame damage tick more and more enemies will spawn (i.e Zombies exploding into an infinite zomb army during the day) 

Its gotten so bad to the point where the Alicorn Amulet is permanently turned off for players on our server due to this bug crashing the server so fast -- But a few players on our server would like to rp with the amulet and cant

--

Ideally there should potentially be a cap on how many times the entities can split perhaps? or maybe a gamerule to disable / set a cap maybe? 

--

Wear it for a long period of time and then try to fight enemies when you're in deep corruption

Version 1.20.1 - Unicopia 1.3.8

**Comment by EternaDash** [comment]
Mitosis

**Comment by Sollace** [comment]
Mitosis is an intended side-effect of players wearing the amulet for too long. I have toned it down to happen less often.
