### ISSUE TITLE
Allow Mobs To Use Racial Abilities

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#468]
Episode 10 Of Ripping Apart #397's Corpse, We Are At Double Digits!
*this may be a lot*

Concept
-
The Idea Is... Easy To Comprehend (there i didn't say simple again)
With MineLP Installed, Each Ponified Mob Are A Different Pony Race. This Has Given Me The Idea Of Mobs Being Able To Use Their Racial Abilities.
Mobs Should Be Given Pony Features Similarly To How Players Do If MineLP Isn't Installed.

Difficulty Variations
-
If Every Single Zompony And Skeleton Could Use Their Racial Abilities, That Would Probably End Very, Very Poorly. So I Say Difficulty Affects The Probability For A Mob To Be Able To Use Their Racial Abilities.

Easy: 1% Per Mob
Normal: 2% Per Mob
Hard: 5% Per Mob

New Gamerule
-
DoMobsUseRacialAbilities, On By Default, Controls If Mobs Spawned Rolls For A Chance To Use Their Racial Abilities. Mobs Already Spawned Able To Use Their Abilities Will Not Change If Disabled.

Zompony/Husk
-
Earth Zompony
Ability: Ground Pound
An Earth Zompony Would Have The Ability To Use Ground Pound With A Similar Range As To A Regular Earth Pony. Unlike A Regular Ground Pound, It Does Not Deal Damage To Other Zomponies (however other hostile mobs are fair game). It Also Does Not Break Blocks, We Don't Need Another Creeper. Lastly, It Does Four Damage, Or Two Hearts, Because Otherwise It Wouldn't Really Matter.

Pegasus
Ability: Flight
A Zompony Pegasus Would Have The Ability To Actually Use Those Things Strapped To It's Back 24/7: It's Wings. If The Zompony Is 20 Blocks Or More Away *Or* Are Unable To Reach Their Target, They Initiate Flight. In The First Case, The Zompony Will Stop Flying At A Safe Spot (so not on lava) When 5 Blocks Away From Their Target. In The Second Case, They Fly To The Closest Spot That Will Allow Them To Pathfind And Attack Their Target, Ideally Further Than 4 Blocks But If Necessary It Will Fly Closer To Or Into Their Target. They Will Not Fly When It Is Raining And They Are Outside.

Unicorn
Ability: Necromancy
A Zompony Unicorn Would Have The Ability To Cast An Alternate Version Of Necromancy. When Within 10 Blocks Of A Target, They Will Cast Necromancy And- After 3 Seconds, Summon 5 Random Undead Mobs. That Is, Zomponies, Skeletons, Husks, Strays, And Wither Skeletons If They Happen To Be In The Nether. They May Only Do This Once, And Monsters They Spawn Cannot Use Their Racial Abilites To Prevent A Possible Infinite Cascade Of Unicorn Zomponies.
Note: Vexes Are Not Classified As Undead, Please For The Love Of Celestia Don't Let Unicorn Zomponies Spawn Them.
![image](https://github.com/user-attachments/assets/22103366-a718-401c-92b6-184b2c661d69)

Skeleton
-
Unicorn
Ability: Teleport
The Skeleton Would Have The Ability To Teleport. If Their Target Gets Out Of Reach But Is Less Than 20 Blocks Away, For Example By Using A Door, The Skeleton Will Teleport To A Free Space Where They Can Continue Attacking. They Will Also Teleport To A Random Spot Around Their Target Occasionally To Disorient Them And Will Teleport To Dodge Incoming Projectiles.

Wither Skeleton
-
Unicorn
Ability: Fire Bolt
I Have Elected To *Not* Give Wither Skeletons The Ability To Teleport Because That Would Be Bucking Terrifying. Instead, They Get Fire Bolt. If Their Target Is Further Than 5 Blocks Or Is Inaccessible Thanks To A Height Difference Or Gap, They Will Attempt To Hit Them With A Fire Bolt Which They Can Fire Once Every 5 Seconds.

Endermare
-
Unicorn
Ability: Arcane Protection
Endermares Would Have The Ability To Cast Arcane Protection. When Nearby A Target Who Is Able To Cast Spells, As In A Unicorn Or Alicorn, They Will Cast Arcane Protection To.. Uh.. Arcane Protection Doesn't Work For Me. I Assume It Creates A Magic Deadzone? I'm Just Guessing Here.

Alicorn
Ability: Also Arcane Protection
I Am Not Even Going To Try To Suggest Giving Endermares The Power To Move The Sun And Moon. maybe as 2025's april fools?

Pillager
-
Changeling
Ability: N/A
Sollace Seems To Have Their Own Idea On How Changelings As A Mob Will Work So I'll Leave This To Her.
![image](https://github.com/user-attachments/assets/d7474f34-8350-4aa0-89a4-2b19b51ecbe8)

Vindicator
-
Pegasus (oh no)
Ability: Flight
Oh God They're Pegasi. And As A Pegasus, A Vindicator Would Be Able To Fly.
A Walking 19.5 Damage Dispenser Now Has Flight, **It's Time To Bucking Run.**
This Would Work The Same As Flight For A Zompony Pegasus, And So This Doesn't Immediately Result In Catastrophe, For Vindicators Specifically They Have Only A 0.25% Chance Per Spawn To Use Their Ability On Normal, 0.5% On Hard, And They Just Can't On Easy.

Evoker
-
Unicorn
Ability: Teleportation
Nothing New Here So Just Take What I Said About The Skeleton. Evokers Are OP Enough With Their Vexes Which Deal WAY TOO MUCH DAMAGE So I'd Rather Not Make Them Worse.

Illusioner
-
Unicorn
Ability: Displacement
Yes I Remembered Illusioners Exist. When Their Target Is In An Area That Won't Put Them In A Worse Position, Like Somewhere They'd Be Unable To Reach Their Target, They May Cast Displacement And Swap Places With Their Target To Disorient Them. If The Illusioner Is Surrounded By Other Hostile Mobs, They Will Also Cast Displacement To Swap Places With Their Target And Plunge Them Into Their Allies.

End
-
Running Out Of Ideas And Honestly I'd Rather Not Even Mention The Fact Pegasus Piglin Brutes Exists Because Another Walking 19.5 Damage Dispenser Being Able To Fly Is Just Too Much.

**Comment by Sollace** [comment]
This is both hard to do and not really something I would want.
