### ISSUE TITLE
Game crash upon loading world, received a NullPointerException from crash report. 

### ISSUE THREAD

**Issue by Richfly01** [Sollace/Unicopia#471]
**Describe the bug**
Game crashes whenever loading a world with any version of Unicopia higher than 1.3.0 (For MC 1.20.1)

**Expected behavior**
The mod should work, as the 1.3.0 version does work with Sinytra. Game also runs fine without Unicopia. 
(unsure about any older versions, 1.3.0 is just the latest that works)

**Steps to reproduce**
Load any version of Unicopia higher than 1.3.0 on MC version 1.20.1, Forge version  47.3.10, and Sinytra connector version 1.0.0.beta 45 (newest), then create or load up a world, if you get the bug, you would see the loading screen with "Reading World Data" for about 10 - 20 seconds before game crashes back the the launcher with "Error: java.lang.NullPointerException: Starting integrated server" and exit code -1. 

**Version Information:**
 - Minecraft Version: 1.20.1 

 - Mine Little Pony Version: 4.11.7, 1.20.1

**Mod Loader:**
Forge 47.3.10 (with connector)
Siyntra Connector 1.0.0.beta 45

**Client/Server Logs**
Latest Crash Report
[crash-2024-09-25_03.02.06-client.txt](https://github.com/user-attachments/files/17129211/crash-2024-09-25_03.02.06-client.txt)

Latest log on Unicopia version 1.3.8. (All other versions have practically identical logs, 1.3.0 is the newest that works)
[2024-09-25-7.txt](https://github.com/user-attachments/files/17129421/2024-09-25-7.txt)

(*Unrelated note, Unicopia alters the Minimum Light Levels of Shaders*)

**Comment by Sollace** [comment]
You should preferrably report this to the Synatra Connector team. It's either a problem with connector or with Forge.

https://github.com/Sinytra/Connector/issues.

You also appear to be using LexForge which is not properly supported by Connector, so please test with NeoForge before reporting it.
