### ISSUE TITLE
[BUG] Ballon doesnt work?

### ISSUE THREAD

**Issue by Mrufka69** [Sollace/Unicopia#473]
**Describe the bug**
Ballon doesn't work. 

**Expected behavior**
it works. 

**Screenshots**

![obraz_2024-09-26_202212841](https://github.com/user-attachments/assets/35b3debd-a4f1-4feb-b832-86f3eda229c6)

**Version Information:**
 - Minecraft Version: 1.20.4
 - Mine Little Pony Version: 1.20.4

**Mod Loader:**
 - Fabric

**Comment by Sollace** [comment]
It's not inflated. You need to inflate it.

Add fuel and turn it on so it inflates. It will start flyinh when it's fully inflated.

**Comment by Mrufka69** [comment]
How do i do that? It just eats fuel and does nothing :C

**Comment by Sollace** [comment]
> How do i do that? It just eats fuel and does nothing :C

You will have to get a flint and steel to light it. And you use the flint and steel again to toggle it off.
