### ISSUE TITLE
Please Don't Let Mimics Spawn On The First One Or Two Days

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#474]
Not Fun To Spawn Next To A Ruined Portal, Open A Chest To Find Some Cool Stuff, And Die Instantly Because It Has Teeth, No Soul, And Forklift Certification. Especially Annoying On Hardcore I Can Imagine. That's One Way To Get A New Player To Become A Was.

What Made Me Realize Mimics Might Need To Be Pushed Back A Few Days Is Walking About 600-ish Blocks In A Gigantic Snowy Wasteland With No Resources, Finding A Ruined Portal, And Being Met With Unavoidable Death Because There Wasn't Even Any Trees I Could've Used To Make A Sword.

This Was After My Previous World I Also Spawned In A Featureless Snowy Wasteland And Died After Walking Another 500 Blocks To Find Nothing But Snow.. And A Creeper That Wandered From The Local Cave System And Snuck Up On Me.

*my luck is just perfect*

**Comment by Sollace** [comment]
There are a few chest types that don't spawn mimics: Villages, Bastions, Underwater chests, and Shipwrecks (and soon bonus chests too).

Any other chest has a chance of spawning a mimic weighted based on your player's luck, dolphin's grace, unluck, bad omen, and local difficulty. The intention is for ruined chests to have a risk that you're supposed to be prepared for before opening them, so if you're playing hardcore, don't open them on your first day. Find a village instead as those are always safe.
