### ISSUE TITLE
The Texture For Palm Logs Is Ugly And Inconsistent

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#475]
Palm Trees Are Neat. It Acts As A White Planks Type And Adds More Life To Beaches... However, The Log Is Just Ugly.

First Of All, Every Other Log Ever, Even The Nether Stems I Forgot To Include, Have Rings Inside Them, Because That's How Trees Work. I'm Gonna Be Honest, Palm Logs Look Like They're Made Of Sand.

Secondly, The Bark's Texture Doesn't Feel Like Bark At All And Is More Akin To A Barrel. It Looks Like A Barrel Filled With Sand. Though That's Probably From The Lack Of Shading In The Texture, As Looking Closer It *Does* Resemble Bark Again.

And Thirdly (and my biggest issue with the log), The Stripped Texture Makes No Sense. Every Other Log's Stripped Variant Takes From The Top And Bottom Texture Of The Log, The Interior. Palm Just Looks Neon And Weird.
*also zap apple logs have the same issue but it's less pronounced as it's at least a similar colour.*

![image](https://github.com/user-attachments/assets/b2d79c48-e2a6-4eea-9684-787fc7e3a4ab)

Planks, On The Other Hoof, Are Amazing, Love Em To Bits. But Palm Logs Make GD's Early 2.0 Phase Look Like A Masterpiece.

**Comment by Sollace** [comment]
The palm textures are modelled after what palms looks like. Palm trees do not have the same bark as regular trees nor do they have rings.

**Comment by EternaDash** [comment]
> Palm trees do not have the same bark as regular trees nor do they have rings.

For The Bark, What Makes It Look Weird Is The Lack Of Shading That Normally The Logs Have.

For As For The Rings: Huh, Didn't Know That. Neat.

The Stripped Log Texture Is Still Really Off Though, Like Every Other Log It Should Match The Interior Of The Tree In Colour. And I Doubt Stripping A Palm Tree Of It's Bark Just Reveals Neon Toothpaste Colour.

**Comment by PrinceDrowsy** [comment]
While you're entitled to your own opinion, this post is an incredibly rude way to put it, especially for free content she and others are making for fun rather than pay. Insults add nothing productive to a suggestion or criticism whatsoever.

**Comment by EternaDash** [comment]
> While you're entitled to your own opinion, this post is an incredibly rude way to put it, especially for free content she and others are making for fun rather than pay. Insults add nothing productive to a suggestion or criticism whatsoever.

Me And Sollace Are Friends, She Would've Said So Already If I Was Rude
