### ISSUE TITLE
Rotten Fish Don't Check Fishy Business Advancement

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#485]
So Turns Out Rotten Fish Don't Count As Fish According To Advancements?
I'm Fishing For Once In Like A Year, And I Catch What I Now Know Is A Rotten Salmon. However The Advancement Doesn't Pop, So I Assume It's Something Random And Continue. Next, I Fish A Raw Salmon And The Advancement Pops, Which Is When I Realize "Hang On, The First Thing I Caught Was A Rotten Salmon."
Rotten Or Not, They Are Fish. This Isn't A Situation Like With Corn Being A Fruit Actually.

**Comment by Sollace** [comment]
The fishy business advancement has an explicit list of items that it counts. I'm not doing anything to modify vanilla advancements nor can I really.
