### ISSUE TITLE
Baited Fishing Rods Unbait After Reeling In Even If Nothing Is Caught

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#486]
We Have A Baited Fishing Rod, We Aim Up And Cast The Line Up Like We're Trying To Catch Zeus. We Proceed To Reel It Back In Nearly Immediately Before It Hits Anything At All. Suddenly The Bait Is Gone, Vanished, Evaporated, It Left For The Milk.
Did, Like, The *Sky* Eat It?

**Comment by Sollace** [comment]
Works as intended. Using the rod consumes the worm

**Comment by EternaDash** [comment]
> Works as intended. Using the rod consumes the worm

Damn, Guess The Sky *Does* Eat It.
