### ISSUE TITLE
Making A Baited Fishing Rod Resets It's Durability

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#487]
Let's Say We Have A Fishing Rod On One Durability Point. It's About To Explode Into Little Shrapnel Of Sticks And String, And We Dig Up A Wheat Worm For No Particular Reason. We Put The Wheat Worm Onto The Fishing Rod, And Suddenly It's As Good As New. Who Needs Mending When You Have Worm.

**Comment by Sollace** [comment]
This kind of thing will be fixed in 1.21 with the move to components
