### ISSUE TITLE
Baskets Take Knockback And Flash Red When Hit

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#488]
I Understand They're Entities, Like How Boats Are. But Boats Don't Flicker Or Take Knockback, And It Looks Really Weird. It Also Turns Into A Puff Of Smoke Like A Regular Mob, Also Unlike A Boat.
I Don't Think Baskets Are Alive... Are They? *if they are i am so on the most wanted list for the united states of basketland*

**Comment by Sollace** [comment]
> I Don't Think Baskets Are Alive... Are They?

_shhhh don't let them know_

**Comment by Sollace** [comment]
Closing this as the knockback is a necessary means of moving the basket.
