### ISSUE TITLE
[BUG] Exception in server tick loop

### ISSUE THREAD

**Issue by eyelessderp** [Sollace/Unicopia#491]
Using the beta for the 1.21 version of the game, the game crashes as soon as I try to load into a world. I usually try to figure stuff like this out myself but after making sure everything is up to date and installed correctly the problem still persists. 

 - Minecraft Version: 1.21
 - Mine little pony -4.12.1+1.21

**Mod Loader:**
 - [X] Fabric
 - [ ] Quilt
 - [ ] Neoforge (with connector)

**Client/Server Logs**
[crash-2024-10-12_19.05.18-server.txt](https://github.com/user-attachments/files/17351781/crash-2024-10-12_19.05.18-server.txt)

**Comment by Sollace** [comment]
Thanks for the report. This is a change in https://github.com/MineLittlePony/Fabwork which has broken backwards compatibility. I'll look at fixing it in there prior to the release. For now you may have to remove bigpony.

**Comment by Sollace** [comment]
Sorry, Fabwork, not Kirin (my bad, doing this after midnight here)

**Comment by eyelessderp** [comment]
Thank you for taking the time to respond, removing bigpony worked perfectly!
