### ISSUE TITLE
Flying Too High Pulls You Down Rapidly For Some Reason

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#492]
I Don't Know Why, But While I Was Flying Well Above The Clouds Where It Doesn't Rain, I Started Getting Pulled Down, Rapidly. It Felt Kinda Like The Force That Pulls You Down Further Into The Void, But It Was Trying To Splat Me Into The Earth Despite There Being No Void In Sight. I Click V Twice To Stop And Start Flying Mid-Air To Maybe Reset It: Nope. I Try To Flap My Wings To Counteract It, Maybe I'm Just Descending? Nope. Nothing I Did Stopped It, Which I Highly Doubt Is Intentional. Only Stopped Once I Landed On The Ground, Would've Killed Me When Landing From How Fast I Was Going If I Didn't Stop Flying Before Hitting The Floor.

**Comment by Sollace** [comment]
I've never had this happen for me.
