### ISSUE TITLE
Nourish Earth Sometimes Breaks Rock Crops

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#493]
https://github.com/user-attachments/assets/c8f7f7fc-5156-4e09-81a8-0ad87b8aecea

Why? Not Sure, It Just Kinda Does. And Whenever Fully Mature They Are Essentially Guaranteed To Break.
*also i'm on 1.20.4*

Update: One Grew Right In-Front Of Me And Broke Itself, So It's Just Whenever They Grow They Can Randomly Break

**Comment by Sollace** [comment]
Ah yeah. That does look like a bug. Seems like the farmland is reverting to dirt when a neighboring block changes which causes them to pop off. Might be that the rock crop isn't in the block tag that all crops are supposed to be.

If that's the case it should be easy to fix and have in the same update I plan to do to fix #490
