### ISSUE TITLE
[BUG] Critical injection failure: Callback method onTrySleep

### ISSUE THREAD

**Issue by dmkenza** [Sollace/Unicopia#498]
**Describe the bug**
Can't run on 1.21.1 with sinytra connector

**Version Information:**
 - Minecraft Version: [e.g. 1.21.1]
 - Unicopia Version:  1.3.101.21  

**Mod Loader:**
 -  Neoforge (with connector)
----
[log.txt](https://github.com/user-attachments/files/17444854/x1.txt)

**Comment by Sollace** [comment]
This is a known issue that I believe was reported already to the synatra connector devs. It's up to them to look at it first as I believe this is due to a change neoforge makes which connector may need to fix.
