### ISSUE TITLE
[ Feature Request ] Butterfly Spawn control

### ISSUE THREAD

**Issue by coppercore** [Sollace/Unicopia#50]
Firstly, thank you for all the work on this awesome little mod.

Simply put, I'd like to request a way to control how many butterflies will spawn, or at the very least, a toggle/command ingame to toggle spawning just of butterflies.

**Comment by PoneyClairDeLune** [comment]
Same here. Butterflies are chugging a way too much portion of CPU resource just for their ticking...

**Comment by Sollace** [comment]
I will reduce the spawn rate for butterflies (if I'm unable to fix the cpu resource drain). Thanks for reporting that!
