### ISSUE TITLE
Heart Bound Sometimes Doesn't Decrease It's Level When Triggered

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#500]
https://github.com/user-attachments/assets/1b602ca1-9c59-47a7-868f-4c07d4f9910c

Sometimes It Does, Sometimes It Doesn't. Has A Mind Of It's Own, Really.
(also 500th issue, lets goooo)

**Comment by Sollace** [comment]
There's a random chance of it not consuming based on your player's luck/unluck stat. The base luck when computing the heartbound effect for non-earth ponies with no luck/unluck, or dolphin's grace, or bad omen status effects (which all impact your computed luck) is +3.
