### ISSUE TITLE
Throwing A Pearl Into A Black Hole Should Obliterate You

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#502]
As Of Right Now, The Pearl Just Stops Existing. But Seeing How Pearls Teleport A Pony Where They Land, You Can See Where I'm Going With This.
I Mean, Logically, It'd Teleport The Pony Inside The Black Hole, Which Would Unsurprisingly Instantly Kill Them.

**Comment by Sollace** [comment]
I don't really agree with this. The pearl only teleports you if it _hits something._ 

There's nothing in the blackhole for it to hit, so it just gets destroyed.
