### ISSUE TITLE
Throwing A Horseshoe Collapses Reality (by crashing)

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#505]
_Gotta Bring Out Fullscreen Capture For This One._

https://github.com/user-attachments/assets/9d11f0db-0a19-4586-8d73-bce5497b65bf

World Also Insta-Crashes Upon Load, Bricking It Permanently, So That's Not Ideal.
Here's The [latest.log](https://github.com/user-attachments/files/17483658/latest.log) File.

**Comment by Sollace** [comment]
Wait for next release.
