### ISSUE TITLE
Chitin Spikes Are Comically Overpowered

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#507]
https://github.com/user-attachments/assets/159f254f-84e2-4f18-aafc-30d9635b20d2

This Armour Is So Good You Can Survive A 100 Block Fall Effortlessly. It Takes Eight Hits From The Warden To Kill You On Normal.
You Are Practically Indestructible, Yet These Tiny Pokey Things Instantly Evaporate You From A Mere 10 Blocks.
That's More Ridiculous Than A Stalagmite, By A Lot, Which Doesn't Even Kill At 50 Blocks In This Scenario.
*that might be a tad overkill.*

Edit: Just Tested, This Thing Is Dealing A Whopping 132 Damage From Just 10 Blocks.

**Comment by Sollace** [comment]
Big surprise. Spikes hurt when you slam into them at sonic speeds.

Damage is dealt only if you move towards the pointed ends, and scales with speed (iirc). This is the intended behaviour.
