### ISSUE TITLE
[BUG] Crushing Blow disconnects player from world

### ISSUE THREAD

**Issue by OmnipresentMicroorganism** [Sollace/Unicopia#508]
Whenever I use the Crushing Blow ability, it kicks me from the world back to the title screen. Each of the other abilities work, it's only Crushing Blow that fails. I'm playing on a 1.21.1 singleplayer creative world, Fabric loader 0.16.7, Unicopia 1.13.11.

A video showing the bug (sorry for the lag:)
https://github.com/user-attachments/assets/24e3c6d0-1178-4862-b755-211e0ecdc296

And the latest.log:
[latest.log](https://github.com/user-attachments/files/17496335/latest.log)

**Comment by Sollace** [comment]
Thanks. This is a known issue.
