### ISSUE TITLE
Clouds Can Spawn Structures (possible compat with yung's better mineshafts)

### ISSUE THREAD

**Issue by EternaDash** [Sollace/Unicopia#515]
(note: i am on 1.21.1 minecraft, 1.3.12 unicopia)
![image](https://github.com/user-attachments/assets/3e468a84-4679-446c-ba5a-176d6c5ff78b)
I Don't Know If This Is A Issue With [YUNG's Better Mineshafts](https://modrinth.com/mod/yungs-better-mineshafts) Specifically Or If Other Structures Can Spawn On Clouds Still.
Either Way, It Definitely Looks Silly.

**Comment by EternaDash** [comment]
I Just Realized I Did My 100th Issue, And I Didn't Do Anything Interesting
Buck

**Comment by Sollace** [comment]
The clouds are generated using a cave carver, and the cloud blocks themselves are excluded from the world heighmap. You're going to have to take this to Yung's Better Mineshafts because there's nothing more I can do to make this work.
