### ISSUE TITLE
[BUG] Arcane Rift Spell causes the server to crash.

### ISSUE THREAD

**Issue by LilacRaven** [Sollace/Unicopia#516]
**Describe the bug**
Upon casting the Arcane Rift spell or gem, the entire server crashes.

**Expected behavior**
For the Arcane Rift spell to be cast without the server crashing.

**Steps to reproduce**
The steps to reproduce the bug are unclear, but seemingly, after multiple casts and dispelling of the Arcane Rift spell, the spell will eventually crash the server after a certain period of time, and has been unable to be recast without crashing.

**Screenshots**
Video recording of the bug: https://filebin.net/yuoz9gnwosjgyt2l

**Version Information:**
 - Minecraft Version: 1.21.1
 - Mine Little Pony Version: 4.12.1 +1.21

**Mod Loader:**
 -Fabric

**Comment by Sollace** [comment]
Please attach your server logs

**Comment by LilacRaven** [comment]
[crash-2024-11-18_11.51.15-server.txt](https://github.com/user-attachments/files/17803738/crash-2024-11-18_11.51.15-server.txt)

**Comment by Sollace** [comment]
Thanks. Ye looks like a bug.

For now just try to avoid using the arcane rift until I can get a fix out.

**Comment by LilacRaven** [comment]
Sure thing, thank you!
