### ISSUE TITLE
[BUG] Server crashing

### ISSUE THREAD

**Issue by LilacRaven** [Sollace/Unicopia#518]
**Describe the bug**
When some or just one player in the server loads into certain chunks on the map, a crash will occur, disconnecting both the users and crashing the entire server.

**Expected behavior**
The expected behavior would be for the server not to crash.  

**Steps to reproduce**
It seems to happen sporadically. Some players were also unable to load into the server again without causing it to crash, an issue that would often randomly solve itself.

**Screenshots**

**Version Information:**
 - Minecraft Version: [1.21.1]
 - Mine Little Pony Version: 1.21.1

**Mod Loader:**
 - Fabric

**Client/Server Logs**
If applicable, add log files by uploading them as attachments or put them below.
[crash-2024-11-19_01.01.16-server.txt](https://github.com/user-attachments/files/17819400/crash-2024-11-19_01.01.16-server.txt)

**Comment by Sollace** [comment]
This looks like a problem with Ledger or with Quilt. Given the crash report specifically calls out quilt, my bet is you would have the best luck reporting it to them.

**Comment by LilacRaven** [comment]
Thank you for the response!
