### ISSUE TITLE
[request] Stressed effect is excessive 

### ISSUE THREAD

**Issue by LilacLulamoon** [Sollace/Unicopia#52]
The stressed curse is more common and nauseating than it needs to be. Do you think you could make it way less common to get from an enchantment table, or at least reduce the shaking cause by it?

**Comment by LilacLulamoon** [comment]
so far i've gotten stressed 3 every single time i've enchanted something, that seems straight up unfair

**Comment by ghost** [comment]
> so far i've gotten stressed 3 every single time i've enchanted something, that seems straight up unfair

This has been my experience as well.  Something is wrong with the weighting for this enchantment, and as a result enchanting tables are effectively useless.  I've resorted to compiling my own jar with this enchant excluded, which I've attached here.  The only change is commenting out where the Stressed enchant gets registered.

[Unicopia-1.0.0-beta.15-NO-STRESSFUL.zip](https://github.com/Sollace/Unicopia/files/8191106/Unicopia-1.0.0-beta.15-NO-STRESSFUL.zip)
