### ISSUE TITLE
[BUG] [1.21.1] Unicopia + Terralith causes worldgen freeze serverside

### ISSUE THREAD

**Issue by Dragunsblood** [Sollace/Unicopia#521]
**Describe the bug**
The combination of terralith and unicopia on my server seems to be causing a freeze when trying to load serverside. removing either mod resumes normal function.

**Expected behavior**
Expected the world to generate as intended and the server to finish starting.

**Steps to reproduce**
Install terralith and unicopia, try to launch server with both.

**Screenshots**

**Version Information:**
 - Minecraft Version: 1.21.1
 - Mine Little Pony Version: 4.12.1

**Mod Loader:**
 - [ X ] Fabric
 - [ ] Quilt
 - [ ] Neoforge (with connector)

**Client/Server Logs**
If applicable, add log files by uploading them as attachments or put them below.

<details>
```
[latest.log](https://github.com/user-attachments/files/18050852/latest.log)

```
</details>

**Comment by Sollace** [comment]
I suggest reporting this to terallith. There's nothing I can really do to fix this as it's a problem with the biomes overlapping.

**Comment by Sollace** [comment]
Nothing I can do to fix this. Report it as an issue to Terralith.
