### ISSUE TITLE
Bugs, and Polearm Balance

### ISSUE THREAD

**Issue by Silversky13** [Sollace/Unicopia#64]
I adore this mod.  I just made my account so I don't know if I should have split these up into separate posts or not. Please forgive me if so.
A few bugs with new release.

- **Batponies Bug:** When hanging upside down if you jump it allows you to run around and jump on ceilings permanently until you hit g again. It's not really a bad thing to climb around, it's just when they step off a ledge they fall upwards until you hit G again. It allows them to gain absurd height using trees, fall to their death onto the roof of a cave, or fall out of the world into the sky and die. 

- **Unicorns Bug:** Sometimes when switching spells using gemstones it will keep the shield spell instead. It seems kind of random when it happens and with what spells. Could just be me, I'm still figuring out how the spells and spell book works. 

As a separate issue, I have no idea how to make the unicorn ability with Shift+Teleport button work or what it does. The icon changes, but I only get the failure sound trying to do anything with it. Perhaps I'm not using it right, or perhaps it's a bug, I'm really not sure, but I've tried everything I can think of. Really like the Wololo reference as well

- **Rift Gemstone Possible Bug:** This is more just a visual thing, and it may be on purpose. The visual effect for rift magic spell is on a 45-degree angle and floats off the ground when cast. It works wonderfully as it's supposed to, it just has that visual thing I thought I should mention.

- **Polearm Balance:** I love the pole arms being included. They are amazing, please keep them. The only issue is that they are the best weapon in the game by far now to the point of being overpowered. The issue is that they hit as hard as the sword and have the same enchantments (including sweeping edge), but are cheaper than the sword and hit so fast and from so far away that they are better than any other weapon in pretty much every situation, especially when combined with the higher mobility of flight. 

I know you wanted them to be used as a weapon that flying creatures use to attack which is why they have such a long range, and they work great for that, but they absolutely delete anything within 7-11 blocks by spam clicking. It makes it so that the only mobs that are even a minor threat are ranged mobs and bosses with ranged attacks. They are also significantly better than any ranged weapon or spell because of how fast they hit considering most ranged attacks tend to happen at relatively close ranges, and most races can close the gap so fast as well. It also begs the question, why cast one of the spells and use mana, or use another ability of the other races, when I can just spam click my polearm and delete the enemy 8 blocks away? If you are playing with friends, it also means that anyone without a polearm generally doesn't even get the opportunity to fight hostile mobs at all unless there are alot of them, which is a bummer for those that heavily enchant axes and swords.

_My suggestion, or request I suppose, for polearms is that they have their stats adjusted so that their attack speed is very very slow, maybe the slowest of all weapons/tools be default, and that their base damage be reduced by 1 or 2._

I flew around a bit and did some skirmish type fly-by attacks against mobs and found that lowering attack speed (by purposely clicking very slow) would have almost no impact on this type of use. It also wouldn't stop someone from hovering and clicking, but it would impact the hovering spam click and ground-based spam click usage, basically heavily discouraging it. It would also encourage people to switch to a different melee or ranged weapon, use their racial abilities/spells, or rely on a friend within shorter distances so the rest of your mod can really shine as well. 

The reduced damage could also account for it being as cheap as a shovel, as well as its increased striking range. If it doesn't quite pack that _hit_ you wanted, another possibility is to still lower damage and attack speed like above and also include Knockback as default if you wanted so it appears to hit harder without actually really hitting harder.

**Comment by Sollace** [comment]
>Rift Gemstone Possible Bug:

This is intentional. The portal is oriented to the direction you're facing.

> Unicorns Bug: 

I'm not sure what this is referring to. Swapping spells with gems doesn't cancel spells you have cast. They'll remain active until you dismiss them.

> Batponies Bug:

That is indeed a bug! I'll fix it for the next release.

> I have no idea how to make the unicorn ability with Shift+Teleport button work or what it does

Shift+Teleport switches it to teleport you to the far side of blocks instead of the nearest, so you can go through walls.

> I don't know if I should have split these up into separate posts or not.

This is fine, but in future it would be better to put each of these into separate issues so I can better keep track of them. Thanks for the feedback!

**Comment by Silversky13** [comment]
Thanks for your response. Sorry, in the future I'll open separate ones. 

For the spells swap I mean that sometimes I would swap to the rift spell for example and change the gemstone normally, but when it cast it would cast the default protection shield spell on occasion, like it didn't switch but still used the gem visually. But it seems to be very rare and random when or if it happens. The vast majority of the time it works perfect, so maybe this is more a game lag/tick issue.

Thank you for telling me about the shift teleport that makes alot more sense now and for looking into the polearm balancing.

**Comment by Sollace** [comment]
@Silversky13 Ah, you might still have the gem in your hand.

If you have a gem with a spell in your hand, it will use that instead of what's equipped in the slot.

**Comment by Silversky13** [comment]
Oh, that would make sense then. Also that is super cool, I will keep that in mind cause I had no idea
