### ISSUE TITLE
Idea: Endgame Alicorns

### ISSUE THREAD

**Issue by RivetTrain587** [Sollace/Unicopia#65]
I think it would be really neat if the alicorn race was not just something for people in creative mode, but something you could become in survival by "earning" it in some way, like by defeating the wither or defending a village from a raid. 

If that was the only way to become an alicorn, then that would prevent people from just choosing to be an alicorn right from the start. I can see how that might be a bit OP for the early game, but I think it would be interesting to give people the option to become an alicorn as some sort of endgame reward.

**Comment by Sollace** [comment]
Alicorn was never intended to be available in survival. Only reason I added it was so I could more easily test the abilities from different races. If I were to add them, even as an endgame feature, I'd first have to do some balancing to make them fit into the game.

**Comment by RivetTrain587** [comment]
Yeah, I can see how they might need a bit of balancing. I do still think having some sort of alicorn-like endgame upgrade (maybe a nerfed "ascended" version?) might be nice to have to let people use parts of the mod that they might have otherwise missed out on early/mid game. 

I know non-flying races can fly with the Wings of Icarus, but there isn't a magic equivalent for the non-magical races (other than maybe using a metamorphosis potion), for example.

I definitely get how having someone who couldn't fly at the start suddenly being able to do sonic rainbooms could be a bit overpowered, but I also think having something like an alicorn race would let people get a taste of what playing as the other races would be like. 

Then again, that might require adding different "kinds" of alicorns, and I'm not sure how much of a headache that would be to implement.

**Comment by RivetTrain587** [comment]
Earlier today, I found myself thinking about the pony MC servers I've played on in the past and how they dealt with alicorns, and I remembered one server I used to play on that allowed people to "buy" alicornhood with in-game currency, but the cost was so high that alicorn players were difficult to come by.

That left me wondering if something like that could be applied to Unicopia alicorns. I don't mean making them super expensive currency-wise, but having the effort needed to become an alicorn be at least great enough that people don't simply gun for alicornhood as soon as they start out. Maybe something like getting a ridiculously difficult to get achievement? Getting every single achievement out there?

I'm not entirely sure how easy any of what I mentioned above would be to implement. Would using that approach be more difficult than nerfing alicorns?

**Comment by Sollace** [comment]
Don't worry, I have an idea on how I can make alicorn a playable race. It will probably mean nerfing the alicorn amulet a little, but I hope you like it when it's eventually done.

**Comment by BlasterM5** [comment]
I always thought of a balanced alicorn being a Jack of All Stats - they have the abilities of all three races, but to a lesser extent - not as fast as a pegasus in flight, not as powerful as a unicorn with pew pew, not as strong as earth pony - but they still have abilities from all three. A versatility race that sacrifices raw strength in any one area for utility in all areas.

**Comment by MimzyFang** [comment]
Suggestions from my suggestions google sheet:

- Each pony should maybe have some form of way to activate the power of an alicorn like some great challenge just like how twilight completed star swirl's spell each pony type should have something specifically for their traits, for example Pegasus should maybe make something from clouds or something to do with their flight and doing this will turn them into an alicorn.
- More movement too ponies to give it that less blocky feel and maybe fluffy manes.
