### ISSUE TITLE
Discs playing to whole server on multiplayer

### ISSUE THREAD

**Issue by Silversky13** [Sollace/Unicopia#67]
The discs in the mod are great, but they don't fade over distance like other discs. Only really a problem on multiplayer but could be used as a means of trolling by starting and stopping the disc or spamming it. This should be able to be fixed really easily by just converting the music file from stereo to mono using audacity or another program if they work the same was as other music discs. 
It would be awesome if this could be fixed. 
Alternatively, if you sent me the specific music files you used, I might be able to see if I can convert them for you and send them back.

**Comment by Sollace** [comment]
Closed with #69
