### ISSUE TITLE
Changelings are incapable of gaining saturation from eating love

### ISSUE THREAD

**Issue by Silversky13** [Sollace/Unicopia#71]
As the title says. The new love items like the love bucket, bottle o love, or mug o love will not replenish any hunger saturation when consumed. It does get rid of the nausea effect though. 
At first I thought Changelings couldn't eat, but I see they can eat meat now.

**Comment by Sollace** [comment]
The love replenishes hearts, not hunger.

**Comment by Silversky13** [comment]
Gotcha
