### ISSUE TITLE
Funk, just funk playing across full world

### ISSUE THREAD

**Issue by Silversky13** [Sollace/Unicopia#73]
The disc Funk, Just Funk still plays across full world instead of falling off after a certain distance like all the other discs. All other discs have been fixed already, its just this one that seems to have been accidentally missed. Thank you for taking the time to fix them, I'm enjoying the new release.

**Comment by Sollace** [comment]
Thanks! Brining in @FollowSlipstream as they did the fixes for the rest.

(I don't really understand what they did, all I did to create the audio files was convert them to ogg format in audacity)

**Comment by Sollace** [comment]
Oh, though maybe this isn't an issue, because the funk disc intentionally has a longer range than the rest.

**Comment by Sollace** [comment]
```
  "music_disc.crusade": {
    "category": "blocks",
    "sounds": [
      { "name": "unicopia:record/crusade", "stream": true}
    ]
  },
  "music_disc.popular": {
    "category": "blocks",
    "sounds": [
      { "name": "unicopia:record/popular", "stream": true}
    ]
  },
  "music_disc.pet": {
    "category": "blocks",
    "stream": true,
    "sounds": [
      { "name": "unicopia:record/pet", "stream": true}
    ]
  },
  "music_disc.funk": {
    "category": "blocks",
    "sounds": [
      { "name": "unicopia:record/funk", "stream": true, "attenuation_distance": 21120}
    ]
  },
```

**Comment by Silversky13** [comment]
Odd. I know that if it can't be fixed in however they did it, if you open it in audacity and then use the "Mix" tool to mix it to Mono and export it to OGG it should accomplish the same thing with the distance fall off of standard minecraft discs. As far as I know it is because Stereo files are used for the games background music to play across the full world, while Mono files are used in other sounds and music discs to play to only certain locations. Might just be easier to change the distance though. I'm only concerned about the distance if people decide to spam the disc in a jukebox to troll.

**Comment by FollowSlipstream** [comment]
I might've missed that one. Will sort it out later today! 
Though indeed it looks intentional for one reason or another. @Sollace is this something we want to change? I think keeping it in line with the others makes sense as it'll be culled long before you reach that 21120 distance meaning it would just unpleasantly chop off, and also it's mildly immersion breaking.

**Comment by Sollace** [comment]
@FollowSlipstream It is supposed to be just slightly longer range than the others. Not sure how I got to the 21120 number, but I'll definitely check that it's still doing what it was meant to.
