### ISSUE TITLE
Race Change on Death 

### ISSUE THREAD

**Issue by Silversky13** [Sollace/Unicopia#74]
This doesn't seem to happen every time a death occurs, but occasionally when you die it will make you a unicorn. I've noticed that this tends to be mainly isolated to Earth Ponies dying and being changed so far. It also seems to stick with the player even if you use a potion of metamorphosis or when using the effect give command to change them back to earth pony. Occasionally, it allows the potion or command to work, but it seems more likely to immediately change you back to unicorn instead of what you tried to change your race to because the effect kills you. I haven't yet seen it happen with other races.

**Comment by Sollace** [comment]
Can you try turning off the mine little pony detection in the mod's settings?

**Comment by Silversky13** [comment]
I've been unable to recreate this bug since posting it even once with many people playing and many deaths. It may have just been another mod conflicting in some obscure way with the particular deaths. I apologize for taking so long to respond. I had alot going on and a death in the family so alot of things got pushed to the wayside. I look forward to the next update

**Comment by Sollace** [comment]
Alright, no problem. Thanks for responding, and you have my condolences for your family member.
