### ISSUE TITLE
Inventory GUI messed up after flying as a pegasus

### ISSUE THREAD

**Issue by MarcyMuffins** [Sollace/Unicopia#8]
Ok so, here's the problem in pictures:
1. Normal hud as an earth pony (or any other non-flying race):
![изображение](https://user-images.githubusercontent.com/36843738/55672907-5dec5f00-58a9-11e9-9414-b51341eabd56.png)
2. Inventory hud as an earth pony (or any other non-flying race):
![изображение](https://user-images.githubusercontent.com/36843738/55672914-79f00080-58a9-11e9-8a4d-aa50677bf685.png)
3. Normal hud as pegasus (notice the bars at the bottom not overlapping and slightly offset):
![изображение](https://user-images.githubusercontent.com/36843738/55672922-9ab85600-58a9-11e9-8ca2-4a4be1911f34.png)
4. Inventory hud as pegasus (notice the bottom bar):
![изображение](https://user-images.githubusercontent.com/36843738/55672927-b15ead00-58a9-11e9-9db8-bbfb9b72e850.png)
Ive checked with and without additional mods, the problem still persists

**Comment by Sollace** [comment]
I'm going to need screenshots without any other mods.

**Comment by Sollace** [comment]
This may be a forge version issue. What version are you trying to run it with? I know my one is heck old.

![image](https://user-images.githubusercontent.com/6429283/55673881-27fda980-58ae-11e9-92d9-2e8f2e99eea4.png)

**Comment by MarcyMuffins** [comment]
I'm currently using the latest forge version, will send screenshots soon

**Comment by Sollace** [comment]
@AceMuffins 
mcfVersion=14.23.2.2654

That's the version the mod is built with and it works there. You'll have to be more specific with which version.

**Comment by MarcyMuffins** [comment]
Alright, I'ma load up and check:
Forge 14.23.5.2824
I'll move every mod and config to a profile with the version you specified, and I'll check if the issue persists

**Comment by MarcyMuffins** [comment]
Ok so, loading up with the version specified was impossible, since all mods, understandably, required a newer version of forge, the earliest version I can try is 14.23.5.2779

**Comment by MarcyMuffins** [comment]
I will try without all the mods, however if the issue remains in the earliest possible version with the mods present, it will mean that every pack with this mod will have this issue

**Comment by MarcyMuffins** [comment]
The issue does in fact persist on the earliest possible version (14.23.5.2779) with all the mods in place, after some testing I've concluded that some mod does cause the issue, and when I find the mod responsible, I will report it to you

**Comment by Sollace** [comment]
Okay, great!

A quick note: The current method is, in retrospect, a terrible way of moving the Gui elements, and it will probably be changing.

I'll hold off on that until you get back to me, though.

**Comment by MarcyMuffins** [comment]
ok... this is weird, the mod that seems to cause it is Mantle, the library mod.
Which means tinkers construct is out the window, i also suspect that this might be the issue, but dont quote me on that:
(taken from Mantle description)
"Also adds a reworked hearts display with overlaid colored hearts, instead of rows over rows of stacked hearts. The different colors only appear if you have a way to increase your max health, regular hearts are unchanged."

**Comment by Sollace** [comment]
@AceMuffins Okay, now this all makes sense. I can see that everything after the hearts have been offset by the same amount.

That should make it easy to fix.

**Comment by MarcyMuffins** [comment]
Nice
