### ISSUE TITLE
Iris Mod causes entities to be occluded and hidden from view by Unicorn Shield Spell effect

### ISSUE THREAD

**Issue by coppercore** [Sollace/Unicopia#81]
Unicopia complied from latest source as of 2022-Nov-23. (Also happens with Latest beta 27)

Getting this oddball effect when the shield is toggled on, whereas the shield is transparent, somehow, when the Iris mod is enabled, even with NO shaders enabled, this happens.

I've confirmed it's Iris doing this, as when Iris is disabled, the visibility of entities acts as normal through the shield.

Happens in first and in third person.

Screenshots:
![2022-11-23_17 23 28](https://user-images.githubusercontent.com/35123789/203656405-77c08365-db2f-4fbe-8813-f7550eaa1fcb.png)
![2022-11-23_17 23 32](https://user-images.githubusercontent.com/35123789/203656411-8968abc8-a840-4abd-a009-5cf026a933ba.png)
![2022-11-23_17 23 41](https://user-images.githubusercontent.com/35123789/203656416-55f3d95a-6139-4004-9399-bcbb02e58144.png)
![2022-11-23_17 23 45](https://user-images.githubusercontent.com/35123789/203656422-551675de-5856-4dc8-a8ae-a4cf641bf7e8.png)

**Comment by coppercore** [comment]
As an addendum, I have noticed that having Iris enabled will cause butterflies to not be visible at all times, unicorn shield or not. I can open a new issue if needed, but I have a feeling these are related issues.

**Comment by coppercore** [comment]
It gets more amusing too. Water and even Ice seems to be occluded.

Here is a shot of standing on a frozen river with the shield on.
![image](https://user-images.githubusercontent.com/35123789/205447224-b9db291a-9dae-4bc5-9a3a-ec512482deaf.png)

**Comment by Sollace** [comment]
It's a problem with transparencies. Can you try setting graphics to "Fabulous" and see if that fixes it?

**Comment by coppercore** [comment]
Fabulous fixes the transparency issue, but now the bubble is simply missing.

![image](https://user-images.githubusercontent.com/35123789/205461517-7b61a88e-242b-43d2-8384-b22aebd52b20.png)

This is just flat Iris enabled, no shaders enabled.
