### ISSUE TITLE
Butterfly config toggle

### ISSUE THREAD

**Issue by coppercore** [Sollace/Unicopia#83]
This is more of a simple request, but I would like to have the option to enable/disable the Unicopia butterflies. I'm in a situation where I have another mod that spawns butterflies, so it seems a bit redundant to have both fluttering around.

**Comment by Sollace** [comment]
That's a reasonable request, however keep in mind at a later point the butterflies may become a necessary food source for bat ponies!

Out of curiosity, though, what mod is it that also adds butterflies?

**Comment by coppercore** [comment]
I have wondered about that actually myself.

This mod here adds several variety of butterlies, of which you can actually right click on them and even pick them up.

https://www.curseforge.com/minecraft/mc-mods/chirpys-wildlife

It seems to play very well with Unicopia, haven't ran into an issue yet,

It would be amusing if you could also just eat them after picking them up instead of having to kill them.

**Comment by Sollace** [comment]
Yeah, I honestly need to improve the butterflies.
