### ISSUE TITLE
Drop rate for Oats and Oat seeds seems off

### ISSUE THREAD

**Issue by coppercore** [Sollace/Unicopia#86]
Git build of Unicopia, also is present in last release. The drop rates for Oats vs Oat Seeds seems to be backwards, where a single three block high stalk will drop 3 Oats and 8-9 Oat Seeds.

As an aside, I almost wonder if the drop rate is a little on the higher side even when correct, as these end up being some of the best crops in the game in general. I know fries are tasty, but they might be too tasty, heh.

![image](https://user-images.githubusercontent.com/35123789/205774434-0e5e347f-b637-4ccb-a227-b1b8be132852.png)

**Comment by Sollace** [comment]
I'll have to check what the rates are for vanilla, as I based on on that loot table. 3x is expected, though, because the plant grows 3 blocks tall.

**Comment by coppercore** [comment]
That's fair. Only thing I would ask is the growth rate the same, well, same per Oat?

Like I figure it would take 3x the time for these to grow, or at least 2x.

Granted growth rates in Minecraft in general are kinda wack and just chance based if I remember right.
