### ISSUE TITLE
Changeling remains 2 blocks tall when using Pehkui

### ISSUE THREAD

**Issue by Sidewinder4t2** [Sollace/Unicopia#88]
Tested using Pehkui 3.6.0 and 3.5.0, Minecraft 1.19.2, and Unicopia beta 28
Changeling view position changes, but collision dimensions remain 2 blocks tall even when they transform into 1 block high entities (or blocks).

**Comment by Sollace** [comment]
I didn't notice the versions on this before. Can you test this on the latest unicopia 1.1.0-beta?

**Comment by Sidewinder4t2** [comment]
Checked with Pehkui 3.5.0, 3.7.5 and the last version of fabric API (0.76.0) available for 1.19.2, Unicopia 1.0.0+lts and Unicopia 1.0.0 beta 30+lts. Reproduced each time. Also occurs in beta 5 for 1.19.3 with fabric API 0.76.1 and Pehkui 3.7.5.

**Comment by Sidewinder4t2** [comment]
From the digging that I did and my limited understanding, Pehkui is used for features such as Bewitchment's transformations into differently sized creatures - as such I'd speculate it's an overriding mixin or some such.
