### ISSUE TITLE
Multiplayer/Realms compatibility

### ISSUE THREAD

**Issue by izazia** [Sollace/Unicopia#89]
#34 Is this multiplayer friendly? Both my friend and I have the mod however when joining our multiplayer server we're unable to pick a tribe and most of the items/mobs are missing...

**Comment by Sollace** [comment]
Did you install it on the realm server? The mod won't work if you don't have it on the server as well.

**Comment by MimzyFang** [comment]
I don't think I's possible to use on realms since realms servers are controlled my Mojang

**Comment by Sollace** [comment]
Right, then I'm going to close this as there's nothing we can really do
