### ISSUE TITLE
Hydrophobic spell crash? Skeleton possibly related?

### ISSUE THREAD

**Issue by SkyArrow76** [Sollace/Unicopia#95]
So, been getting this crash from a ticking skeleton entity. Didn't get much info from that alone, but used Not Enough Crashes and the crash log mentioned effect.HydrophobicSpell. (To be clear, I was not using the spell, nor even knew about it yet). It's possible this is a whole separate error, but it may be related. Here's the original crash log, the detailed one, and my mods list. This is on 1.19.3. I couldn't really say how to reproduce as it seems to happen randomly.
[crash-2023-01-27_20.03.05-server.txt](https://github.com/Sollace/Unicopia/files/10524353/crash-2023-01-27_20.03.05-server.txt)
[crash-2023-01-27_21.03.03-server.txt](https://github.com/Sollace/Unicopia/files/10524354/crash-2023-01-27_21.03.03-server.txt)
[modlist 1.19.3 fabric.txt](https://github.com/Sollace/Unicopia/files/10524356/modlist.1.19.3.fabric.txt)

**Comment by Sollace** [comment]
Yeah, I know exactly what this is

**Comment by Sollace** [comment]
Nope, doesn't seem to be anything I can fix. The NotEnoughCrashes crash log was a red herring. The actual problem was that ConcurrentModificationException, which looks like is a vanilla bug since skeletons change their own AI.
