### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by 456rockybaka** [Sollace/Unicopia#96]
I can't seem to get the wings of Icarus to work am i doing something wrong how do I use them I'm on 1.18.2 Minecraft

**Comment by Sollace** [comment]
They require energy. I have a method of charging them planned for other races. For now,though, you need a magically capable pony (unicorn or changeling) to charge it for you if you're not one already.

**Comment by 456rockybaka** [comment]
Ok thank you I was already a pony ill try again, by the way, is there any way to change your magic color that I'm not aware of, if not that would be a great feature. and is there any easy way maybe a command that would disable hand movements I usually play with the mod mine little pony and the movement looks a bit awkward when you are a pony  Sorry for the long message, the mod that you created is amazing, cant wait for future updates,  keep p the great work.
