### ISSUE TITLE
Want It Need It Crash

### ISSUE THREAD

**Issue by SkyArrow76** [Sollace/Unicopia#97]
So, similar to #95 I think with the ConcurrentModificationException, but just wanted to post it to be sure it's not the same vanilla bug like you mentioned.
[crash-2023-02-24_20.00.38-server.txt](https://github.com/Sollace/Unicopia/files/10829946/crash-2023-02-24_20.00.38-server.txt)
Mods being used are just fabric api, minelittlepony, hdskins, and unicopia.
Was trying to do some testing to narrow down a crash that mentioned want it need it and a skeleton (
[crashlog2.txt](https://github.com/Sollace/Unicopia/files/10829954/crashlog2.txt)
[crashlog1.txt](https://github.com/Sollace/Unicopia/files/10829955/crashlog1.txt)
), so i tried both summoning one with an item enchanted with that and throw one to one to pick up (in video below it crashed right after cutting off).
For summoning them in, it was a 50/50 whether it would immediately crash.

https://user-images.githubusercontent.com/33587750/221327577-02bd0ef1-8804-471a-89ad-f10754491061.mp4

**Comment by Sollace** [comment]
This was fixed in this commit, but has not been released yet.
https://github.com/Sollace/Unicopia/commit/8a13b028099fc87d7625b01d515021ab87eb2222
