### ISSUE TITLE
Request for assistance

### ISSUE THREAD

**Issue by RETROGLOOM** [Sollace/Unicopia#98]
Hello! I run a Minecraft server that has this mod in use but there's a lot we are failing to understand/learn. Is there any way I could possibly get in contact with you to create a more hands-on guide for how things work? (mostly in the realm of unicorns and magic) :]

**Comment by Sollace** [comment]
First thing unicorns should do is make a spellbook. That has all the information needed for crafting spells.

**Comment by LuckyDusk** [comment]
Are diamonds the only way to get gems? I tried using a few shovels with gem finder, but I couldn't find anything.

**Comment by Sollace** [comment]
> Are diamonds the only way to get gems? I tried using a few shovels with gem finder, but I couldn't find anything.

Gem finding is mainly for finding ores, and iirc it works best on a pickaxe, I may consider adding what you're doing as a feature. There certainly should be more ways to get gemstones.

**Comment by LuckyDusk** [comment]
Yeah the book mentions finding in them ground so I wasn't to sure. Maybe amethyst could be used in some way?
